// GENERATED by gen_endpoints.py from spec/endpoints/school_support.json — DO NOT EDIT. Edit the spec + regenerate.
import { NextRequest, NextResponse } from "next/server";
import { requireSchoolScope } from "@/server/guards/requireSchoolScope";
import { validateSupportTickets_create } from "@/server/rules/support_tickets.generated";
import { listSchoolTickets, raiseSchoolTicket } from "@/server/support/tickets";
import { ok, err, meta } from "@/server/http/envelope";

const MOD = "school_support";

export async function GET(request: NextRequest) {
  const guard = await requireSchoolScope(request, "school_support");
  if (!guard.ok) return NextResponse.json(guard.body, { status: guard.status });
  const data = await listSchoolTickets(guard.actor.school_id ?? "");
  return NextResponse.json(ok(data, meta(guard.requestId, MOD)));
}

export async function POST(request: NextRequest) {
  const guard = await requireSchoolScope(request, "school_support");
  if (!guard.ok) return NextResponse.json(guard.body, { status: guard.status });
  const schoolId = String(guard.actor.school_id ?? "");
  if (!schoolId) return NextResponse.json(err("FORBIDDEN", "No school in scope.", meta(guard.requestId, MOD)), { status: 403 });
  let body: Record<string, unknown>;
  try { body = (await request.json()) as Record<string, unknown>; } catch { body = {}; }
  const fieldErrors = validateSupportTickets_create(body);
  if (fieldErrors.length) return NextResponse.json(err("VALIDATION_FAILED", "Validation failed.", meta(guard.requestId, MOD), { field_errors: fieldErrors }), { status: 422 });
  const result = await raiseSchoolTicket(schoolId, body, guard.actor);
  if ("error" in result) return NextResponse.json(err(result.error.code, result.error.message, meta(guard.requestId, MOD), result.error.field_errors ? { field_errors: result.error.field_errors } : undefined), { status: result.error.status });
  return NextResponse.json(ok(result.data, meta(guard.requestId, MOD)));
}
