// GENERATED by gen_routes (Robot 6) — DO NOT EDIT.
import { getEmailCampaigns, updateEmailCampaigns, deleteEmailCampaigns } from "@/services/email_campaigns.service";
import { ok, err } from "@/runtime/envelope";

export async function GET(_req: Request, { params }: { params: { id: string } }) {
  const row = await getEmailCampaigns(params.id);
  return row ? ok(row) : err("NOT_FOUND", 404, "email_campaigns not found");
}

export async function PATCH(req: Request, { params }: { params: { id: string } }) {
  return ok(await updateEmailCampaigns(params.id, await req.json()));
}

export async function DELETE(_req: Request, { params }: { params: { id: string } }) {
  return ok(await deleteEmailCampaigns(params.id));
}
