// GENERATED by gen_endpoints.py from spec/endpoints/school_support_detail.json — DO NOT EDIT. Edit the spec + regenerate.
import { NextRequest, NextResponse } from "next/server";
import { requireSchoolScope } from "@/server/guards/requireSchoolScope";
import { getSchoolTicketDetail } from "@/server/support/tickets";
import { ok, err, meta } from "@/server/http/envelope";

export async function GET(request: NextRequest, ctx: { params: Promise<{ id: string }> }) {
  const { id } = await ctx.params;
  const guard = await requireSchoolScope(request, "school_support");
  if (!guard.ok) return NextResponse.json(guard.body, { status: guard.status });
  const result = await getSchoolTicketDetail(guard.actor.school_id ?? "", id);
  if ("error" in result) return NextResponse.json(err(result.error.code, result.error.message, meta(guard.requestId, "school_support")), { status: result.error.status });
  return NextResponse.json(ok(result.data, meta(guard.requestId, "school_support")));
}
