// GENERATED by gen_routes (Robot 6) — DO NOT EDIT.
import { getSchools, updateSchools, deleteSchools } from "@/services/schools.service";
import { ok, err } from "@/runtime/envelope";

export async function GET(_req: Request, { params }: { params: { id: string } }) {
  const row = await getSchools(params.id);
  return row ? ok(row) : err("NOT_FOUND", 404, "schools not found");
}

export async function PATCH(req: Request, { params }: { params: { id: string } }) {
  return ok(await updateSchools(params.id, await req.json()));
}

export async function DELETE(_req: Request, { params }: { params: { id: string } }) {
  return ok(await deleteSchools(params.id));
}
