// GENERATED by gen_pages.py from spec/pages/staff_settings_changes.json — DO NOT EDIT. Edit the spec/component + regenerate.
import { SettingsChangesView } from "@/components/SettingsChangesView";

export default function Page() {
  return <SettingsChangesView />;
}
