// GENERATED by gen_routes (Robot 6) — DO NOT EDIT.
import { getReEvaluations, updateReEvaluations, deleteReEvaluations } from "@/services/re_evaluations.service";
import { ok, err } from "@/runtime/envelope";

export async function GET(_req: Request, { params }: { params: { id: string } }) {
  const row = await getReEvaluations(params.id);
  return row ? ok(row) : err("NOT_FOUND", 404, "re_evaluations not found");
}

export async function PATCH(req: Request, { params }: { params: { id: string } }) {
  return ok(await updateReEvaluations(params.id, await req.json()));
}

export async function DELETE(_req: Request, { params }: { params: { id: string } }) {
  return ok(await deleteReEvaluations(params.id));
}
