// GENERATED by _validation/gen_modules.py — DO NOT EDIT.
import { NextRequest, NextResponse } from "next/server";
import { requireStaffScope } from "@/server/guards/requireStaffScope";
import { ok, meta } from "@/server/http/envelope";
import { listChildRecords } from "@/server/lib/listChild";

export async function GET(request: NextRequest, ctx: { params: Promise<{ id: string }> }) {
  const guard = await requireStaffScope(request, "admin_settings_versions", "read");
  if (!guard.ok) return NextResponse.json(guard.body, { status: guard.status });
  const { id } = await ctx.params;
  const data = await listChildRecords("setting_activation_events", "setting_version_id", id, guard.actor);
  return NextResponse.json(ok(data, meta(guard.requestId, "admin_settings_versions")));
}
