// GENERATED by gen_routes (Robot 6) — DO NOT EDIT.
import { getUsers, updateUsers, deleteUsers } from "@/services/users.service";
import { ok, err } from "@/runtime/envelope";

export async function GET(_req: Request, { params }: { params: { id: string } }) {
  const row = await getUsers(params.id);
  return row ? ok(row) : err("NOT_FOUND", 404, "users not found");
}

export async function PATCH(req: Request, { params }: { params: { id: string } }) {
  return ok(await updateUsers(params.id, await req.json()));
}

export async function DELETE(_req: Request, { params }: { params: { id: string } }) {
  return ok(await deleteUsers(params.id));
}
