// GENERATED by gen_pages.py from spec/pages/staff_jobs_page.json — DO NOT EDIT. Edit the spec/component + regenerate.
import { JobsView } from "@/components/JobsView";

export default function Page() {
  return <JobsView />;
}
