// GENERATED by gen_rules (Robot 7) from canonical + rule_catalog — DO NOT EDIT.
export type FieldError = { field: string; message: string };

export function validateAdmitCards(input: Record<string, unknown>): FieldError[] {
  const errors: FieldError[] = [];
  if (!String(input.student_id ?? "").trim()) errors.push({ field: "student_id", message: "Student id is required" });
  if (!String(input.participation_id ?? "").trim()) errors.push({ field: "participation_id", message: "Participation id is required" });
  if (!String(input.school_id ?? "").trim()) errors.push({ field: "school_id", message: "School id is required" });
  if (input.status !== undefined && !["generated", "issued"].includes(String(input.status))) errors.push({ field: "status", message: "Status is not a valid status code" });
  return errors;
}
