// GENERATED by gen_rules (Robot 7) from canonical + rule_catalog — DO NOT EDIT.
export type FieldError = { field: string; message: string };

export function validateAnswerKeys(input: Record<string, unknown>): FieldError[] {
  const errors: FieldError[] = [];
  if (!String(input.olympiad_id ?? "").trim()) errors.push({ field: "olympiad_id", message: "Olympiad id is required" });
  if (!String(input.grade ?? "").trim()) errors.push({ field: "grade", message: "Grade is required" });
  if (!String(input.total_questions ?? "").trim()) errors.push({ field: "total_questions", message: "Total questions is required" });
  if (!String(input.key ?? "").trim()) errors.push({ field: "key", message: "Key is required" });
  if (input.status !== undefined && !["archived", "draft", "published"].includes(String(input.status))) errors.push({ field: "status", message: "Status is not a valid status code" });
  return errors;
}
