// GENERATED by gen_rules (Robot 7) from canonical + rule_catalog — DO NOT EDIT.
export type FieldError = { field: string; message: string };

export function validateAwards(input: Record<string, unknown>): FieldError[] {
  const errors: FieldError[] = [];
  if (!String(input.result_id ?? "").trim()) errors.push({ field: "result_id", message: "Result id is required" });
  if (!String(input.student_id ?? "").trim()) errors.push({ field: "student_id", message: "Student id is required" });
  if (!String(input.school_id ?? "").trim()) errors.push({ field: "school_id", message: "School id is required" });
  if (input.award_type !== undefined && !["gold", "silver", "bronze", "merit"].includes(String(input.award_type))) errors.push({ field: "award_type", message: "Award type is not a valid value" });
  if (input.status !== undefined && !["delivered", "dispatched", "pending"].includes(String(input.status))) errors.push({ field: "status", message: "Status is not a valid status code" });
  return errors;
}
