// GENERATED by gen_rules (Robot 7) from canonical + rule_catalog — DO NOT EDIT.
// Named BRD validation rules for certificates (richer rules — DB/format/cross-record — layer in later):
//   - certificate_generation_gate: Certificates generated only for published results and active/non-revoked stude (src 10.023)
//   - verification_public_fields: Public certificate verification can expose only whitelisted fields; never expo (src 10.024)
export type FieldError = { field: string; message: string };

export function validateCertificates(input: Record<string, unknown>): FieldError[] {
  const errors: FieldError[] = [];
  if (!String(input.verification_code ?? "").trim()) errors.push({ field: "verification_code", message: "Verification code is required" });
  if (!String(input.student_id ?? "").trim()) errors.push({ field: "student_id", message: "Student id is required" });
  if (!String(input.result_id ?? "").trim()) errors.push({ field: "result_id", message: "Result id is required" });
  if (!String(input.school_id ?? "").trim()) errors.push({ field: "school_id", message: "School id is required" });
  if (input.status !== undefined && !["draft", "generated", "invalid", "issued", "rate_limited", "revoked", "valid"].includes(String(input.status))) errors.push({ field: "status", message: "Status is not a valid status code" });
  return errors;
}
