// GENERATED by gen_rules (Robot 7) from canonical + rule_catalog — DO NOT EDIT.
// Named BRD validation rules for courier_batches (richer rules — DB/format/cross-record — layer in later):
//   - courier_required_fields: Courier submission requires courier_company, awb_number, dispatch_date, packag (src 10.017)
//   - received_count_reconciliation: If sheets_received differs from sheets_expected, create exception status and r (src 10.018)
export type FieldError = { field: string; message: string };

export function validateCourierBatches(input: Record<string, unknown>): FieldError[] {
  const errors: FieldError[] = [];
  if (!String(input.batch_code ?? "").trim()) errors.push({ field: "batch_code", message: "Batch code is required" });
  if (!String(input.school_id ?? "").trim()) errors.push({ field: "school_id", message: "School id is required" });
  if (!String(input.participation_id ?? "").trim()) errors.push({ field: "participation_id", message: "Participation id is required" });
  if (!String(input.courier_company ?? "").trim()) errors.push({ field: "courier_company", message: "Courier company is required" });
  if (!String(input.awb_number ?? "").trim()) errors.push({ field: "awb_number", message: "Awb number is required" });
  if (!String(input.dispatch_date ?? "").trim()) errors.push({ field: "dispatch_date", message: "Dispatch date is required" });
  if (!String(input.package_count ?? "").trim()) errors.push({ field: "package_count", message: "Package count is required" });
  if (!String(input.sheets_expected ?? "").trim()) errors.push({ field: "sheets_expected", message: "Sheets expected is required" });
  if (!String(input.sheets_dispatched ?? "").trim()) errors.push({ field: "sheets_dispatched", message: "Sheets dispatched is required" });
  if (input.status !== undefined && !["closed", "dispatched", "exception", "pending", "received"].includes(String(input.status))) errors.push({ field: "status", message: "Status is not a valid status code" });
  return errors;
}
