// GENERATED by gen_rules (Robot 7) from canonical + rule_catalog — DO NOT EDIT.
export type FieldError = { field: string; message: string };

export function validateEmailCampaigns(input: Record<string, unknown>): FieldError[] {
  const errors: FieldError[] = [];
  if (!String(input.campaign_code ?? "").trim()) errors.push({ field: "campaign_code", message: "campaign_code is required" });
  if (!String(input.name ?? "").trim()) errors.push({ field: "name", message: "name is required" });
  if (!String(input.subject ?? "").trim()) errors.push({ field: "subject", message: "subject is required" });
  if (!String(input.html_content ?? "").trim()) errors.push({ field: "html_content", message: "html_content is required" });
  if (!String(input.channel ?? "").trim()) errors.push({ field: "channel", message: "channel is required" });
  if (input.channel !== undefined && !["outreach", "transactional"].includes(String(input.channel))) errors.push({ field: "channel", message: "channel is not a valid value" });
  if (input.status !== undefined && !["cancelled", "draft", "in_brevo", "paused", "scheduled", "sending", "sent"].includes(String(input.status))) errors.push({ field: "status", message: "status is not a valid status code" });
  return errors;
}
