// GENERATED by gen_rules (Robot 7) from canonical + rule_catalog — DO NOT EDIT.
// Named BRD validation rules for exam_materials (richer rules — DB/format/cross-record — layer in later):
//   - material_release_window: Material download allowed only after release_at and before expires_at if confi (src 10.016)
//   - payment_before_material: Payment paid/manually_confirmed and slot_confirmed required before material do (src 10.015)
export type FieldError = { field: string; message: string };

export function validateExamMaterials(input: Record<string, unknown>): FieldError[] {
  const errors: FieldError[] = [];
  if (!String(input.material_code ?? "").trim()) errors.push({ field: "material_code", message: "material_code is required" });
  if (!String(input.olympiad_id ?? "").trim()) errors.push({ field: "olympiad_id", message: "olympiad_id is required" });
  if (!String(input.file ?? "").trim()) errors.push({ field: "file", message: "file is required" });
  if (!String(input.release_at ?? "").trim()) errors.push({ field: "release_at", message: "release_at is required" });
  if (input.status !== undefined && !["approved", "draft", "expired", "release_scheduled", "released", "revoked"].includes(String(input.status))) errors.push({ field: "status", message: "status is not a declared state" });
  return errors;
}
