// GENERATED by gen_rules (Robot 7) from canonical + rule_catalog — DO NOT EDIT.
// Named BRD validation rules for participations (richer rules — DB/format/cross-record — layer in later):
//   - locked_participation_edit: After count_finalised, student changes require operations/admin override and a (src 10.010)
//   - student_count_positive: Final confirmed_student_count must be greater than zero. (src 10.009)
export type FieldError = { field: string; message: string };

export function validateParticipations(input: Record<string, unknown>): FieldError[] {
  const errors: FieldError[] = [];
  if (!String(input.participation_code ?? "").trim()) errors.push({ field: "participation_code", message: "participation_code is required" });
  if (!String(input.school_id ?? "").trim()) errors.push({ field: "school_id", message: "school_id is required" });
  if (!String(input.olympiad_id ?? "").trim()) errors.push({ field: "olympiad_id", message: "olympiad_id is required" });
  return errors;
}
