// GENERATED by gen_rules (Robot 7) from canonical + rule_catalog — DO NOT EDIT.
// Named BRD validation rules for participations (richer rules — DB/format/cross-record — layer in later):
//   - locked_participation_edit: After count_finalised, student changes require operations/admin override and a (src 10.010)
//   - student_count_positive: Final confirmed_student_count must be greater than zero. (src 10.009)
export type FieldError = { field: string; message: string };

export function validateParticipations(input: Record<string, unknown>): FieldError[] {
  const errors: FieldError[] = [];
  if (!String(input.school_id ?? "").trim()) errors.push({ field: "school_id", message: "School id is required" });
  if (!String(input.olympiad_id ?? "").trim()) errors.push({ field: "olympiad_id", message: "Olympiad id is required" });
  if (input.status !== undefined && !["approved", "cancelled", "certificates_released", "count_finalised", "draft", "exam_completed", "locked", "materials_released", "paid", "payment_pending", "renewed", "results_published", "slot_confirmed", "students_open", "submitted", "upload_received", "validation_failed", "validation_passed"].includes(String(input.status))) errors.push({ field: "status", message: "Status is not a valid status code" });
  return errors;
}
