// GENERATED by gen_rules (Robot 7) from canonical + rule_catalog — DO NOT EDIT.
// Named BRD validation rules for payments (richer rules — DB/format/cross-record — layer in later):
//   - net_amount_non_negative: Net amount payable must be >= 0 and gross = count * fee; commission = count *  (src 10.012)
//   - webhook_signature: Razorpay webhook must verify signature before any payment status update. (src 10.025)
export type FieldError = { field: string; message: string };

export function validatePayments(input: Record<string, unknown>): FieldError[] {
  const errors: FieldError[] = [];
  if (!String(input.payment_code ?? "").trim()) errors.push({ field: "payment_code", message: "Payment code is required" });
  if (!String(input.participation_id ?? "").trim()) errors.push({ field: "participation_id", message: "Participation id is required" });
  if (!String(input.school_id ?? "").trim()) errors.push({ field: "school_id", message: "School id is required" });
  if (!String(input.expected_amount ?? "").trim()) errors.push({ field: "expected_amount", message: "Expected amount is required" });
  if (input.status !== undefined && !["draft", "expired", "failed", "link_created", "manually_confirmed", "paid", "pending", "reconciled", "reversed"].includes(String(input.status))) errors.push({ field: "status", message: "Status is not a valid status code" });
  return errors;
}
