// GENERATED by gen_rules (Robot 7) from canonical + rule_catalog — DO NOT EDIT.
export type FieldError = { field: string; message: string };

export function validateReEvaluations(input: Record<string, unknown>): FieldError[] {
  const errors: FieldError[] = [];
  if (!String(input.result_id ?? "").trim()) errors.push({ field: "result_id", message: "Result id is required" });
  if (!String(input.student_id ?? "").trim()) errors.push({ field: "student_id", message: "Student id is required" });
  if (!String(input.school_id ?? "").trim()) errors.push({ field: "school_id", message: "School id is required" });
  if (!String(input.reason ?? "").trim()) errors.push({ field: "reason", message: "Reason is required" });
  if (input.status !== undefined && !["rejected", "requested", "resolved", "under_review"].includes(String(input.status))) errors.push({ field: "status", message: "Status is not a valid status code" });
  return errors;
}
