// GENERATED by gen_rules (Robot 7) from canonical + rule_catalog — DO NOT EDIT.
export type FieldError = { field: string; message: string };

export function validateSchoolSettings(input: Record<string, unknown>): FieldError[] {
  const errors: FieldError[] = [];
  if (!String(input.school_id ?? "").trim()) errors.push({ field: "school_id", message: "School id is required" });
  if (input.emblem_on_certificate !== undefined && !["no", "yes"].includes(String(input.emblem_on_certificate))) errors.push({ field: "emblem_on_certificate", message: "Emblem on certificate is not a valid value" });
  return errors;
}
