// GENERATED by gen_rules (Robot 7) from canonical + rule_catalog — DO NOT EDIT.
// Named BRD validation rules for school_users (richer rules — DB/format/cross-record — layer in later):
//   - coordinator_email_valid: Coordinator email must be syntactically valid and unique for active school use (src 10.003)
export type FieldError = { field: string; message: string };

export function validateSchoolUsers(input: Record<string, unknown>): FieldError[] {
  const errors: FieldError[] = [];
  if (!String(input.directus_user_id ?? "").trim()) errors.push({ field: "directus_user_id", message: "Directus user id is required" });
  if (!String(input.school_id ?? "").trim()) errors.push({ field: "school_id", message: "School id is required" });
  return errors;
}
