// GENERATED by gen_rules (Robot 7) from canonical + rule_catalog — DO NOT EDIT.
// Named BRD validation rules for students (richer rules — DB/format/cross-record — layer in later):
//   - student_consent_required: Students without consent_obtained=true cannot be finalised. (src 10.008)
//   - student_duplicate_rule: Duplicate check within school+participation using candidate_id if existing, el (src 10.007)
//   - student_file_type: Student upload accepts CSV/XLSX only. (src 10.004)
//   - student_required_columns: Student upload must include student_name, grade, olympiad/subject or participa (src 10.006)
export type FieldError = { field: string; message: string };

export function validateStudents(input: Record<string, unknown>): FieldError[] {
  const errors: FieldError[] = [];
  if (!String(input.school_id ?? "").trim()) errors.push({ field: "school_id", message: "school_id is required" });
  if (!String(input.participation_id ?? "").trim()) errors.push({ field: "participation_id", message: "participation_id is required" });
  if (!String(input.student_name ?? "").trim()) errors.push({ field: "student_name", message: "student_name is required" });
  if (!String(input.grade ?? "").trim()) errors.push({ field: "grade", message: "grade is required" });
  if (!String(input.consent_obtained ?? "").trim()) errors.push({ field: "consent_obtained", message: "consent_obtained is required" });
  return errors;
}
