// GENERATED by gen_rules (Robot 7) from canonical + rule_catalog — DO NOT EDIT.
export type FieldError = { field: string; message: string };

export function validateStudyResources(input: Record<string, unknown>): FieldError[] {
  const errors: FieldError[] = [];
  if (!String(input.olympiad_id ?? "").trim()) errors.push({ field: "olympiad_id", message: "Olympiad id is required" });
  if (input.kind !== undefined && !["syllabus", "sample_paper", "guide"].includes(String(input.kind))) errors.push({ field: "kind", message: "Kind is not a valid value" });
  if (!String(input.title ?? "").trim()) errors.push({ field: "title", message: "Title is required" });
  if (!String(input.url ?? "").trim()) errors.push({ field: "url", message: "Url is required" });
  if (input.status !== undefined && !["archived", "draft", "published"].includes(String(input.status))) errors.push({ field: "status", message: "Status is not a valid status code" });
  return errors;
}
