// GENERATED by gen_services (Robot 5) from canonical + rule_catalog — DO NOT EDIT.
import { db } from "@/runtime/db";              // frozen data kernel
import { validateAdmitCards } from "@/rules/admit_cards.rules"; // from gen_rules (Robot 7)

export type AdmitCardsInput = {
  admit_card_code?: string;
  student_id: string;
  participation_id: string;
  school_id: string;
  exam_slot_id?: string;
  candidate_id?: string;
  venue?: string;
  status?: string;
};

export async function createAdmitCards(input: AdmitCardsInput) {
  const data: Record<string, unknown> = { ...input };
  if (!data.admit_card_code) data.admit_card_code = "ADMI-" + crypto.randomUUID().slice(0, 8).toUpperCase();  // BRD §18: auto-generated, unique + stable
  const errors = validateAdmitCards(data);
  if (errors.length) return { ok: false as const, errors };
  return { ok: true as const, data: await db.insert("admit_cards", data) };
}

export async function getAdmitCards(id: string) { return db.get("admit_cards", id); }
export async function listAdmitCards() { return db.list("admit_cards"); }
export async function updateAdmitCards(id: string, patch: Partial<AdmitCardsInput>) { return db.update("admit_cards", id, patch); }
export async function deleteAdmitCards(id: string) { return db.delete("admit_cards", id); }

// lifecycle state machine — only these transitions exist (from the BRD via the catalog)
const TRANSITIONS = { issue: { from: "generated", to: "issued" } } as const;
export async function transitionAdmitCards(id: string, action: keyof typeof TRANSITIONS) {
  const row = await db.get("admit_cards", id) as { status?: string };
  const t = TRANSITIONS[action];
  if (!t) throw new Error(`unknown action ${action} on admit_cards`);
  if (t.from !== "any" && row.status !== t.from)
    throw new Error(`illegal transition ${action}: admit_cards is "${row.status}", needs "${t.from}"`);
  return db.update("admit_cards", id, { status: t.to });
}
