// GENERATED by gen_services (Robot 5) from canonical + rule_catalog — DO NOT EDIT.
import { db } from "@/runtime/db";              // frozen data kernel
import { validateAnswerKeys } from "@/rules/answer_keys.rules"; // from gen_rules (Robot 7)

export type AnswerKeysInput = {
  answer_key_code?: string;
  olympiad_id: string;
  grade: string;
  total_questions: number;
  key: Record<string, unknown>;
  status?: string;
};

export async function createAnswerKeys(input: AnswerKeysInput) {
  const data: Record<string, unknown> = { ...input };
  if (!data.answer_key_code) data.answer_key_code = "ANSW-" + crypto.randomUUID().slice(0, 8).toUpperCase();  // BRD §18: auto-generated, unique + stable
  const errors = validateAnswerKeys(data);
  if (errors.length) return { ok: false as const, errors };
  return { ok: true as const, data: await db.insert("answer_keys", data) };
}

export async function getAnswerKeys(id: string) { return db.get("answer_keys", id); }
export async function listAnswerKeys() { return db.list("answer_keys"); }
export async function updateAnswerKeys(id: string, patch: Partial<AnswerKeysInput>) { return db.update("answer_keys", id, patch); }
export async function deleteAnswerKeys(id: string) { return db.delete("answer_keys", id); }

// lifecycle state machine — only these transitions exist (from the BRD via the catalog)
const TRANSITIONS = { archive: { from: "any", to: "archived" }, publish: { from: "draft", to: "published" }, revise: { from: "published", to: "draft" } } as const;
export async function transitionAnswerKeys(id: string, action: keyof typeof TRANSITIONS) {
  const row = await db.get("answer_keys", id) as { status?: string };
  const t = TRANSITIONS[action];
  if (!t) throw new Error(`unknown action ${action} on answer_keys`);
  if (t.from !== "any" && row.status !== t.from)
    throw new Error(`illegal transition ${action}: answer_keys is "${row.status}", needs "${t.from}"`);
  const updated = await db.update("answer_keys", id, { status: t.to });
  try { await db.insert("audit_events", { trace_id: "AUD-" + crypto.randomUUID().slice(0, 12), action, entity_name: "answer_keys", entity_id: id, previous_status: (row as { status?: string }).status ?? null, new_status: t.to, created_at: new Date().toISOString() }); } catch (e) { /* audit best-effort */ }
  return updated;
}
