// GENERATED by gen_services (Robot 5) from canonical + rule_catalog — DO NOT EDIT.
import { db } from "../runtime/db";              // frozen data kernel
import { validateAuditEvents } from "../rules/audit_events.rules"; // from gen_rules (Robot 7)

export type AuditEventsInput = {
  trace_id: string;
  actor_user_id?: string;
  actor_role: string;
  action: string;
  entity_name: string;
  entity_id: string;
  previous_status?: string;
  new_status?: string;
  ip_address?: string;
  external_reference?: string;
  reason?: string;
};

export async function createAuditEvents(input: AuditEventsInput) {
  const errors = validateAuditEvents(input);
  if (errors.length) return { ok: false as const, errors };
  return { ok: true as const, data: await db.insert("audit_events", input) };
}

export async function getAuditEvents(id: string) { return db.get("audit_events", id); }
export async function listAuditEvents() { return db.list("audit_events"); }
export async function updateAuditEvents(id: string, patch: Partial<AuditEventsInput>) { return db.update("audit_events", id, patch); }
