// GENERATED by gen_services (Robot 5) from canonical + rule_catalog — DO NOT EDIT.
import { db } from "@/runtime/db";              // frozen data kernel
import { validateAwards } from "@/rules/awards.rules"; // from gen_rules (Robot 7)

export type AwardsInput = {
  award_code?: string;
  result_id: string;
  student_id: string;
  school_id: string;
  award_type?: string;
  tracking_ref?: string;
  status?: string;
};

export async function createAwards(input: AwardsInput) {
  const data: Record<string, unknown> = { ...input };
  if (!data.award_code) data.award_code = "AWAR-" + crypto.randomUUID().slice(0, 8).toUpperCase();  // BRD §18: auto-generated, unique + stable
  const errors = validateAwards(data);
  if (errors.length) return { ok: false as const, errors };
  return { ok: true as const, data: await db.insert("awards", data) };
}

export async function getAwards(id: string) { return db.get("awards", id); }
export async function listAwards() { return db.list("awards"); }
export async function updateAwards(id: string, patch: Partial<AwardsInput>) { return db.update("awards", id, patch); }
export async function deleteAwards(id: string) { return db.delete("awards", id); }

// lifecycle state machine — only these transitions exist (from the BRD via the catalog)
const TRANSITIONS = { deliver: { from: "dispatched", to: "delivered" }, dispatch: { from: "pending", to: "dispatched" } } as const;
export async function transitionAwards(id: string, action: keyof typeof TRANSITIONS) {
  const row = await db.get("awards", id) as { status?: string };
  const t = TRANSITIONS[action];
  if (!t) throw new Error(`unknown action ${action} on awards`);
  if (t.from !== "any" && row.status !== t.from)
    throw new Error(`illegal transition ${action}: awards is "${row.status}", needs "${t.from}"`);
  const updated = await db.update("awards", id, { status: t.to });
  try { await db.insert("audit_events", { trace_id: "AUD-" + crypto.randomUUID().slice(0, 12), action, entity_name: "awards", entity_id: id, previous_status: (row as { status?: string }).status ?? null, new_status: t.to, created_at: new Date().toISOString() }); } catch (e) { /* audit best-effort */ }
  return updated;
}
