// GENERATED by gen_services (Robot 5) from canonical + rule_catalog — DO NOT EDIT.
import { db } from "../runtime/db";              // frozen data kernel
import { validateCertificates } from "../rules/certificates.rules"; // from gen_rules (Robot 7)

export type CertificatesInput = {
  certificate_number: string;
  verification_code: string;
  student_id: string;
  result_id: string;
  school_id: string;
  certificate_type?: string;
  pdf_file?: string;
  issued_at?: string;
  revoked_at?: string;
  revocation_reason: string;
  status?: string;
};

export async function createCertificates(input: CertificatesInput) {
  const errors = validateCertificates(input);
  if (errors.length) return { ok: false as const, errors };
  return { ok: true as const, data: await db.insert("certificates", input) };
}

export async function getCertificates(id: string) { return db.get("certificates", id); }
export async function listCertificates() { return db.list("certificates"); }
export async function updateCertificates(id: string, patch: Partial<CertificatesInput>) { return db.update("certificates", id, patch); }

// lifecycle state machine — only these transitions exist (from the BRD via the catalog)
const TRANSITIONS = { rate_limit: { from: "request", to: "rate_limited" }, verify_code: { from: "request", to: "valid" }, generate: { from: "results_published", to: "generated" }, issue: { from: "generated", to: "issued" }, revoke: { from: "issued", to: "revoked" } } as const;
export async function transitionCertificates(id: string, action: keyof typeof TRANSITIONS) {
  const row = await db.get("certificates", id) as { status?: string };
  const t = TRANSITIONS[action];
  if (!t) throw new Error(`unknown action ${action} on certificates`);
  if (t.from !== "any" && row.status !== t.from)
    throw new Error(`illegal transition ${action}: certificates is "${row.status}", needs "${t.from}"`);
  return db.update("certificates", id, { status: t.to });
}
