// GENERATED by gen_services (Robot 5) from canonical + rule_catalog — DO NOT EDIT.
import { db } from "@/runtime/db";              // frozen data kernel
import { validateCertificates } from "@/rules/certificates.rules"; // from gen_rules (Robot 7)
import { advanceParticipation } from "@/services/participations.service"; // effect + cascade chains

export type CertificatesInput = {
  certificate_number: string;
  verification_code: string;
  student_id: string;
  result_id: string;
  school_id: string;
  certificate_type?: string;
  pdf_file?: string;
  issued_at?: string;
  revoked_at?: string;
  revocation_reason: string;
  status?: string;
};

export async function createCertificates(input: CertificatesInput) {
  const errors = validateCertificates(input);
  if (errors.length) return { ok: false as const, errors };
  return { ok: true as const, data: await db.insert("certificates", input) };
}

export async function getCertificates(id: string) { return db.get("certificates", id); }
export async function listCertificates() { return db.list("certificates"); }
export async function updateCertificates(id: string, patch: Partial<CertificatesInput>) { return db.update("certificates", id, patch); }
export async function deleteCertificates(id: string) { return db.delete("certificates", id); }

// lifecycle state machine — only these transitions exist (from the BRD via the catalog)
const TRANSITIONS = { generate: { from: "results_published", to: "generated" }, issue: { from: "generated", to: "issued" }, revoke: { from: "issued", to: "revoked" } } as const;
export async function transitionCertificates(id: string, action: keyof typeof TRANSITIONS) {
  const row = await db.get("certificates", id) as { status?: string, result_id?: string };
  const t = TRANSITIONS[action];
  if (!t) throw new Error(`unknown action ${action} on certificates`);
  if (t.from !== "any" && row.status !== t.from)
    throw new Error(`illegal transition ${action}: certificates is "${row.status}", needs "${t.from}"`);
  const updated = await db.update("certificates", id, { status: t.to });
  try { await db.insert("audit_events", { trace_id: "AUD-" + crypto.randomUUID().slice(0, 12), action, entity_name: "certificates", entity_id: id, previous_status: (row as { status?: string }).status ?? null, new_status: t.to, created_at: new Date().toISOString() }); } catch (e) { /* audit best-effort */ }
  // EFFECT CHAINS (spine) + registration side-effect (create participation)
  if (action === "issue" && row.result_id) { const _r = await db.get("results", row.result_id) as { participation_id?: string }; if (_r?.participation_id) await advanceParticipation(_r.participation_id, "certificates_released"); }
  return updated;
}
