// GENERATED by gen_services (Robot 5) from canonical + rule_catalog — DO NOT EDIT.
import { db } from "@/runtime/db";              // frozen data kernel
import { validateCourierBatches } from "@/rules/courier_batches.rules"; // from gen_rules (Robot 7)

export type CourierBatchesInput = {
  batch_code: string;
  school_id: string;
  participation_id: string;
  courier_company: string;
  awb_number: string;
  dispatch_date: string;
  package_count: number;
  sheets_expected: number;
  sheets_dispatched: number;
  sheets_received?: number;
  receipt_file?: string;
  seal_condition?: string;
  status?: string;
};

export async function createCourierBatches(input: CourierBatchesInput) {
  const errors = validateCourierBatches(input);
  if (errors.length) return { ok: false as const, errors };
  return { ok: true as const, data: await db.insert("courier_batches", input) };
}

export async function getCourierBatches(id: string) { return db.get("courier_batches", id); }
export async function listCourierBatches() { return db.list("courier_batches"); }
export async function updateCourierBatches(id: string, patch: Partial<CourierBatchesInput>) { return db.update("courier_batches", id, patch); }
