// GENERATED by gen_services (Robot 5) from canonical + rule_catalog — DO NOT EDIT.
import { db } from "@/runtime/db";              // frozen data kernel
import { validateEmailCampaigns } from "@/rules/email_campaigns.rules"; // from gen_rules (Robot 7)
import { sendCampaign } from "@/runtime/email/campaign_sender";  // service hook (signed kernel)
import { createInBrevo } from "@/runtime/email/campaign_brevo";  // service hook (signed kernel)

export type EmailCampaignsInput = {
  campaign_code: string;
  name: string;
  subject: string;
  html_content: string;
  channel: string;
  provider?: string;
  segment?: string;
  status?: string;
  scheduled_at?: string;
  sent_count?: number;
  delivered_count?: number;
  opened_count?: number;
  bounced_count?: number;
  target_ids?: string;
  provider_campaign_id?: string;
  provider_url?: string;
};

export async function createEmailCampaigns(input: EmailCampaignsInput) {
  const errors = validateEmailCampaigns(input);
  if (errors.length) return { ok: false as const, errors };
  return { ok: true as const, data: await db.insert("email_campaigns", input) };
}

export async function getEmailCampaigns(id: string) { return db.get("email_campaigns", id); }
export async function listEmailCampaigns() { return db.list("email_campaigns"); }
export async function updateEmailCampaigns(id: string, patch: Partial<EmailCampaignsInput>) { return db.update("email_campaigns", id, patch); }
export async function deleteEmailCampaigns(id: string) { return db.delete("email_campaigns", id); }

// lifecycle state machine — only these transitions exist (from the BRD via the catalog)
const TRANSITIONS = { cancel: { from: "any", to: "cancelled" }, create_in_brevo: { from: "draft", to: "in_brevo" }, finish_send: { from: "sending", to: "sent" }, pause: { from: "sending", to: "paused" }, schedule: { from: "draft", to: "scheduled" }, start_send: { from: "draft", to: "sending" } } as const;
export async function transitionEmailCampaigns(id: string, action: keyof typeof TRANSITIONS) {
  const row = await db.get("email_campaigns", id) as { status?: string };
  const t = TRANSITIONS[action];
  if (!t) throw new Error(`unknown action ${action} on email_campaigns`);
  if (t.from !== "any" && row.status !== t.from)
    throw new Error(`illegal transition ${action}: email_campaigns is "${row.status}", needs "${t.from}"`);
  const updated = await db.update("email_campaigns", id, { status: t.to });
  // EFFECT CHAINS (spine) + registration side-effect (create participation)
  if (action === "start_send") await sendCampaign(id);
  if (action === "create_in_brevo") await createInBrevo(id);
  return updated;
}
