// GENERATED by gen_services (Robot 5) from canonical + rule_catalog — DO NOT EDIT.
import { db } from "@/runtime/db";              // frozen data kernel
import { validateEmailSends } from "@/rules/email_sends.rules"; // from gen_rules (Robot 7)

export type EmailSendsInput = {
  send_ref: string;
  campaign_id: string;
  school_id: string;
  email: string;
  status?: string;
  provider_message_id?: string;
  sent_at?: string;
  delivered_at?: string;
  opened_at?: string;
};

export async function createEmailSends(input: EmailSendsInput) {
  const errors = validateEmailSends(input);
  if (errors.length) return { ok: false as const, errors };
  return { ok: true as const, data: await db.insert("email_sends", input) };
}

export async function getEmailSends(id: string) { return db.get("email_sends", id); }
export async function listEmailSends() { return db.list("email_sends"); }
export async function updateEmailSends(id: string, patch: Partial<EmailSendsInput>) { return db.update("email_sends", id, patch); }

// lifecycle state machine — only these transitions exist (from the BRD via the catalog)
const TRANSITIONS = { mark_bounced: { from: "any", to: "bounced" }, mark_clicked: { from: "opened", to: "clicked" }, mark_delivered: { from: "sent", to: "delivered" }, mark_failed: { from: "any", to: "failed" }, mark_opened: { from: "delivered", to: "opened" }, mark_sent: { from: "queued", to: "sent" }, mark_unsubscribed: { from: "any", to: "unsubscribed" } } as const;
export async function transitionEmailSends(id: string, action: keyof typeof TRANSITIONS) {
  const row = await db.get("email_sends", id) as { status?: string };
  const t = TRANSITIONS[action];
  if (!t) throw new Error(`unknown action ${action} on email_sends`);
  if (t.from !== "any" && row.status !== t.from)
    throw new Error(`illegal transition ${action}: email_sends is "${row.status}", needs "${t.from}"`);
  return db.update("email_sends", id, { status: t.to });
}
