// GENERATED by gen_services (Robot 5) from canonical + rule_catalog — DO NOT EDIT.
import { db } from "@/runtime/db";              // frozen data kernel
import { validateExamMaterials } from "@/rules/exam_materials.rules"; // from gen_rules (Robot 7)
import { advanceParticipation } from "@/services/participations.service"; // effect chains

export type ExamMaterialsInput = {
  material_code: string;
  participation_id?: string;
  olympiad_id: string;
  exam_slot_id?: string;
  material_type?: string;
  file: string;
  release_at: string;
  expires_at?: string;
  download_count?: number;
  status?: string;
};

export async function createExamMaterials(input: ExamMaterialsInput) {
  const errors = validateExamMaterials(input);
  if (errors.length) return { ok: false as const, errors };
  return { ok: true as const, data: await db.insert("exam_materials", input) };
}

export async function getExamMaterials(id: string) { return db.get("exam_materials", id); }
export async function listExamMaterials() { return db.list("exam_materials"); }
export async function updateExamMaterials(id: string, patch: Partial<ExamMaterialsInput>) { return db.update("exam_materials", id, patch); }

// lifecycle state machine — only these transitions exist (from the BRD via the catalog)
const TRANSITIONS = { approve_material: { from: "draft", to: "approved" }, release_when_due: { from: "release_scheduled", to: "released" }, revoke: { from: "any", to: "revoked" }, schedule_release: { from: "approved", to: "release_scheduled" } } as const;
export async function transitionExamMaterials(id: string, action: keyof typeof TRANSITIONS) {
  const row = await db.get("exam_materials", id) as { status?: string, participation_id?: string };
  const t = TRANSITIONS[action];
  if (!t) throw new Error(`unknown action ${action} on exam_materials`);
  if (t.from !== "any" && row.status !== t.from)
    throw new Error(`illegal transition ${action}: exam_materials is "${row.status}", needs "${t.from}"`);
  const updated = await db.update("exam_materials", id, { status: t.to });
  // EFFECT CHAINS — advance the participation spine (forward-only, from the catalog)
  if (action === "release_when_due" && row.participation_id) await advanceParticipation(row.participation_id, "materials_released");
  return updated;
}
