// GENERATED by gen_services (Robot 5) from canonical + rule_catalog — DO NOT EDIT.
import { db } from "@/runtime/db";              // frozen data kernel
import { validateExamSlots } from "@/rules/exam_slots.rules"; // from gen_rules (Robot 7)

export type ExamSlotsInput = {
  slot_code: string;
  exam_date: string;
  start_time: string;
  end_time: string;
  timezone?: string;
  mode?: string;
  capacity_schools: number;
  capacity_students: number;
  booked_schools?: number;
  booked_students?: number;
  eligible_grades?: Record<string, unknown>;
  status?: string;
};

export async function createExamSlots(input: ExamSlotsInput) {
  const errors = validateExamSlots(input);
  if (errors.length) return { ok: false as const, errors };
  return { ok: true as const, data: await db.insert("exam_slots", input) };
}

export async function getExamSlots(id: string) { return db.get("exam_slots", id); }
export async function listExamSlots() { return db.list("exam_slots"); }
export async function updateExamSlots(id: string, patch: Partial<ExamSlotsInput>) { return db.update("exam_slots", id, patch); }

// lifecycle state machine — only these transitions exist (from the BRD via the catalog)
const TRANSITIONS = { capacity_full: { from: "open", to: "full" }, change_slot: { from: "slot_confirmed", to: "changed" }, confirm_capacity: { from: "selected", to: "slot_confirmed" }, select_slot: { from: "open", to: "selected" } } as const;
export async function transitionExamSlots(id: string, action: keyof typeof TRANSITIONS) {
  const row = await db.get("exam_slots", id) as { status?: string };
  const t = TRANSITIONS[action];
  if (!t) throw new Error(`unknown action ${action} on exam_slots`);
  if (t.from !== "any" && row.status !== t.from)
    throw new Error(`illegal transition ${action}: exam_slots is "${row.status}", needs "${t.from}"`);
  return db.update("exam_slots", id, { status: t.to });
}
