// GENERATED by gen_services (Robot 5) from canonical + rule_catalog — DO NOT EDIT.
import { db } from "../runtime/db";              // frozen data kernel
import { validateOlympiads } from "../rules/olympiads.rules"; // from gen_rules (Robot 7)

export type OlympiadsInput = {
  olympiad_code: string;
  name: string;
  academic_year: string;
  subject: string;
  eligible_grades: Record<string, unknown>;
  registration_open_at: string;
  registration_close_at: string;
  exam_window_start: string;
  exam_window_end: string;
  fee_per_student: number;
  school_commission_per_student: number;
  max_marks: number;
  status?: string;
};

export async function createOlympiads(input: OlympiadsInput) {
  const errors = validateOlympiads(input);
  if (errors.length) return { ok: false as const, errors };
  return { ok: true as const, data: await db.insert("olympiads", input) };
}

export async function getOlympiads(id: string) { return db.get("olympiads", id); }
export async function listOlympiads() { return db.list("olympiads"); }
export async function updateOlympiads(id: string, patch: Partial<OlympiadsInput>) { return db.update("olympiads", id, patch); }
