// GENERATED by gen_services (Robot 5) from canonical + rule_catalog — DO NOT EDIT.
import { db } from "../runtime/db";              // frozen data kernel
import { validateOmrImports } from "../rules/omr_imports.rules"; // from gen_rules (Robot 7)

export type OmrImportsInput = {
  import_code: string;
  participation_id: string;
  courier_batch_id: string;
  uploaded_file: string;
  row_count?: number;
  valid_count?: number;
  error_count?: number;
  review_status?: string;
  uploaded_by: string;
  approved_by?: string;
};

export async function createOmrImports(input: OmrImportsInput) {
  const errors = validateOmrImports(input);
  if (errors.length) return { ok: false as const, errors };
  return { ok: true as const, data: await db.insert("omr_imports", input) };
}

export async function getOmrImports(id: string) { return db.get("omr_imports", id); }
export async function listOmrImports() { return db.list("omr_imports"); }
export async function updateOmrImports(id: string, patch: Partial<OmrImportsInput>) { return db.update("omr_imports", id, patch); }
