// GENERATED by gen_services (Robot 5) from canonical + rule_catalog — DO NOT EDIT.
import { db } from "@/runtime/db";              // frozen data kernel
import { validateOmrImports } from "@/rules/omr_imports.rules"; // from gen_rules (Robot 7)
import { advanceParticipation } from "@/services/participations.service"; // effect chains

export type OmrImportsInput = {
  import_code: string;
  participation_id: string;
  courier_batch_id: string;
  uploaded_file: string;
  row_count?: number;
  valid_count?: number;
  error_count?: number;
  review_status?: string;
  uploaded_by: string;
  approved_by?: string;
};

export async function createOmrImports(input: OmrImportsInput) {
  const errors = validateOmrImports(input);
  if (errors.length) return { ok: false as const, errors };
  return { ok: true as const, data: await db.insert("omr_imports", input) };
}

export async function getOmrImports(id: string) { return db.get("omr_imports", id); }
export async function listOmrImports() { return db.list("omr_imports"); }
export async function updateOmrImports(id: string, patch: Partial<OmrImportsInput>) { return db.update("omr_imports", id, patch); }

// lifecycle state machine — only these transitions exist (from the BRD via the catalog)
const TRANSITIONS = { approve_import: { from: "reviewed", to: "approved" }, reject_import: { from: "any", to: "rejected" }, upload_omr: { from: "awaiting_import", to: "imported" }, validate_import: { from: "imported", to: "reviewed" } } as const;
export async function transitionOmrImports(id: string, action: keyof typeof TRANSITIONS) {
  const row = await db.get("omr_imports", id) as { status?: string, participation_id?: string };
  const t = TRANSITIONS[action];
  if (!t) throw new Error(`unknown action ${action} on omr_imports`);
  if (t.from !== "any" && row.status !== t.from)
    throw new Error(`illegal transition ${action}: omr_imports is "${row.status}", needs "${t.from}"`);
  const updated = await db.update("omr_imports", id, { status: t.to });
  // EFFECT CHAINS — advance the participation spine (forward-only, from the catalog)
  if (action === "approve_import" && row.participation_id) await advanceParticipation(row.participation_id, "exam_completed");
  return updated;
}
