// GENERATED by gen_services (Robot 5) from canonical + rule_catalog — DO NOT EDIT.
import { db } from "@/runtime/db";              // frozen data kernel
import { validateOmrImports } from "@/rules/omr_imports.rules"; // from gen_rules (Robot 7)
import { advanceParticipation } from "@/services/participations.service"; // effect + cascade chains

export type OmrImportsInput = {
  import_code: string;
  participation_id: string;
  courier_batch_id: string;
  uploaded_file: string;
  row_count?: number;
  valid_count?: number;
  error_count?: number;
  review_status?: string;
  uploaded_by: string;
  approved_by?: string;
  status?: string;
};

export async function createOmrImports(input: OmrImportsInput) {
  const errors = validateOmrImports(input);
  if (errors.length) return { ok: false as const, errors };
  return { ok: true as const, data: await db.insert("omr_imports", input) };
}

export async function getOmrImports(id: string) { return db.get("omr_imports", id); }
export async function listOmrImports() { return db.list("omr_imports"); }
export async function updateOmrImports(id: string, patch: Partial<OmrImportsInput>) { return db.update("omr_imports", id, patch); }
export async function deleteOmrImports(id: string) { return db.delete("omr_imports", id); }

// lifecycle state machine — only these transitions exist (from the BRD via the catalog)
const TRANSITIONS = { approve_import: { from: "reviewed", to: "approved" }, reject_import: { from: "any", to: "rejected" }, upload_omr: { from: "awaiting_import", to: "imported" }, validate_import: { from: "imported", to: "reviewed" } } as const;
export async function transitionOmrImports(id: string, action: keyof typeof TRANSITIONS) {
  const row = await db.get("omr_imports", id) as { status?: string, participation_id?: string };
  const t = TRANSITIONS[action];
  if (!t) throw new Error(`unknown action ${action} on omr_imports`);
  if (t.from !== "any" && row.status !== t.from)
    throw new Error(`illegal transition ${action}: omr_imports is "${row.status}", needs "${t.from}"`);
  const updated = await db.update("omr_imports", id, { status: t.to });
  try { await db.insert("audit_events", { trace_id: "AUD-" + crypto.randomUUID().slice(0, 12), action, entity_name: "omr_imports", entity_id: id, previous_status: (row as { status?: string }).status ?? null, new_status: t.to, created_at: new Date().toISOString() }); } catch (e) { /* audit best-effort */ }
  // EFFECT CHAINS (spine) + registration side-effect (create participation)
  if (action === "approve_import" && row.participation_id) await advanceParticipation(row.participation_id, "exam_completed");
  return updated;
}

// BRD §10 omr_candidate_match — every scanned candidate_id must be in the participation roster, no duplicates
export async function matchOmrCandidates(participationId: string, scanned: string[]) {
  const roster = (await db.list("students")) as Array<{ candidate_id?: string; participation_id?: string }>;
  const valid = new Set(roster.filter((s) => s.participation_id === participationId).map((s) => s.candidate_id));
  const seen = new Set<string>(); const matched: string[] = [];
  const errors: Array<{ candidate_id: string; reason: string }> = [];
  for (const cid of scanned) {
    if (!valid.has(cid)) errors.push({ candidate_id: cid, reason: "not in participation roster" });
    else if (seen.has(cid)) errors.push({ candidate_id: cid, reason: "duplicate scan" });
    else matched.push(cid);
    seen.add(cid);
  }
  return { matched, errors };
}
