// GENERATED by gen_services (Robot 5) from canonical + rule_catalog — DO NOT EDIT.
import { db } from "@/runtime/db";              // frozen data kernel
import { validateParticipations } from "@/rules/participations.rules"; // from gen_rules (Robot 7)

export type ParticipationsInput = {
  participation_code: string;
  school_id: string;
  olympiad_id: string;
  estimated_student_count?: number;
  confirmed_student_count?: number;
  gross_amount?: number;
  commission_amount?: number;
  net_amount_payable?: number;
  payment_status?: string;
  exam_slot_id?: string;
  consent_declaration_status?: string;
  status?: string;
  locked_at?: string;
};

export async function createParticipations(input: ParticipationsInput) {
  const errors = validateParticipations(input);
  if (errors.length) return { ok: false as const, errors };
  return { ok: true as const, data: await db.insert("participations", input) };
}

export async function getParticipations(id: string) { return db.get("participations", id); }
export async function listParticipations() { return db.list("participations"); }
export async function updateParticipations(id: string, patch: Partial<ParticipationsInput>) { return db.update("participations", id, patch); }

// lifecycle state machine — only these transitions exist (from the BRD via the catalog)
const TRANSITIONS = { finalise: { from: "validation_passed", to: "count_finalised" }, upload_students: { from: "students_open", to: "upload_received" }, validate: { from: "upload_received", to: "validation_passed" } } as const;
export async function transitionParticipations(id: string, action: keyof typeof TRANSITIONS) {
  const row = await db.get("participations", id) as { status?: string };
  const t = TRANSITIONS[action];
  if (!t) throw new Error(`unknown action ${action} on participations`);
  if (t.from !== "any" && row.status !== t.from)
    throw new Error(`illegal transition ${action}: participations is "${row.status}", needs "${t.from}"`);
  return db.update("participations", id, { status: t.to });
}
