// GENERATED by gen_services (Robot 5) from canonical + rule_catalog — DO NOT EDIT.
import { db } from "@/runtime/db";              // frozen data kernel
import { validatePayments } from "@/rules/payments.rules"; // from gen_rules (Robot 7)
import { advanceParticipation } from "@/services/participations.service"; // effect + cascade chains

export type PaymentsInput = {
  payment_code: string;
  participation_id: string;
  school_id: string;
  expected_amount: number;
  received_amount?: number;
  provider?: string;
  provider_link_id?: string;
  provider_payment_id?: string;
  payment_reference?: string;
  status?: string;
  manual_evidence_file: string;
  reversal_reason: string;
  reconciled_at?: string;
};

export async function createPayments(input: PaymentsInput) {
  const errors = validatePayments(input);
  if (errors.length) return { ok: false as const, errors };
  return { ok: true as const, data: await db.insert("payments", input) };
}

export async function getPayments(id: string) { return db.get("payments", id); }
export async function listPayments() { return db.list("payments"); }
export async function updatePayments(id: string, patch: Partial<PaymentsInput>) { return db.update("payments", id, patch); }
export async function deletePayments(id: string) { return db.delete("payments", id); }

// lifecycle state machine — only these transitions exist (from the BRD via the catalog)
const TRANSITIONS = { create_link: { from: "draft", to: "link_created" }, manual_confirm: { from: "any", to: "manually_confirmed" }, provider_pending: { from: "link_created", to: "pending" }, reconcile: { from: "paid", to: "reconciled" }, reverse: { from: "paid", to: "reversed" }, webhook_paid: { from: "pending", to: "paid" } } as const;
export async function transitionPayments(id: string, action: keyof typeof TRANSITIONS) {
  const row = await db.get("payments", id) as { status?: string, participation_id?: string };
  const t = TRANSITIONS[action];
  if (!t) throw new Error(`unknown action ${action} on payments`);
  if (t.from !== "any" && row.status !== t.from)
    throw new Error(`illegal transition ${action}: payments is "${row.status}", needs "${t.from}"`);
  const updated = await db.update("payments", id, { status: t.to });
  // EFFECT CHAINS (spine) + registration side-effect (create participation)
  if (action === "create_link" && row.participation_id) await advanceParticipation(row.participation_id, "payment_pending");
  if (action === "webhook_paid" && row.participation_id) await advanceParticipation(row.participation_id, "paid");
  if (action === "manual_confirm" && row.participation_id) await advanceParticipation(row.participation_id, "paid");
  return updated;
}
