// GENERATED by gen_services (Robot 5) from canonical + rule_catalog — DO NOT EDIT.
import { db } from "@/runtime/db";              // frozen data kernel
import { validateReEvaluations } from "@/rules/re_evaluations.rules"; // from gen_rules (Robot 7)

export type ReEvaluationsInput = {
  re_eval_code?: string;
  result_id: string;
  student_id: string;
  school_id: string;
  reason: string;
  fee?: number;
  revised_score?: number;
  resolution_note?: string;
  status?: string;
};

export async function createReEvaluations(input: ReEvaluationsInput) {
  const data: Record<string, unknown> = { ...input };
  if (!data.re_eval_code) data.re_eval_code = "RE_E-" + crypto.randomUUID().slice(0, 8).toUpperCase();  // BRD §18: auto-generated, unique + stable
  const errors = validateReEvaluations(data);
  if (errors.length) return { ok: false as const, errors };
  return { ok: true as const, data: await db.insert("re_evaluations", data) };
}

export async function getReEvaluations(id: string) { return db.get("re_evaluations", id); }
export async function listReEvaluations() { return db.list("re_evaluations"); }
export async function updateReEvaluations(id: string, patch: Partial<ReEvaluationsInput>) { return db.update("re_evaluations", id, patch); }
export async function deleteReEvaluations(id: string) { return db.delete("re_evaluations", id); }

// lifecycle state machine — only these transitions exist (from the BRD via the catalog)
const TRANSITIONS = { reject: { from: "any", to: "rejected" }, resolve: { from: "under_review", to: "resolved" }, start_review: { from: "requested", to: "under_review" } } as const;
export async function transitionReEvaluations(id: string, action: keyof typeof TRANSITIONS) {
  const row = await db.get("re_evaluations", id) as { status?: string };
  const t = TRANSITIONS[action];
  if (!t) throw new Error(`unknown action ${action} on re_evaluations`);
  if (t.from !== "any" && row.status !== t.from)
    throw new Error(`illegal transition ${action}: re_evaluations is "${row.status}", needs "${t.from}"`);
  return db.update("re_evaluations", id, { status: t.to });
}
