// GENERATED by gen_services (Robot 5) from canonical + rule_catalog — DO NOT EDIT.
import { db } from "@/runtime/db";              // frozen data kernel
import { validateSchoolSettings } from "@/rules/school_settings.rules"; // from gen_rules (Robot 7)

export type SchoolSettingsInput = {
  settings_code?: string;
  school_id: string;
  display_name?: string;
  emblem_url?: string;
  emblem_on_certificate?: string;
  contact_email?: string;
};

export async function createSchoolSettings(input: SchoolSettingsInput) {
  const data: Record<string, unknown> = { ...input };
  if (!data.settings_code) data.settings_code = "SETT-" + crypto.randomUUID().slice(0, 8).toUpperCase();  // BRD §18: auto-generated, unique + stable
  const errors = validateSchoolSettings(data);
  if (errors.length) return { ok: false as const, errors };
  return { ok: true as const, data: await db.insert("school_settings", data) };
}

export async function getSchoolSettings(id: string) { return db.get("school_settings", id); }
export async function listSchoolSettings() { return db.list("school_settings"); }
export async function updateSchoolSettings(id: string, patch: Partial<SchoolSettingsInput>) { return db.update("school_settings", id, patch); }
export async function deleteSchoolSettings(id: string) { return db.delete("school_settings", id); }
