// GENERATED by gen_services (Robot 5) from canonical + rule_catalog — DO NOT EDIT.
import { db } from "@/runtime/db";              // frozen data kernel
import { validateSchoolImports } from "@/rules/school_imports.rules"; // from gen_rules (Robot 7)

export type SchoolImportsInput = {
  import_code: string;
  source: string;
  file: string;
  total_rows?: number;
  imported_count?: number;
  failed_count?: number;
  status?: string;
  error_summary?: string;
};

export async function createSchoolImports(input: SchoolImportsInput) {
  const errors = validateSchoolImports(input);
  if (errors.length) return { ok: false as const, errors };
  return { ok: true as const, data: await db.insert("school_imports", input) };
}

export async function getSchoolImports(id: string) { return db.get("school_imports", id); }
export async function listSchoolImports() { return db.list("school_imports"); }
export async function updateSchoolImports(id: string, patch: Partial<SchoolImportsInput>) { return db.update("school_imports", id, patch); }

// lifecycle state machine — only these transitions exist (from the BRD via the catalog)
const TRANSITIONS = { complete_import: { from: "validating", to: "imported" }, fail_import: { from: "any", to: "failed" }, validate_rows: { from: "uploaded", to: "validating" } } as const;
export async function transitionSchoolImports(id: string, action: keyof typeof TRANSITIONS) {
  const row = await db.get("school_imports", id) as { status?: string };
  const t = TRANSITIONS[action];
  if (!t) throw new Error(`unknown action ${action} on school_imports`);
  if (t.from !== "any" && row.status !== t.from)
    throw new Error(`illegal transition ${action}: school_imports is "${row.status}", needs "${t.from}"`);
  return db.update("school_imports", id, { status: t.to });
}
