// GENERATED by gen_services (Robot 5) from canonical + rule_catalog — DO NOT EDIT.
import { db } from "../runtime/db";              // frozen data kernel
import { validateSchools } from "../rules/schools.rules"; // from gen_rules (Robot 7)

export type SchoolsInput = {
  school_code: string;
  name: string;
  board?: string;
  city: string;
  state: string;
  country?: string;
  address?: string;
  principal_name?: string;
  coordinator_name: string;
  coordinator_email: string;
  coordinator_mobile?: string;
  status?: string;
};

export async function createSchools(input: SchoolsInput) {
  const errors = validateSchools(input);
  if (errors.length) return { ok: false as const, errors };
  return { ok: true as const, data: await db.insert("schools", input) };
}

export async function getSchools(id: string) { return db.get("schools", id); }
export async function listSchools() { return db.list("schools"); }
export async function updateSchools(id: string, patch: Partial<SchoolsInput>) { return db.update("schools", id, patch); }

// lifecycle state machine — only these transitions exist (from the BRD via the catalog)
const TRANSITIONS = { approve_school: { from: "registered", to: "approved" }, block_school: { from: "any", to: "blocked" }, open_student_upload: { from: "approved", to: "students_open" }, submit_registration: { from: "lead", to: "registered" } } as const;
export async function transitionSchools(id: string, action: keyof typeof TRANSITIONS) {
  const row = await db.get("schools", id) as { status?: string };
  const t = TRANSITIONS[action];
  if (!t) throw new Error(`unknown action ${action} on schools`);
  if (t.from !== "any" && row.status !== t.from)
    throw new Error(`illegal transition ${action}: schools is "${row.status}", needs "${t.from}"`);
  return db.update("schools", id, { status: t.to });
}
