// GENERATED by gen_services (Robot 5) from canonical + rule_catalog — DO NOT EDIT.
import { db } from "@/runtime/db";              // frozen data kernel
import { validateSchools } from "@/rules/schools.rules"; // from gen_rules (Robot 7)
import { advanceParticipation } from "@/services/participations.service"; // effect + cascade chains

export type SchoolsInput = {
  school_code?: string;
  name: string;
  board?: string;
  city: string;
  state: string;
  country?: string;
  address_line1?: string;
  address_line2?: string;
  locality?: string;
  pincode?: string;
  principal_name?: string;
  coordinator_name: string;
  coordinator_email: string;
  coordinator_mobile?: string;
  status?: string;
  website?: string;
  source: string;
  unsubscribed?: boolean;
  last_contacted_at?: string;
  import_id?: string;
};

export async function createSchools(input: SchoolsInput) {
  const data: Record<string, unknown> = { ...input };
  if (!data.school_code) data.school_code = "SCHO-" + crypto.randomUUID().slice(0, 8).toUpperCase();  // BRD §18: auto-generated, unique + stable
  const errors = validateSchools(data);
  if (errors.length) return { ok: false as const, errors };
  return { ok: true as const, data: await db.insert("schools", data) };
}

export async function getSchools(id: string) { return db.get("schools", id); }
export async function listSchools() { return db.list("schools"); }
export async function updateSchools(id: string, patch: Partial<SchoolsInput>) { return db.update("schools", id, patch); }
export async function deleteSchools(id: string) { return db.delete("schools", id); }

// lifecycle state machine — only these transitions exist (from the BRD via the catalog)
const TRANSITIONS = { activate: { from: "inactive", to: "approved" }, approve_school: { from: "registered", to: "approved" }, block_school: { from: "any", to: "blocked" }, deactivate: { from: "approved", to: "inactive" }, register_interest: { from: "prospect", to: "lead" }, reject_school: { from: "registered", to: "rejected" }, submit_registration: { from: "lead", to: "registered" } } as const;
export async function transitionSchools(id: string, action: keyof typeof TRANSITIONS) {
  const row = await db.get("schools", id) as { status?: string };
  const t = TRANSITIONS[action];
  if (!t) throw new Error(`unknown action ${action} on schools`);
  if (t.from !== "any" && row.status !== t.from)
    throw new Error(`illegal transition ${action}: schools is "${row.status}", needs "${t.from}"`);
  if (action === "submit_registration" && (!(row as Record<string, unknown>).address_line1 || !(row as Record<string, unknown>).locality || !(row as Record<string, unknown>).pincode)) throw new Error("submit_registration requires: address_line1, locality, pincode");
  const updated = await db.update("schools", id, { status: t.to });
  // EFFECT CHAINS (spine) + registration side-effect (create participation)
  if (action === "submit_registration") { const _olys = await db.list("olympiads"); if (_olys.length) await db.insert("participations", { participation_code: "PART-" + crypto.randomUUID().slice(0, 6).toUpperCase(), school_id: id, olympiad_id: (_olys[0] as { id: string }).id, status: "submitted" }); }  // BRD: registration creates a participation
  if (action === "approve_school") { const _rel = (await db.list("participations")).filter((r) => (r as Record<string, unknown>).school_id === id); for (const _p of _rel) await advanceParticipation((_p as { id: string }).id, "students_open"); }  // cascade: open related participations
  return updated;
}
