// GENERATED by gen_services (Robot 5) from canonical + rule_catalog — DO NOT EDIT.
import { db } from "@/runtime/db";              // frozen data kernel
import { validateSchoolUsers } from "@/rules/school_users.rules"; // from gen_rules (Robot 7)

export type SchoolUsersInput = {
  directus_user_id: string;
  school_id: string;
  role_label?: string;
  is_primary?: boolean;
  status?: string;
};

export async function createSchoolUsers(input: SchoolUsersInput) {
  const errors = validateSchoolUsers(input);
  if (errors.length) return { ok: false as const, errors };
  return { ok: true as const, data: await db.insert("school_users", input) };
}

export async function getSchoolUsers(id: string) { return db.get("school_users", id); }
export async function listSchoolUsers() { return db.list("school_users"); }
export async function updateSchoolUsers(id: string, patch: Partial<SchoolUsersInput>) { return db.update("school_users", id, patch); }
