// GENERATED by gen_services (Robot 5) from canonical + rule_catalog — DO NOT EDIT.
import { db } from "@/runtime/db";              // frozen data kernel
import { validateStudyResources } from "@/rules/study_resources.rules"; // from gen_rules (Robot 7)

export type StudyResourcesInput = {
  resource_code?: string;
  olympiad_id: string;
  grade?: string;
  kind?: string;
  title: string;
  url: string;
  status?: string;
};

export async function createStudyResources(input: StudyResourcesInput) {
  const data: Record<string, unknown> = { ...input };
  if (!data.resource_code) data.resource_code = "RESO-" + crypto.randomUUID().slice(0, 8).toUpperCase();  // BRD §18: auto-generated, unique + stable
  const errors = validateStudyResources(data);
  if (errors.length) return { ok: false as const, errors };
  return { ok: true as const, data: await db.insert("study_resources", data) };
}

export async function getStudyResources(id: string) { return db.get("study_resources", id); }
export async function listStudyResources() { return db.list("study_resources"); }
export async function updateStudyResources(id: string, patch: Partial<StudyResourcesInput>) { return db.update("study_resources", id, patch); }
export async function deleteStudyResources(id: string) { return db.delete("study_resources", id); }

// lifecycle state machine — only these transitions exist (from the BRD via the catalog)
const TRANSITIONS = { archive: { from: "any", to: "archived" }, publish: { from: "draft", to: "published" }, unpublish: { from: "published", to: "draft" } } as const;
export async function transitionStudyResources(id: string, action: keyof typeof TRANSITIONS) {
  const row = await db.get("study_resources", id) as { status?: string };
  const t = TRANSITIONS[action];
  if (!t) throw new Error(`unknown action ${action} on study_resources`);
  if (t.from !== "any" && row.status !== t.from)
    throw new Error(`illegal transition ${action}: study_resources is "${row.status}", needs "${t.from}"`);
  const updated = await db.update("study_resources", id, { status: t.to });
  try { await db.insert("audit_events", { trace_id: "AUD-" + crypto.randomUUID().slice(0, 12), action, entity_name: "study_resources", entity_id: id, previous_status: (row as { status?: string }).status ?? null, new_status: t.to, created_at: new Date().toISOString() }); } catch (e) { /* audit best-effort */ }
  return updated;
}
