// GENERATED by gen_services (Robot 5) from canonical + rule_catalog — DO NOT EDIT.
import { db } from "@/runtime/db";              // frozen data kernel
import { validateStudents } from "@/rules/students.rules"; // from gen_rules (Robot 7)

export type StudentsInput = {
  candidate_id: string;
  school_id: string;
  participation_id: string;
  student_name: string;
  grade: string;
  section?: string;
  school_roll_number?: string;
  parent_guardian_name?: string;
  parent_contact?: string;
  consent_obtained: boolean;
  consent_date?: string;
  status?: string;
  validation_errors?: Record<string, unknown>;
};

export async function createStudents(input: StudentsInput) {
  const data: Record<string, unknown> = { ...input };
  if (!data.candidate_id) data.candidate_id = "CAND-" + crypto.randomUUID().slice(0, 8).toUpperCase();  // BRD §18: auto-generated, unique + stable
  const errors = validateStudents(data);
  if (errors.length) return { ok: false as const, errors };
  return { ok: true as const, data: await db.insert("students", data) };
}

export async function getStudents(id: string) { return db.get("students", id); }
export async function listStudents() { return db.list("students"); }
export async function updateStudents(id: string, patch: Partial<StudentsInput>) { return db.update("students", id, patch); }
export async function deleteStudents(id: string) { return db.delete("students", id); }
