// GENERATED by gen_services (Robot 5) from canonical + rule_catalog — DO NOT EDIT.
import { db } from "@/runtime/db";              // frozen data kernel
import { validateUsers } from "@/rules/users.rules"; // from gen_rules (Robot 7)

export type UsersInput = {
  email: string;
  full_name: string;
  role: string;
  user_status: string;
};

export async function createUsers(input: UsersInput) {
  const errors = validateUsers(input);
  if (errors.length) return { ok: false as const, errors };
  return { ok: true as const, data: await db.insert("users", input) };
}

export async function getUsers(id: string) { return db.get("users", id); }
export async function listUsers() { return db.list("users"); }
export async function updateUsers(id: string, patch: Partial<UsersInput>) { return db.update("users", id, patch); }
export async function deleteUsers(id: string) { return db.delete("users", id); }
