// GENERATED by gen_routes (Robot 6) — DO NOT EDIT.
import { getAnswerKeys, updateAnswerKeys, deleteAnswerKeys } from "@/services/answer_keys.service";
import { ok, err } from "@/runtime/envelope";

export async function GET(_req: Request, { params }: { params: { id: string } }) {
  const row = await getAnswerKeys(params.id);
  return row ? ok(row) : err("NOT_FOUND", 404, "answer_keys not found");
}

export async function PATCH(req: Request, { params }: { params: { id: string } }) {
  return ok(await updateAnswerKeys(params.id, await req.json()));
}

export async function DELETE(_req: Request, { params }: { params: { id: string } }) {
  return ok(await deleteAnswerKeys(params.id));
}
