// GENERATED by gen_routes (Robot 6) — DO NOT EDIT.
import { getCertificates, updateCertificates, deleteCertificates } from "@/services/certificates.service";
import { ok, err } from "@/runtime/envelope";

export async function GET(_req: Request, { params }: { params: { id: string } }) {
  const row = await getCertificates(params.id);
  return row ? ok(row) : err("NOT_FOUND", 404, "certificates not found");
}

export async function PATCH(req: Request, { params }: { params: { id: string } }) {
  return ok(await updateCertificates(params.id, await req.json()));
}

export async function DELETE(_req: Request, { params }: { params: { id: string } }) {
  return ok(await deleteCertificates(params.id));
}
