// GENERATED by gen_endpoints.py from spec/endpoints/school_lookup.json — DO NOT EDIT. Edit the spec + regenerate.
import { NextRequest, NextResponse } from "next/server";
import { requireSchoolScope } from "@/server/guards/requireSchoolScope";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";
import { LOOKUP_LABELS } from "@/server/lookups/labelColumns.generated";
import { SCHOOL_SCOPE } from "@/server/lookups/schoolScope.generated";
import { ok, meta } from "@/server/http/envelope";
import { lookupQuery, lookupResult, escapeLike } from "@/server/lookups/query";

const MOD = "school_dashboard";
type Row = Record<string, unknown>;
const rows = (data: unknown) => (data ?? []) as unknown as Row[];

export async function GET(request: NextRequest, ctx: { params: Promise<{ table: string }> }) {
  const { table } = await ctx.params;
  const guard = await requireSchoolScope(request, MOD);
  if (!guard.ok) return NextResponse.json(guard.body, { status: guard.status });
  const schoolId = guard.actor.school_id;
  const labelCol = LOOKUP_LABELS[table];
  const scope = SCHOOL_SCOPE[table];
  const empty = () => NextResponse.json(ok({ items: [], hasMore: false }, meta(guard.requestId, MOD)));
  if (!labelCol || !schoolId || !scope || scope.kind === "none") return empty();

  const supabase = createSupabaseAdminClient();
  const { q, limit } = lookupQuery(request);
  const finalize = (col: "school_id" | "id" | string, ids: string | string[]) => {
    let query = supabase.from(table).select(`id, ${labelCol}`);
    query = Array.isArray(ids) ? query.in(col, ids) : query.eq(col, ids);
    if (q && labelCol !== "id") query = query.ilike(labelCol, `%${escapeLike(q)}%`);
    return query.order(labelCol === "id" ? "id" : labelCol, { ascending: true }).limit(limit + 1);
  };
  const respond = async (col: string, ids: string | string[]) => {
    if (Array.isArray(ids) && !ids.length) return empty();
    const { data, error } = await finalize(col, ids);
    if (error) return empty();
    return NextResponse.json(ok(lookupResult(data, labelCol, limit), meta(guard.requestId, MOD)));
  };

  if (scope.kind === "direct") return respond("school_id", schoolId);

  if (scope.kind === "path") {
    const hops = scope.hops;
    const { data: anc } = await supabase.from(hops[hops.length - 1].parent).select("id").eq("school_id", schoolId);
    let ids = rows(anc).map((r) => String(r.id));
    for (let i = hops.length - 1; i >= 1; i--) {
      if (!ids.length) return empty();
      const { data } = await supabase.from(hops[i - 1].parent).select("id").in(hops[i].via, ids);
      ids = rows(data).map((r) => String(r.id));
    }
    return respond(hops[0].via, ids);
  }

  const { data: links } = await supabase.from(scope.junction).select(scope.fk).eq("school_id", schoolId);
  const ids = rows(links).map((l) => l[scope.fk]).filter(Boolean) as string[];
  return respond("id", ids);
}
