#!/usr/bin/env python3
"""
generate_rollback.py

Purpose
-------
Create machine-readable rollback entries for every release/change.

Usage
-----
python scripts/generate_rollback.py --root . --release REL-2026-0001 --module finance_ops --risk critical
python scripts/generate_rollback.py --root . --release REL-2026-0001 --module results_ops --changed-file app/staff/results/page.tsx
"""

from __future__ import annotations

import argparse
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List

def now() -> str:
    return datetime.now(timezone.utc).isoformat()

def load_json(path: Path, default: Any = None) -> Any:
    if not path.exists():
        return default
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)

def rollback_type_for_risk(risk: str) -> str:
    if risk in ["critical", "high"]:
        return "manual"
    return "automatic"

def build_entry(args: argparse.Namespace) -> Dict[str, Any]:
    risk = args.risk
    rbk_id = args.rollback_id or f"RBK-{datetime.now(timezone.utc).strftime('%Y%m%d')}-0001"
    return {
        "rollback_id": rbk_id,
        "release_id": args.release,
        "environment": args.environment,
        "created_at": now(),
        "owner": {"name": args.owner_name, "role": args.owner_role, "email": args.owner_email},
        "risk_level": risk,
        "affected_modules": args.module,
        "change_summary": args.summary,
        "files_changed": args.changed_file,
        "migrations": [
            {
                "migration_id": m,
                "description": "Review migration before production.",
                "reversible": False if risk in ["critical", "high"] else True,
                "rollback_method": "forward_fix" if risk in ["critical", "high"] else "reverse_migration",
                "data_loss_risk": "medium" if risk in ["critical", "high"] else "none",
                "manual_steps": ["review migration", "take backup", "test rollback in staging"]
            }
            for m in args.migration
        ],
        "feature_flags": [
            {"flag": f, "old_value": None, "new_value": None, "rollback_value": False}
            for f in args.feature_flag
        ],
        "config_changes": [],
        "data_changes": [],
        "external_side_effects": [],
        "rollback_strategy": {
            "type": rollback_type_for_risk(risk),
            "steps": [
                "disable affected feature flags if present",
                "stop affected workers if needed",
                "revert code or deploy previous build",
                "apply reverse migration only if safe; otherwise forward-fix",
                "revoke signed URLs if sensitive files affected",
                "run rollback smoke tests",
                "record rollback audit event"
            ],
            "estimated_risk": risk
        },
        "verification_steps": [
            "run lint/typecheck/tests",
            "run security baseline check",
            "run privacy baseline check",
            "run smoke tests for affected modules",
            "confirm audit event created"
        ],
        "smoke_tests": ["staff login", "dashboard loads", "affected module route loads", "audit event visible"],
        "approval": {"required": risk in ["critical", "high"], "status": "pending" if risk in ["critical", "high"] else "not_required"},
        "notes": "Generated by scripts/generate_rollback.py"
    }

def validate_minimal(entry: Dict[str, Any]) -> List[str]:
    required = ["rollback_id", "release_id", "environment", "created_at", "owner", "risk_level", "affected_modules", "change_summary", "rollback_strategy", "verification_steps", "approval"]
    return [k for k in required if k not in entry or entry[k] in [None, "", []]]

def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", default=".")
    parser.add_argument("--release", required=True)
    parser.add_argument("--module", action="append", required=True)
    parser.add_argument("--risk", choices=["low", "medium", "high", "critical"], default="medium")
    parser.add_argument("--environment", choices=["dev", "staging", "production"], default="dev")
    parser.add_argument("--summary", default="Release/change rollback entry")
    parser.add_argument("--changed-file", action="append", default=[])
    parser.add_argument("--migration", action="append", default=[])
    parser.add_argument("--feature-flag", action="append", default=[])
    parser.add_argument("--rollback-id", default=None)
    parser.add_argument("--owner-name", default="TBD")
    parser.add_argument("--owner-role", default="technical_owner")
    parser.add_argument("--owner-email", default="")
    args = parser.parse_args()

    root = Path(args.root).resolve()
    entry = build_entry(args)
    missing = validate_minimal(entry)
    out_dir = root / "rollback" / "releases"
    out_dir.mkdir(parents=True, exist_ok=True)
    out = out_dir / f"{entry['release_id']}_{entry['rollback_id']}.json"
    out.write_text(json.dumps(entry, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(json.dumps({"status": "ROLLBACK_ENTRY_CREATED" if not missing else "ROLLBACK_ENTRY_CREATED_WITH_WARNINGS", "missing": missing, "file": str(out)}, indent=2))
    return 0 if not missing else 1

if __name__ == "__main__":
    raise SystemExit(main())
