// GENERATED by gen_routes (Robot 6) — DO NOT EDIT.
import { listOmrImports, createOmrImports } from "@/services/omr_imports.service";
import { ok, err } from "@/runtime/envelope";

export async function GET() { return ok(await listOmrImports()); }

export async function POST(req: Request) {
  const input = await req.json();
  const r = await createOmrImports(input);
  return r.ok ? ok(r.data, 201) : err("VALIDATION_FAILED", 422, r.errors);
}
