// GENERATED by gen_routes (Robot 6) — DO NOT EDIT.
import { getOmrImports, updateOmrImports } from "@/services/omr_imports.service";
import { ok, err } from "@/runtime/envelope";

export async function GET(_req: Request, { params }: { params: { id: string } }) {
  const row = await getOmrImports(params.id);
  return row ? ok(row) : err("NOT_FOUND", 404, "omr_imports not found");
}

export async function PATCH(req: Request, { params }: { params: { id: string } }) {
  return ok(await updateOmrImports(params.id, await req.json()));
}
