import { ModuleTable } from "@/components/ModuleTable";

export default function Page() {
  return (
    <ModuleTable
      title="Work Tasks"
      eyebrow="staff \u00b7 task_work_queue_tasks"
      endpoint="/api/staff/tasks/work-tasks"
      columns={[{"key": "task_code", "label": "Task"}, {"key": "task_title", "label": "Task Title"}, {"key": "task_description", "label": "Task Description"}, {"key": "task_type", "label": "Task Type"}, {"key": "task_status", "label": "Status"}]}
      description="Manage and review work tasks across the olympiad operations."
      breadcrumbs={[{"label": "Staff", "href": "/staff/dashboard"}, {"label": "Tasks", "href": "/staff/tasks"}, {"label": "Work Tasks"}]}
      nextAction="\u2192 Use \u201cNew Work Task\u201d to add one, then act on it from the list."
      statusKey="task_status"
      moduleId="task_work_queue_tasks"
      createFields={[{"key": "task_title", "label": "Task Title", "type": "text"}, {"key": "task_description", "label": "Task Description", "type": "text"}, {"key": "task_type", "label": "Task Type", "type": "select", "options": [{"value": "manual", "label": "Manual"}, {"value": "system_follow_up", "label": "System Follow Up"}, {"value": "approval", "label": "Approval"}, {"value": "sla_breach", "label": "SLA Breach"}, {"value": "exception_resolution", "label": "Exception Resolution"}, {"value": "module_action", "label": "Module Action"}, {"value": "support_follow_up", "label": "Support Follow Up"}, {"value": "security_review", "label": "Security Review"}]}, {"key": "source_module", "label": "Source Module", "type": "text"}, {"key": "source_entity_type", "label": "Source Entity Type", "type": "text"}, {"key": "source_entity_id", "label": "Source Entity", "type": "text"}, {"key": "queue_id", "label": "Queue", "type": "reference", "refTable": "task_queues"}, {"key": "assigned_to", "label": "Assigned To", "type": "reference", "refTable": "staff_profiles"}, {"key": "assigned_role", "label": "Assigned Role", "type": "text"}, {"key": "priority", "label": "Priority", "type": "select", "options": [{"value": "low", "label": "Low"}, {"value": "medium", "label": "Medium"}, {"value": "high", "label": "High"}, {"value": "critical", "label": "Critical"}]}, {"key": "due_at", "label": "Due At", "type": "date"}, {"key": "started_at", "label": "Started At", "type": "date"}, {"key": "completed_at", "label": "Completed At", "type": "date"}, {"key": "completion_note", "label": "Completion Note", "type": "text"}, {"key": "outcome_code", "label": "Outcome", "type": "text"}]}
      actions={[{"action": "block", "label": "Block", "variant": "light", "reason": true, "danger": true}, {"action": "escalate", "label": "Escalate", "variant": "light"}, {"action": "cancel", "label": "Cancel", "variant": "light", "reason": true, "danger": true}, {"action": "reopen", "label": "Reopen", "variant": "light"}, {"action": "archive", "label": "Archive", "variant": "light", "reason": true, "danger": true}]}
      detailPanels={[{"key": "task-assignments", "label": "Task Assignments", "subPath": "task-assignments", "listColumns": ["assignment_status", "assigned_to", "assigned_role", "assignment_reason"]}, {"key": "task-dependencies", "label": "Task Dependencies", "subPath": "task-dependencies", "listColumns": ["dependency_status", "dependency_type", "related_module", "related_entity_type"]}, {"key": "task-comments", "label": "Task Comments", "subPath": "task-comments", "listColumns": ["comment_status", "comment_body", "comment_type", "visibility"]}, {"key": "task-sla-events", "label": "Task Sla Events", "subPath": "task-sla-events", "listColumns": ["event_code", "previous_sla_status", "new_sla_status", "reason"]}]}
      toolbar={{"facet": {"key": "task_status", "options": [{"value": "new", "label": "New"}, {"value": "queued", "label": "Queued"}, {"value": "assigned", "label": "Assigned"}, {"value": "in_progress", "label": "In Progress"}, {"value": "blocked", "label": "Blocked"}, {"value": "waiting", "label": "Waiting"}, {"value": "escalated", "label": "Escalated"}, {"value": "completed", "label": "Completed"}, {"value": "cancelled", "label": "Cancelled"}, {"value": "reopened", "label": "Reopened"}, {"value": "archived", "label": "Archived"}]}, "search": true, "sort": [{"value": "created_at:desc", "label": "Newest"}]}}
    />
  );
}
