// GENERATED by gen_routes (Robot 6) — DO NOT EDIT.
import { listAdmitCards, createAdmitCards } from "@/services/admit_cards.service";
import { ok, err } from "@/runtime/envelope";

export async function GET() { return ok(await listAdmitCards()); }

export async function POST(req: Request) {
  const input = await req.json();
  const r = await createAdmitCards(input);
  return r.ok ? ok(r.data, 201) : err("VALIDATION_FAILED", 422, r.errors);
}
