// GENERATED by gen_routes (Robot 6) — DO NOT EDIT.
import { listExamMaterials, createExamMaterials } from "@/services/exam_materials.service";
import { ok, err } from "@/runtime/envelope";

export async function GET() { return ok(await listExamMaterials()); }

export async function POST(req: Request) {
  const input = await req.json();
  const r = await createExamMaterials(input);
  return r.ok ? ok(r.data, 201) : err("VALIDATION_FAILED", 422, r.errors);
}
