// GENERATED by gen_endpoints.py from spec/endpoints/staff_exports.json — DO NOT EDIT. Edit the spec + regenerate.
import { NextRequest, NextResponse } from "next/server";
import { requireStaffScope } from "@/server/guards/requireStaffScope";
import { createExportRequest, listExports } from "@/server/reports/exportRequests";
import { ok, err, meta } from "@/server/http/envelope";

const MOD = "reports_exports";

export async function GET(request: NextRequest) {
  const guard = await requireStaffScope(request, "reports_exports", "read");
  if (!guard.ok) return NextResponse.json(guard.body, { status: guard.status });
  const data = await listExports();
  return NextResponse.json(ok(data, meta(guard.requestId, MOD)));
}

export async function POST(request: NextRequest) {
  const guard = await requireStaffScope(request, "reports_exports", "write");
  if (!guard.ok) return NextResponse.json(guard.body, { status: guard.status });
  let body: Record<string, unknown>;
  try { body = (await request.json()) as Record<string, unknown>; } catch { body = {}; }
  const result = await createExportRequest(guard.actor, body);
  if ("error" in result) return NextResponse.json(err(result.error.code, result.error.message, meta(guard.requestId, MOD), result.error.field_errors ? { field_errors: result.error.field_errors } : undefined), { status: result.error.status });
  return NextResponse.json(ok(result.data, meta(guard.requestId, MOD)));
}
