#!/usr/bin/env python3
"""Generate Next.js route handlers from spec/endpoints/*.json — the centralized owner of every CUSTOM
(non-module-CRUD) app route, so no app route is hand-written (master-loop: never hand-edit generated output;
routes flow from a spec). Each spec selects a `kind` (lookup, list, action, file, ingest, aggregate,
public_read, ...) + params; this emits the full route.ts. Deep domain logic stays in @/server/* services that
the generated route calls. Run from the repo root: python _validation/gen_endpoints.py

Infra endpoints (health/cron/internal/webhook) are intentionally NOT owned here — they are hand-written and
exempt in check_generated (documented), per the founder's "keep infra separate" decision (2026-06-26)."""
import json, sys
from pathlib import Path

APP = Path("versa-oms/app/app")
SPECS = Path("versa-oms/spec/endpoints")


def header(spec_file):
    return f"// GENERATED by gen_endpoints.py from spec/endpoints/{spec_file} — DO NOT EDIT. Edit the spec + regenerate.\n"


# ---- kind: lookup -------------------------------------------------------------------------------------
# Reference-picker data for any FK-target table. Staff sees all; school sees only its own rows (SCHOOL_SCOPE).
# Both support ?q= label search + ?limit= pagination (server/lookups/query.ts).

def _lookup_staff():
    return '''import { NextRequest, NextResponse } from "next/server";
import { requireStaffScope } from "@/server/guards/requireStaffScope";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";
import { LOOKUP_LABELS } from "@/server/lookups/labelColumns.generated";
import { ok, err, meta } from "@/server/http/envelope";
import { lookupQuery, lookupResult, escapeLike } from "@/server/lookups/query";

const MOD = "company_dashboard"; // any authenticated staff may read reference data

export async function GET(request: NextRequest, ctx: { params: Promise<{ table: string }> }) {
  const { table } = await ctx.params;
  const guard = await requireStaffScope(request, MOD, "read");
  if (!guard.ok) return NextResponse.json(guard.body, { status: guard.status });

  const labelCol = LOOKUP_LABELS[table];
  if (!labelCol) return NextResponse.json(err("NOT_FOUND", "Not a reference table.", meta(guard.requestId, MOD)), { status: 404 });

  const { q, limit } = lookupQuery(request);
  const supabase = createSupabaseAdminClient();
  let query = supabase.from(table).select(`id, ${labelCol}`);
  if (q && labelCol !== "id") query = query.ilike(labelCol, `%${escapeLike(q)}%`);
  const { data, error } = await query.order(labelCol === "id" ? "id" : labelCol, { ascending: true }).limit(limit + 1);
  if (error) return NextResponse.json(ok({ items: [], hasMore: false }, meta(guard.requestId, MOD)));
  return NextResponse.json(ok(lookupResult(data, labelCol, limit), meta(guard.requestId, MOD)));
}
'''


def _lookup_school():
    return '''import { NextRequest, NextResponse } from "next/server";
import { requireSchoolScope } from "@/server/guards/requireSchoolScope";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";
import { LOOKUP_LABELS } from "@/server/lookups/labelColumns.generated";
import { SCHOOL_SCOPE } from "@/server/lookups/schoolScope.generated";
import { ok, meta } from "@/server/http/envelope";
import { lookupQuery, lookupResult, escapeLike } from "@/server/lookups/query";

const MOD = "school_dashboard";
type Row = Record<string, unknown>;
const rows = (data: unknown) => (data ?? []) as unknown as Row[];

export async function GET(request: NextRequest, ctx: { params: Promise<{ table: string }> }) {
  const { table } = await ctx.params;
  const guard = await requireSchoolScope(request, MOD);
  if (!guard.ok) return NextResponse.json(guard.body, { status: guard.status });
  const schoolId = guard.actor.school_id;
  const labelCol = LOOKUP_LABELS[table];
  const scope = SCHOOL_SCOPE[table];
  const empty = () => NextResponse.json(ok({ items: [], hasMore: false }, meta(guard.requestId, MOD)));
  if (!labelCol || !schoolId || !scope || scope.kind === "none") return empty();

  const supabase = createSupabaseAdminClient();
  const { q, limit } = lookupQuery(request);
  const finalize = (col: "school_id" | "id" | string, ids: string | string[]) => {
    let query = supabase.from(table).select(`id, ${labelCol}`);
    query = Array.isArray(ids) ? query.in(col, ids) : query.eq(col, ids);
    if (q && labelCol !== "id") query = query.ilike(labelCol, `%${escapeLike(q)}%`);
    return query.order(labelCol === "id" ? "id" : labelCol, { ascending: true }).limit(limit + 1);
  };
  const respond = async (col: string, ids: string | string[]) => {
    if (Array.isArray(ids) && !ids.length) return empty();
    const { data, error } = await finalize(col, ids);
    if (error) return empty();
    return NextResponse.json(ok(lookupResult(data, labelCol, limit), meta(guard.requestId, MOD)));
  };

  if (scope.kind === "direct") return respond("school_id", schoolId);

  if (scope.kind === "path") {
    const hops = scope.hops;
    const { data: anc } = await supabase.from(hops[hops.length - 1].parent).select("id").eq("school_id", schoolId);
    let ids = rows(anc).map((r) => String(r.id));
    for (let i = hops.length - 1; i >= 1; i--) {
      if (!ids.length) return empty();
      const { data } = await supabase.from(hops[i - 1].parent).select("id").in(hops[i].via, ids);
      ids = rows(data).map((r) => String(r.id));
    }
    return respond(hops[0].via, ids);
  }

  const { data: links } = await supabase.from(scope.junction).select(scope.fk).eq("school_id", schoolId);
  const ids = rows(links).map((l) => l[scope.fk]).filter(Boolean) as string[];
  return respond("id", ids);
}
'''


def emit_lookup(spec):
    return _lookup_staff() if spec["portal"] == "staff" else _lookup_school()


# ---- kind: aggregate ----------------------------------------------------------------------------------
# A read-only GET that guards, calls one kernel aggregation service, and envelopes the result. The logic
# lives in a frozen-kernel service (e.g. server/lib/dashboard.ts); the route is pure wiring.

def emit_aggregate(spec):
    portal, mod, svc = spec["portal"], spec["module"], spec["service"]
    imp, key = spec["importFrom"], spec["resultKey"]
    if portal == "staff":
        gimport = 'import { requireStaffScope } from "@/server/guards/requireStaffScope";'
        gcall = f'await requireStaffScope(request, {json.dumps(mod)}, "read")'
        arg = "guard.actor"
    else:
        gimport = 'import { requireSchoolScope } from "@/server/guards/requireSchoolScope";'
        gcall = f'await requireSchoolScope(request, {json.dumps(mod)})'
        arg = 'guard.actor.school_id ?? ""'
    return ('import { NextRequest, NextResponse } from "next/server";\n'
            f'{gimport}\n'
            f'import {{ {svc} }} from "{imp}";\n'
            'import { ok, meta } from "@/server/http/envelope";\n\n'
            'export async function GET(request: NextRequest) {\n'
            f'  const guard = {gcall};\n'
            '  if (!guard.ok) return NextResponse.json(guard.body, { status: guard.status });\n'
            f'  const {key} = await {svc}({arg});\n'
            f'  return NextResponse.json(ok({{ {key} }}, meta(guard.requestId, {json.dumps(mod)})));\n'
            '}\n')


KINDS = {"lookup": emit_lookup, "aggregate": emit_aggregate}


def main():
    count = 0
    for sf in sorted(SPECS.glob("*.json")):
        spec = json.loads(sf.read_text(encoding="utf-8"))
        kind = spec.get("kind")
        if kind not in KINDS:
            print(f"  SKIP {sf.name}: unknown kind {kind!r}", file=sys.stderr)
            continue
        body = KINDS[kind](spec)
        out = APP / Path(*spec["path"].split("/")) / "route.ts"
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(header(sf.name) + body, encoding="utf-8")
        count += 1
    print(f"endpoints generated: {count}")


if __name__ == "__main__":
    main()
