#!/usr/bin/env python3
"""Generate Next.js route handlers from spec/endpoints/*.json — the centralized owner of every CUSTOM
(non-module-CRUD) app route, so no app route is hand-written (master-loop: never hand-edit generated output;
routes flow from a spec). Each spec selects a `kind` (lookup, list, action, file, ingest, aggregate,
public_read, ...) + params; this emits the full route.ts. Deep domain logic stays in @/server/* services that
the generated route calls. Run from the repo root: python _validation/gen_endpoints.py

Infra endpoints (health/cron/internal/webhook) are intentionally NOT owned here — they are hand-written and
exempt in check_generated (documented), per the founder's "keep infra separate" decision (2026-06-26)."""
import json, sys
from pathlib import Path

APP = Path("versa-oms/app/app")
SPECS = Path("versa-oms/spec/endpoints")


def header(spec_file):
    return f"// GENERATED by gen_endpoints.py from spec/endpoints/{spec_file} — DO NOT EDIT. Edit the spec + regenerate.\n"


# ---- kind: lookup -------------------------------------------------------------------------------------
# Reference-picker data for any FK-target table. Staff sees all; school sees only its own rows (SCHOOL_SCOPE).
# Both support ?q= label search + ?limit= pagination (server/lookups/query.ts).

def _lookup_staff():
    return '''import { NextRequest, NextResponse } from "next/server";
import { requireStaffScope } from "@/server/guards/requireStaffScope";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";
import { LOOKUP_LABELS } from "@/server/lookups/labelColumns.generated";
import { ok, err, meta } from "@/server/http/envelope";
import { lookupQuery, lookupResult, escapeLike } from "@/server/lookups/query";

const MOD = "company_dashboard"; // any authenticated staff may read reference data

export async function GET(request: NextRequest, ctx: { params: Promise<{ table: string }> }) {
  const { table } = await ctx.params;
  const guard = await requireStaffScope(request, MOD, "read");
  if (!guard.ok) return NextResponse.json(guard.body, { status: guard.status });

  const labelCol = LOOKUP_LABELS[table];
  if (!labelCol) return NextResponse.json(err("NOT_FOUND", "Not a reference table.", meta(guard.requestId, MOD)), { status: 404 });

  const { q, limit } = lookupQuery(request);
  const supabase = createSupabaseAdminClient();
  let query = supabase.from(table).select(`id, ${labelCol}`);
  if (q && labelCol !== "id") query = query.ilike(labelCol, `%${escapeLike(q)}%`);
  const { data, error } = await query.order(labelCol === "id" ? "id" : labelCol, { ascending: true }).limit(limit + 1);
  if (error) return NextResponse.json(ok({ items: [], hasMore: false }, meta(guard.requestId, MOD)));
  return NextResponse.json(ok(lookupResult(data, labelCol, limit), meta(guard.requestId, MOD)));
}
'''


def _lookup_school():
    return '''import { NextRequest, NextResponse } from "next/server";
import { requireSchoolScope } from "@/server/guards/requireSchoolScope";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";
import { LOOKUP_LABELS } from "@/server/lookups/labelColumns.generated";
import { SCHOOL_SCOPE } from "@/server/lookups/schoolScope.generated";
import { ok, meta } from "@/server/http/envelope";
import { lookupQuery, lookupResult, escapeLike } from "@/server/lookups/query";

const MOD = "school_dashboard";
type Row = Record<string, unknown>;
const rows = (data: unknown) => (data ?? []) as unknown as Row[];

export async function GET(request: NextRequest, ctx: { params: Promise<{ table: string }> }) {
  const { table } = await ctx.params;
  const guard = await requireSchoolScope(request, MOD);
  if (!guard.ok) return NextResponse.json(guard.body, { status: guard.status });
  const schoolId = guard.actor.school_id;
  const labelCol = LOOKUP_LABELS[table];
  const scope = SCHOOL_SCOPE[table];
  const empty = () => NextResponse.json(ok({ items: [], hasMore: false }, meta(guard.requestId, MOD)));
  if (!labelCol || !schoolId || !scope || scope.kind === "none") return empty();

  const supabase = createSupabaseAdminClient();
  const { q, limit } = lookupQuery(request);
  const finalize = (col: "school_id" | "id" | string, ids: string | string[]) => {
    let query = supabase.from(table).select(`id, ${labelCol}`);
    query = Array.isArray(ids) ? query.in(col, ids) : query.eq(col, ids);
    if (q && labelCol !== "id") query = query.ilike(labelCol, `%${escapeLike(q)}%`);
    return query.order(labelCol === "id" ? "id" : labelCol, { ascending: true }).limit(limit + 1);
  };
  const respond = async (col: string, ids: string | string[]) => {
    if (Array.isArray(ids) && !ids.length) return empty();
    const { data, error } = await finalize(col, ids);
    if (error) return empty();
    return NextResponse.json(ok(lookupResult(data, labelCol, limit), meta(guard.requestId, MOD)));
  };

  if (scope.kind === "direct") return respond("school_id", schoolId);

  if (scope.kind === "path") {
    const hops = scope.hops;
    const { data: anc } = await supabase.from(hops[hops.length - 1].parent).select("id").eq("school_id", schoolId);
    let ids = rows(anc).map((r) => String(r.id));
    for (let i = hops.length - 1; i >= 1; i--) {
      if (!ids.length) return empty();
      const { data } = await supabase.from(hops[i - 1].parent).select("id").in(hops[i].via, ids);
      ids = rows(data).map((r) => String(r.id));
    }
    return respond(hops[0].via, ids);
  }

  const { data: links } = await supabase.from(scope.junction).select(scope.fk).eq("school_id", schoolId);
  const ids = rows(links).map((l) => l[scope.fk]).filter(Boolean) as string[];
  return respond("id", ids);
}
'''


def emit_lookup(spec):
    return _lookup_staff() if spec["portal"] == "staff" else _lookup_school()


# ---- kind: aggregate ----------------------------------------------------------------------------------
# A read-only GET that guards, calls one kernel aggregation service, and envelopes the result. The logic
# lives in a frozen-kernel service (e.g. server/lib/dashboard.ts); the route is pure wiring.

def emit_aggregate(spec):
    portal, mod, svc = spec["portal"], spec["module"], spec["service"]
    imp, key = spec["importFrom"], spec.get("resultKey")  # resultKey null/absent -> passthrough (result IS the data)
    if portal == "staff":
        gimport = 'import { requireStaffScope } from "@/server/guards/requireStaffScope";'
        gcall = f'await requireStaffScope(request, {json.dumps(mod)}, "read")'
        default_arg = "actor"
    else:
        gimport = 'import { requireSchoolScope } from "@/server/guards/requireSchoolScope";'
        gcall = f'await requireSchoolScope(request, {json.dumps(mod)})'
        default_arg = "school_id"
    arg = {"actor": "guard.actor", "school_id": 'guard.actor.school_id ?? ""', "none": ""}[spec.get("arg", default_arg)]
    if key:
        call = f'  const {key} = await {svc}({arg});\n  return NextResponse.json(ok({{ {key} }}, meta(guard.requestId, {json.dumps(mod)})));\n'
    else:
        call = f'  const data = await {svc}({arg});\n  return NextResponse.json(ok(data, meta(guard.requestId, {json.dumps(mod)})));\n'
    return ('import { NextRequest, NextResponse } from "next/server";\n'
            f'{gimport}\n'
            f'import {{ {svc} }} from "{imp}";\n'
            'import { ok, meta } from "@/server/http/envelope";\n\n'
            'export async function GET(request: NextRequest) {\n'
            f'  const guard = {gcall};\n'
            '  if (!guard.ok) return NextResponse.json(guard.body, { status: guard.status });\n'
            + call + '}\n')


# ---- kind: create -------------------------------------------------------------------------------------
# GET = list (a kernel service) + POST = guard -> validate (compiled rule) -> kernel create op -> envelope.
# The bespoke create logic lives in a kernel op returning { data } | { error: {code,message,status} }.

def emit_create(spec):
    import collections
    portal, mod = spec["portal"], spec["module"]
    L, C = spec["list"], spec["create"]
    if portal == "school":
        gimport = 'import { requireSchoolScope } from "@/server/guards/requireSchoolScope";'
        gget = gpost = f'await requireSchoolScope(request, {json.dumps(mod)})'
        create_call = f'await {C["service"]}(schoolId, body, guard.actor)'
        school_check = ('  const schoolId = String(guard.actor.school_id ?? "");\n'
                        '  if (!schoolId) return NextResponse.json(err("FORBIDDEN", "No school in scope.", meta(guard.requestId, MOD)), { status: 403 });\n')
    else:
        gimport = 'import { requireStaffScope } from "@/server/guards/requireStaffScope";'
        gget = f'await requireStaffScope(request, {json.dumps(mod)}, "read")'
        gpost = f'await requireStaffScope(request, {json.dumps(mod)}, "write")'
        create_call = f'await {C["service"]}(guard.actor, body)'
        school_check = ""
    validator = C.get("validator")  # optional — a compiled rule when validation is entity-derived; absent when
    # the create op does its own bespoke (cross-table) validation and returns a 422 with field_errors.
    imps = collections.defaultdict(set)
    imps[L["from"]].add(L["service"]); imps[C["from"]].add(C["service"])
    if validator:
        imps[C["validatorFrom"]].add(validator)
    svc_imports = "\n".join(f'import {{ {", ".join(sorted(n))} }} from "{p}";' for p, n in sorted(imps.items()))
    list_arg = {"school_id": 'guard.actor.school_id ?? ""', "actor": "guard.actor", "none": ""}[L.get("arg", "none")]
    validate_step = (f'  const fieldErrors = {validator}(body);\n'
                     '  if (fieldErrors.length) return NextResponse.json(err("VALIDATION_FAILED", "Validation failed.", meta(guard.requestId, MOD), { field_errors: fieldErrors }), { status: 422 });\n') if validator else ''
    return (
        'import { NextRequest, NextResponse } from "next/server";\n'
        f'{gimport}\n{svc_imports}\n'
        'import { ok, err, meta } from "@/server/http/envelope";\n\n'
        f'const MOD = {json.dumps(mod)};\n\n'
        'export async function GET(request: NextRequest) {\n'
        f'  const guard = {gget};\n'
        '  if (!guard.ok) return NextResponse.json(guard.body, { status: guard.status });\n'
        f'  const data = await {L["service"]}({list_arg});\n'
        '  return NextResponse.json(ok(data, meta(guard.requestId, MOD)));\n'
        '}\n\n'
        'export async function POST(request: NextRequest) {\n'
        f'  const guard = {gpost};\n'
        '  if (!guard.ok) return NextResponse.json(guard.body, { status: guard.status });\n'
        f'{school_check}'
        '  let body: Record<string, unknown>;\n'
        '  try { body = (await request.json()) as Record<string, unknown>; } catch { body = {}; }\n'
        f'{validate_step}'
        f'  const result = {create_call};\n'
        '  if ("error" in result) return NextResponse.json(err(result.error.code, result.error.message, meta(guard.requestId, MOD), result.error.field_errors ? { field_errors: result.error.field_errors } : undefined), { status: result.error.status });\n'
        '  return NextResponse.json(ok(result.data, meta(guard.requestId, MOD)));\n'
        '}\n'
    )


# ---- kind: view -------------------------------------------------------------------------------------
# A read-only GET whose kernel op may deny (returns { data } | { error: {code,message,status} }) — e.g. a
# gated list (finance/release gates). guard -> op(actor, searchParams) -> envelope or the op's error.

def emit_view(spec):
    portal, mod, svc, imp = spec["portal"], spec["module"], spec["service"], spec["importFrom"]
    if portal == "school":
        gimport = 'import { requireSchoolScope } from "@/server/guards/requireSchoolScope";'
        gcall = f'await requireSchoolScope(request, {json.dumps(mod)})'
    else:
        gimport = 'import { requireStaffScope } from "@/server/guards/requireStaffScope";'
        gcall = f'await requireStaffScope(request, {json.dumps(mod)}, "read")'
    return ('import { NextRequest, NextResponse } from "next/server";\n'
            f'{gimport}\n'
            f'import {{ {svc} }} from "{imp}";\n'
            'import { ok, err, meta } from "@/server/http/envelope";\n\n'
            'export async function GET(request: NextRequest) {\n'
            f'  const guard = {gcall};\n'
            '  if (!guard.ok) return NextResponse.json(guard.body, { status: guard.status });\n'
            f'  const result = await {svc}(guard.actor, request.nextUrl.searchParams);\n'
            f'  if ("error" in result) return NextResponse.json(err(result.error.code, result.error.message, meta(guard.requestId, {json.dumps(mod)})), {{ status: result.error.status }});\n'
            f'  return NextResponse.json(ok(result.data, meta(guard.requestId, {json.dumps(mod)})));\n'
            '}\n')


# ---- kind: detail -----------------------------------------------------------------------------------
# GET one record by [id], scoped: guard -> op(scope, id) -> { data } | { error } (e.g. NOT_FOUND on a
# cross-school id, no leak). The op fetches + scope-checks + any sub-records.

def emit_detail(spec):
    portal, mod, svc, imp = spec["portal"], spec["module"], spec["service"], spec["importFrom"]
    if portal == "school":
        gimport = 'import { requireSchoolScope } from "@/server/guards/requireSchoolScope";'
        gcall = f'await requireSchoolScope(request, {json.dumps(mod)})'
        scope_arg = 'guard.actor.school_id ?? ""'
    else:
        gimport = 'import { requireStaffScope } from "@/server/guards/requireStaffScope";'
        gcall = f'await requireStaffScope(request, {json.dumps(mod)}, "read")'
        scope_arg = "guard.actor"
    return ('import { NextRequest, NextResponse } from "next/server";\n'
            f'{gimport}\n'
            f'import {{ {svc} }} from "{imp}";\n'
            'import { ok, err, meta } from "@/server/http/envelope";\n\n'
            'export async function GET(request: NextRequest, ctx: { params: Promise<{ id: string }> }) {\n'
            '  const { id } = await ctx.params;\n'
            f'  const guard = {gcall};\n'
            '  if (!guard.ok) return NextResponse.json(guard.body, { status: guard.status });\n'
            f'  const result = await {svc}({scope_arg}, id);\n'
            f'  if ("error" in result) return NextResponse.json(err(result.error.code, result.error.message, meta(guard.requestId, {json.dumps(mod)})), {{ status: result.error.status }});\n'
            f'  return NextResponse.json(ok(result.data, meta(guard.requestId, {json.dumps(mod)})));\n'
            '}\n')


# ---- kind: module_item ------------------------------------------------------------------------------
# A module item route that re-exports the generic kernel item handlers (GET/PATCH) over a module service.

def emit_module_item(spec):
    return (f'import {{ makeStaffItemHandlers }} from "@/server/lib/routeHandlers";\n'
            f'import * as service from "{spec["servicePath"]}";\n\n'
            f'export const {{ {spec.get("methods", "GET, PATCH")} }} = makeStaffItemHandlers({json.dumps(spec["module"])}, service);\n')


KINDS = {"lookup": emit_lookup, "aggregate": emit_aggregate, "create": emit_create, "view": emit_view,
         "detail": emit_detail, "module_item": emit_module_item}


def main():
    count = 0
    for sf in sorted(SPECS.glob("*.json")):
        spec = json.loads(sf.read_text(encoding="utf-8"))
        kind = spec.get("kind")
        if kind not in KINDS:
            print(f"  SKIP {sf.name}: unknown kind {kind!r}", file=sys.stderr)
            continue
        body = KINDS[kind](spec)
        out = APP / Path(*spec["path"].split("/")) / "route.ts"
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(header(sf.name) + body, encoding="utf-8")
        count += 1
    print(f"endpoints generated: {count}")


if __name__ == "__main__":
    main()
