#!/usr/bin/env python3
"""Rule-catalog compiler (foundation, P0.14 / spec/rules/RULE_TAXONOMY.md). The build-time "rule engine":
reads each module's declarative rules from spec/rules/<module>.rules.json and emits per-module enforcement
into app/server/rules/<module>.generated.ts (GENERATED bucket). Generated wiring (and, during burn-down,
still-hand-written routes) call these instead of inlining judgment.

NOT a runtime engine — rules are data, this is a compiler, enforcement is generated/type-checked/drift-gated.
This pilot compiles the `validation` type (condition: required_nonempty); other types/conditions extend here.
Distinct from gen_rls.py (which generates Postgres RLS). Run from the repo root: python _validation/gen_rules.py
"""
import json, sys
from pathlib import Path

SPECS = Path("versa-oms/spec/rules")
OUT = Path("versa-oms/app/server/rules")


def pascal(s):
    return "".join(p.capitalize() for p in s.split("_"))


# condition -> a TS boolean expression that is TRUE when the rule is VIOLATED (so we push the error).
def violated_expr(field, condition, params):
    if condition == "required_nonempty":
        return f'!String(body[{json.dumps(field)}] ?? "").trim()'
    raise SystemExit(f"gen_rules: unsupported validation condition {condition!r} (extend gen_rules.py)")


def emit_validators(module, rules):
    by_action = {}
    for r in rules:
        if r["type"] != "validation" or not r.get("enabled", True):
            continue
        by_action.setdefault(r["action"], []).append(r)
    if not by_action:
        return None
    lines = [f"// GENERATED by gen_rules.py from spec/rules/{module}.rules.json — DO NOT EDIT. Edit the rules + regenerate.",
             "// Compiled validation rules (spec/rules/RULE_TAXONOMY.md). Each validate* returns the field errors,",
             "// in declaration order; the calling route wraps them in a VALIDATION_FAILED envelope.",
             "export type FieldError = { field: string; message: string };", ""]
    for action, rs in by_action.items():
        fn = f"validate{pascal(module)}_{action}"
        lines.append(f"export function {fn}(body: Record<string, unknown>): FieldError[] {{")
        lines.append("  const errors: FieldError[] = [];")
        for r in rs:
            w = r["when"]; err = r["then"]["error"]
            cond = violated_expr(w["field"], w["condition"], w.get("params", {}))
            lines.append(f"  if ({cond}) errors.push({{ field: {json.dumps(err['field'])}, message: {json.dumps(err['message'])} }}); // {r['id']}")
        lines.append("  return errors;")
        lines.append("}")
        lines.append("")
    return "\n".join(lines)


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    count = 0
    for sf in sorted(SPECS.glob("*.rules.json")):
        spec = json.loads(sf.read_text(encoding="utf-8"))
        module = spec["_meta"]["module"]
        ts = emit_validators(module, spec.get("rules", []))
        if ts:
            (OUT / f"{module}.generated.ts").write_text(ts, encoding="utf-8")
            count += 1
    print(f"rules compiled: {count} module(s)")


if __name__ == "__main__":
    main()
