#!/usr/bin/env python3
"""Generate the LEAK-CRITICAL school-scope map (app/server/lookups/schoolScope.generated.ts) FROM the rule
catalog's scoping rules (unified). Each scoping rule carries the per-table strategy (direct/path/junction/none)
in `then.strategy`; this reads them and emits the SCHOOL_SCOPE map. The strategy is DERIVED into the catalog by
derive_rule_catalog.derive_scope_map — so this must run AFTER it. Run from the repo root.
"""
import json
from pathlib import Path

CAT = Path("versa-oms/reports/rule_catalog.derived.json")
OUT = Path("versa-oms/app/server/lookups/schoolScope.generated.ts")


def main():
    cat = json.loads(CAT.read_text(encoding="utf-8"))["rules"]
    scope = {r["entity"]: r["then"]["strategy"] for r in cat if r["type"] == "scoping"}
    lines = [
        "// GENERATED by _validation/gen_school_scope.py from the rule catalog (scoping rules) — DO NOT EDIT.",
        "// How /api/school/lookup scopes each FK-target table to the authenticated school (no cross-school leak).",
        "export type SchoolScope =",
        '  | { kind: "direct" }',
        '  | { kind: "path"; hops: { via: string; parent: string }[] }',
        '  | { kind: "junction"; junction: string; fk: string }',
        '  | { kind: "none" };',
        "export const SCHOOL_SCOPE: Record<string, SchoolScope> = {",
    ]
    for tbl in sorted(scope):
        lines.append(f"  {json.dumps(tbl)}: {json.dumps(scope[tbl])},")
    lines += ["};", ""]
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"schoolScope.generated.ts: {len(scope)} FK-target tables (from the catalog)")


if __name__ == "__main__":
    main()
