#!/usr/bin/env python3
"""Generate page SHELLS (app/app/<path>/page.tsx) from spec/pages/*.json. A shell is a thin server component
that renders ONE client view component; the interactive UI lives in the hand-written component (the JobsView
pattern — the design-system usage layer). So there are NO hand-written pages: the page is generated wiring,
the view is a governed component. Run from the repo root.
"""
import json
from pathlib import Path

SPECS = Path("versa-oms/spec/pages")
APP = Path("versa-oms/app/app")


def main():
    n = 0
    for sp in sorted(SPECS.glob("*.json")):
        s = json.loads(sp.read_text(encoding="utf-8"))
        out = APP / s["path"] / "page.tsx"
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(
            f'// GENERATED by gen_pages.py from spec/pages/{sp.name} — DO NOT EDIT. Edit the spec/component + regenerate.\n'
            f'import {{ {s["component"]} }} from "{s["importFrom"]}";\n\n'
            'export default function Page() {\n'
            f'  return <{s["component"]} />;\n'
            '}\n', encoding="utf-8")
        n += 1
    print(f"page shells generated: {n}")


if __name__ == "__main__":
    main()
