#!/usr/bin/env python3
"""Rule-catalog COMPILER (gen_rules). Compiles enforcement from the DERIVED catalog
(reports/rule_catalog.derived.json, produced by derive_rule_catalog.py from canonical/workflows) — NOT from
hand-authored rules. For every entity+action a founder has reviewed (a spec/rules/judgment/<module>.judgment.json
exists), it compiles the derived `validation` rules MINUS the `server_set` fields the judgment excludes, into
app/server/rules/<entity>.generated.ts.

So the rule layer is DERIVED (canonical -> catalog) + a small founder-signed JUDGMENT (server_set) — never
hand-typed (DERIVE-DON'T-AUTHOR, P0.14). Distinct from gen_rls.py (Postgres RLS). Run from the repo root.
"""
import json, sys
from pathlib import Path

CATALOG = Path("versa-oms/reports/rule_catalog.derived.json")
JUDGMENT_DIR = Path("versa-oms/spec/rules/judgment")
OUT = Path("versa-oms/app/server/rules")


def pascal(s):
    return "".join(p.capitalize() for p in s.split("_"))


def violated_expr(field, condition, params):
    f = json.dumps(field)
    if condition == "required_nonempty":
        return f'!String(body[{f}] ?? "").trim()'
    if condition == "enum":
        vals = json.dumps(params.get("values", []))
        return f'body[{f}] !== undefined && body[{f}] !== null && !{vals}.includes(String(body[{f}]))'
    raise SystemExit(f"gen_rules: unsupported validation condition {condition!r} (extend gen_rules.py)")


def main():
    if not CATALOG.exists():
        raise SystemExit("gen_rules: run derive_rule_catalog.py first (no derived catalog)")
    OUT.mkdir(parents=True, exist_ok=True)
    catalog = json.loads(CATALOG.read_text(encoding="utf-8"))["rules"]
    by_ea = {}
    for r in catalog:
        if r["type"] == "validation":
            by_ea.setdefault((r["entity"], r["action"]), []).append(r)

    count = 0
    for jf in sorted(JUDGMENT_DIR.glob("*.judgment.json")):
        j = json.loads(jf.read_text(encoding="utf-8"))
        per_entity = {}
        for entity, actions in j.get("server_set", {}).items():
            for action, conf in actions.items():
                excluded = set(conf.get("fields", []))
                seen, emitted = set(), []
                for r in by_ea.get((entity, action), []):
                    field, cond = r["when"]["field"], r["when"]["condition"]
                    if field in excluded or (field, cond) in seen:
                        continue
                    seen.add((field, cond))
                    emitted.append(r)
                if emitted:
                    per_entity.setdefault(entity, []).append((action, emitted))
        for entity, actions in per_entity.items():
            lines = ["// GENERATED by gen_rules.py — DO NOT EDIT. Compiled from reports/rule_catalog.derived.json",
                     f"// (derived from canonical) MINUS server_set in spec/rules/judgment/{jf.name}. Edit canonical/judgment + regenerate.",
                     "export type FieldError = { field: string; message: string };", ""]
            for action, rules in actions:
                lines.append(f"export function validate{pascal(entity)}_{action}(body: Record<string, unknown>): FieldError[] {{")
                lines.append("  const errors: FieldError[] = [];")
                for r in rules:
                    w, err = r["when"], r["then"]["error"]
                    lines.append(f"  if ({violated_expr(w['field'], w['condition'], w.get('params', {}))}) "
                                 f"errors.push({{ field: {json.dumps(err['field'])}, message: {json.dumps(err['message'])} }}); // {r['id']}")
                lines += ["  return errors;", "}", ""]
            (OUT / f"{entity}.generated.ts").write_text("\n".join(lines), encoding="utf-8")
            count += 1
    print(f"rules compiled: {count} entity enforcement file(s)")


if __name__ == "__main__":
    main()
