// GENERATED by gen_endpoints.py from spec/endpoints/school_materials.json — DO NOT EDIT. Edit the spec + regenerate.
import { NextRequest, NextResponse } from "next/server";
import { requireSchoolScope } from "@/server/guards/requireSchoolScope";
import { listSchoolMaterials } from "@/server/materials/schoolMaterials";
import { ok, err, meta } from "@/server/http/envelope";

export async function GET(request: NextRequest) {
  const guard = await requireSchoolScope(request, "school_materials");
  if (!guard.ok) return NextResponse.json(guard.body, { status: guard.status });
  const result = await listSchoolMaterials(guard.actor, request.nextUrl.searchParams);
  if ("error" in result) return NextResponse.json(err(result.error.code, result.error.message, meta(guard.requestId, "school_materials")), { status: result.error.status });
  return NextResponse.json(ok(result.data, meta(guard.requestId, "school_materials")));
}
