// GENERATED by gen_routes (Robot 6) — DO NOT EDIT.
import { getSchoolUsers, updateSchoolUsers } from "@/services/school_users.service";
import { ok, err } from "@/runtime/envelope";

export async function GET(_req: Request, { params }: { params: { id: string } }) {
  const row = await getSchoolUsers(params.id);
  return row ? ok(row) : err("NOT_FOUND", 404, "school_users not found");
}

export async function PATCH(req: Request, { params }: { params: { id: string } }) {
  return ok(await updateSchoolUsers(params.id, await req.json()));
}
