// GENERATED by gen_pages.py from spec/pages/school_support_page.json — DO NOT EDIT. Edit the spec/component + regenerate.
import { SchoolSupportView } from "@/components/SchoolSupportView";

export default function Page() {
  return <SchoolSupportView />;
}
