// GENERATED by gen_routes (Robot 6) — DO NOT EDIT.
import { getAwards, updateAwards, deleteAwards } from "@/services/awards.service";
import { ok, err } from "@/runtime/envelope";

export async function GET(_req: Request, { params }: { params: { id: string } }) {
  const row = await getAwards(params.id);
  return row ? ok(row) : err("NOT_FOUND", 404, "awards not found");
}

export async function PATCH(req: Request, { params }: { params: { id: string } }) {
  return ok(await updateAwards(params.id, await req.json()));
}

export async function DELETE(_req: Request, { params }: { params: { id: string } }) {
  return ok(await deleteAwards(params.id));
}
