// GENERATED by _validation/gen_modules.py — DO NOT EDIT.
import { NextRequest, NextResponse } from "next/server";
import { requireStaffScope } from "@/server/guards/requireStaffScope";
import { ok, err, meta } from "@/server/http/envelope";
import { ValidationError } from "@/server/lib/defineModule";
import { listChildRecords } from "@/server/lib/listChild";

export async function GET(request: NextRequest, ctx: { params: Promise<{ id: string }> }) {
  const guard = await requireStaffScope(request, "exam_material_ops_files", "read");
  if (!guard.ok) return NextResponse.json(guard.body, { status: guard.status });
  const { id } = await ctx.params;
  return NextResponse.json(ok(await listChildRecords("exam_material_download_events", "material_file_id", id, guard.actor), meta(guard.requestId, "exam_material_ops_files")));
}
