// GENERATED by gen_endpoints.py from spec/endpoints/staff_jobs.json — DO NOT EDIT. Edit the spec + regenerate.
import { NextRequest, NextResponse } from "next/server";
import { requireStaffScope } from "@/server/guards/requireStaffScope";
import { listJobRunsView } from "@/server/jobs/runner";
import { ok, meta } from "@/server/http/envelope";

export async function GET(request: NextRequest) {
  const guard = await requireStaffScope(request, "task_work_queue", "read");
  if (!guard.ok) return NextResponse.json(guard.body, { status: guard.status });
  const data = await listJobRunsView();
  return NextResponse.json(ok(data, meta(guard.requestId, "task_work_queue")));
}
