// GENERATED by gen_routes (Robot 6) — DO NOT EDIT.
import { getAuditEvents, updateAuditEvents } from "@/services/audit_events.service";
import { ok, err } from "@/runtime/envelope";

export async function GET(_req: Request, { params }: { params: { id: string } }) {
  const row = await getAuditEvents(params.id);
  return row ? ok(row) : err("NOT_FOUND", 404, "audit_events not found");
}

export async function PATCH(req: Request, { params }: { params: { id: string } }) {
  return ok(await updateAuditEvents(params.id, await req.json()));
}
