// GENERATED by gen_routes (Robot 6) — DO NOT EDIT.
import { getExamMaterials, updateExamMaterials } from "@/services/exam_materials.service";
import { ok, err } from "@/runtime/envelope";

export async function GET(_req: Request, { params }: { params: { id: string } }) {
  const row = await getExamMaterials(params.id);
  return row ? ok(row) : err("NOT_FOUND", 404, "exam_materials not found");
}

export async function PATCH(req: Request, { params }: { params: { id: string } }) {
  return ok(await updateExamMaterials(params.id, await req.json()));
}
