// GENERATED by gen_routes (Robot 6) — DO NOT EDIT.
import { getOlympiads, updateOlympiads } from "@/services/olympiads.service";
import { ok, err } from "@/runtime/envelope";

export async function GET(_req: Request, { params }: { params: { id: string } }) {
  const row = await getOlympiads(params.id);
  return row ? ok(row) : err("NOT_FOUND", 404, "olympiads not found");
}

export async function PATCH(req: Request, { params }: { params: { id: string } }) {
  return ok(await updateOlympiads(params.id, await req.json()));
}
