import { ModuleTable } from "@/components/ModuleTable";

export default function Page() {
  return (
    <ModuleTable
      title="School Onboarding"
      eyebrow="staff \u00b7 school_onboarding_ops"
      endpoint="/api/staff/schools/onboarding"
      columns={[{"key": "onboarding_code", "label": "Onboarding"}, {"key": "source_type", "label": "Source Type"}, {"key": "school_name", "label": "School Name"}, {"key": "board", "label": "Board"}, {"key": "onboarding_status", "label": "Status"}]}
      description="Review and activate schools so they can register students and book exams."
      breadcrumbs={[{"label": "Staff", "href": "/staff/dashboard"}, {"label": "Schools", "href": "/staff/schools"}, {"label": "Onboarding"}]}
      nextAction="\u2192 Use \u201cNew School Onboarding\u201d to add one, then act on it from the list."
      statusKey="onboarding_status"
      moduleId="school_onboarding_ops"
      createFields={[{"key": "source_type", "label": "Source Type", "type": "select", "options": [{"value": "crm_conversion", "label": "CRM Conversion"}, {"value": "direct_staff_created", "label": "Direct Staff Created"}, {"value": "school_self_submitted", "label": "School Self Submitted"}, {"value": "migration", "label": "Migration"}]}, {"key": "source_lead_id", "label": "Source Lead", "type": "reference", "refTable": "school_leads"}, {"key": "school_id", "label": "School", "type": "reference", "refTable": "schools"}, {"key": "school_name", "label": "School Name", "type": "text"}, {"key": "board", "label": "Board", "type": "text"}, {"key": "address", "label": "Address", "type": "text"}, {"key": "city", "label": "City", "type": "text"}, {"key": "state", "label": "State", "type": "text"}, {"key": "country", "label": "Country", "type": "text"}, {"key": "website", "label": "Website", "type": "text"}, {"key": "coordinator_name", "label": "Coordinator Name", "type": "text"}, {"key": "coordinator_email", "label": "Coordinator Email", "type": "text"}, {"key": "coordinator_phone", "label": "Coordinator Phone", "type": "text"}, {"key": "assigned_reviewer_id", "label": "Assigned Reviewer", "type": "reference", "refTable": "staff_profiles"}, {"key": "assigned_approver_id", "label": "Assigned Approver", "type": "reference", "refTable": "staff_profiles"}, {"key": "approval_note", "label": "Approval Note", "type": "text"}, {"key": "rejection_reason", "label": "Rejection Reason", "type": "text"}, {"key": "block_reason", "label": "Block Reason", "type": "text"}, {"key": "sla_due_at", "label": "SLA Due At", "type": "date"}, {"key": "approved_at", "label": "Approved At", "type": "date"}, {"key": "activated_at", "label": "Activated At", "type": "date"}]}
      actions={[{"action": "submit", "label": "Submit", "variant": "light"}, {"action": "start_review", "label": "Start review", "variant": "blue"}, {"action": "approve", "label": "Approve", "variant": "blue", "reason": true}, {"action": "reject", "label": "Reject", "variant": "light", "reason": true, "danger": true}, {"action": "activate", "label": "Activate", "variant": "blue"}, {"action": "block", "label": "Block", "variant": "light", "reason": true, "danger": true}, {"action": "suspend", "label": "Suspend", "variant": "light", "reason": true, "danger": true}, {"action": "archive", "label": "Archive", "variant": "light", "reason": true, "danger": true}]}
      detailPanels={[{"key": "documents", "label": "Documents", "subPath": "documents", "listColumns": ["review_status", "document_type", "review_note", "reviewed_at"], "addFields": [{"key": "document_type", "label": "Document type", "type": "select", "required": true, "options": ["authorization_letter", "school_id_proof", "coordinator_id_proof_optional", "other"]}, {"key": "review_note", "label": "Note", "type": "textarea"}], "editFields": [{"key": "review_status", "label": "Decision", "type": "select", "required": true, "options": ["under_review", "accepted", "rejected"]}, {"key": "review_note", "label": "Review note", "type": "textarea"}]}, {"key": "events", "label": "Events", "subPath": "events", "listColumns": ["event_code", "previous_status", "new_status", "reason"]}, {"key": "status-controls", "label": "Status Controls", "subPath": "status-controls", "listColumns": ["control_status", "control_type", "reason", "applied_at"]}]}
      toolbar={{"facet": {"key": "onboarding_status", "options": [{"value": "draft", "label": "Draft"}, {"value": "submitted", "label": "Submitted"}, {"value": "under_review", "label": "Under Review"}, {"value": "needs_more_info", "label": "Needs More Info"}, {"value": "approved", "label": "Approved"}, {"value": "rejected", "label": "Rejected"}, {"value": "activated", "label": "Activated"}, {"value": "blocked", "label": "Blocked"}, {"value": "suspended", "label": "Suspended"}, {"value": "archived", "label": "Archived"}]}, "search": true, "sort": [{"value": "created_at:desc", "label": "Newest"}]}}
    />
  );
}
