// GENERATED by gen_routes (Robot 6) — DO NOT EDIT.
import { getSchoolSettings, updateSchoolSettings, deleteSchoolSettings } from "@/services/school_settings.service";
import { ok, err } from "@/runtime/envelope";

export async function GET(_req: Request, { params }: { params: { id: string } }) {
  const row = await getSchoolSettings(params.id);
  return row ? ok(row) : err("NOT_FOUND", 404, "school_settings not found");
}

export async function PATCH(req: Request, { params }: { params: { id: string } }) {
  return ok(await updateSchoolSettings(params.id, await req.json()));
}

export async function DELETE(_req: Request, { params }: { params: { id: string } }) {
  return ok(await deleteSchoolSettings(params.id));
}
