#!/usr/bin/env python3
"""derive_deferred — PROJECT the parked backlog into ONE checklist. The single place to see what's deferred + how
to resume it. Aggregates source-of-truth/v2_supplement/security.json (auth-last · DPDP enforcement · hardening) +
the framework backlog. Writes spec/derived/deferred.json (gated by check_generated) + reports/DEFERRED.md (human).
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SEC = ROOT / "source-of-truth" / "v2_supplement" / "security.json"
OUTJ = ROOT / "spec" / "derived" / "deferred.json"
OUTMD = ROOT / "reports" / "DEFERRED.md"

FRAMEWORK = [
    "auto-write the remaining ladder step types (action/entry/new-field) into source once trusted (apply_annotations extension)",
    "bidirectional trace graph (requirement ↔ source ↔ generated file ↔ test)",
    "golden-output snapshot tests for generators",
    "questions⇄gates duality meta-gate",
]


def main():
    sec = json.loads(SEC.read_text(encoding="utf-8")) if SEC.exists() else {}
    groups = [
        ("auth_last", "Auth-last — wire auth → these light up", "prompt: \"wire auth\" (or \"resume the auth-last security items\")",
         sec.get("deferred_auth_last", [])),
        ("dpdp_enforcement", "DPDP enforcement — NOT auth-gated, do anytime", "prompt: \"do the DPDP consent-enforcement\"",
         sec.get("privacy", {}).get("deferred_enforcement", [])),
        ("hardening", "Hardening backlog", "prompt: \"work the security hardening backlog\"",
         sec.get("hardening_backlog", [])),
        ("framework", "Framework / annotation ladder", "prompt: \"apply the <step> annotations to source\" or a specific item",
         FRAMEWORK),
    ]

    data = {"_robot": "derive_deferred", "groups": {k: items for k, _t, _p, items in groups}}
    OUTJ.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

    total = sum(len(items) for _k, _t, _p, items in groups)
    L = ["# DEFERRED — the parked backlog (one place to check)", "",
         f"**{total} deferred items.** _Generated by `derive_deferred` from `source-of-truth/v2_supplement/security.json` "
         "(+ framework). This is the single checklist; to resume a group, use the prompt shown under it._", ""]
    for _k, title, prompt, items in groups:
        L.append(f"## {title}  ({len(items)})")
        L.append(f"_{prompt}_")
        L.append("")
        for it in items:
            L.append(f"- [ ] {it}")
        L.append("")
    OUTMD.parent.mkdir(parents=True, exist_ok=True)
    OUTMD.write_text("\n".join(L) + "\n", encoding="utf-8")
    print(f"derive_deferred: {total} deferred item(s) -> {OUTMD.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
