#!/usr/bin/env python3
"""derive_journey_map — the LIVING journey map. Projects the domain-stage map (source) against the ACTUAL journeys
+ entities, so it stays true as we build (same source->derive mechanism as derive_annotations).

Reads  source-of-truth/v2_supplement/journey_map.json   (domain stages x entity x staff/school journey x state)
       spec/{staff,school,public}_journeys.json          (actual journeys — to verify + detect drift)
       spec/derived/data_model.json                      (entities — to verify)
Writes reports/JOURNEY_MAP.md                            (the readable map, regenerated every build)
       spec/derived/journey_map.json                     (computed status — gated by check_generated)

Auto-updates: map a stage's journey + set state in source -> it flips here. A declared journey that doesn't exist =
DRIFT (flagged). A journey not mapped to any stage = UNMAPPED (flagged) so coverage can't silently rot.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SRC = ROOT / "source-of-truth" / "v2_supplement" / "journey_map.json"
DM = ROOT / "spec" / "derived" / "data_model.json"
OUTMD = ROOT / "reports" / "JOURNEY_MAP.md"
OUTJ = ROOT / "spec" / "derived" / "journey_map.json"
ICON = {"done": "✅", "partial": "🟡", "gap": "⛔", "deferred": "🔒"}


def all_journeys():
    ids = {}
    for fn in ("staff_journeys", "school_journeys", "public_journeys"):
        p = ROOT / "spec" / f"{fn}.json"
        if p.exists():
            for j in json.loads(p.read_text(encoding="utf-8")).get("journeys", []):
                ids[j["id"]] = fn.split("_")[0]
    return ids


def main():
    data = json.loads(SRC.read_text(encoding="utf-8"))
    stages, phases, extra = data["stages"], data.get("phases", {}), data.get("extra", {})
    jids = all_journeys()
    entities = set(json.loads(DM.read_text(encoding="utf-8")).get("entities", {}))

    mapped, drift = set(), []
    for s in stages:
        for key in ("staff", "school", "public"):
            jid = s.get(key)
            if jid:
                mapped.add(jid)
                if jid not in jids:
                    drift.append(f"{s['id']} ({s['stage']}): declared {key} `{jid}` does not exist")
        for jid in extra.get(s["id"], []):
            mapped.add(jid)
        if s.get("entity") and s["entity"] not in entities:
            drift.append(f"{s['id']}: entity `{s['entity']}` not in canonical")
    unmapped = [j for j in jids if j not in mapped]

    counts = {k: sum(1 for s in stages if s["state"] == k) for k in ICON}
    total = len(stages)

    L = ["# Journey map — olympiad operations (living)", "",
         f"_Generated by `derive_journey_map` from `source-of-truth/v2_supplement/journey_map.json` — regenerated "
         f"every build. **{counts['done']}/{total} done · {counts['partial']} partial · {counts['gap']} gap · "
         f"{counts['deferred']} deferred.** Update a stage's journey + state in source as we build; it reflects here._", ""]
    if drift:
        L += ["> ⚠️ **DRIFT** (source claims a journey/entity that doesn't exist):"] + [f"> - {d}" for d in drift] + [""]
    if unmapped:
        L += [f"> ℹ️ **Unmapped journeys** (built but not tied to a stage — map them in source): {', '.join(unmapped)}", ""]

    for ph, label in phases.items():
        ph_stages = [s for s in stages if s["phase"] == ph]
        if not ph_stages:
            continue
        L.append(f"## {label}")
        L.append("")
        L.append("| # | Stage | Entity | Staff | School / Public | Status |")
        L.append("|---|---|---|---|---|---|")
        for s in ph_stages:
            staff = s.get("staff") or "—"
            sch = s.get("school") or s.get("public") or "—"
            ex = extra.get(s["id"], [])
            if ex:
                staff = (staff + " +" + ",".join(ex)) if staff != "—" else "+" + ",".join(ex)
            L.append(f"| {s['id']} | {s['stage']} | {s.get('entity') or '—'} | {staff} | {sch} | {ICON.get(s['state'], s['state'])} {s['state']} |")
        L.append("")

    OUTMD.parent.mkdir(parents=True, exist_ok=True)
    OUTMD.write_text("\n".join(L) + "\n", encoding="utf-8")
    OUTJ.write_text(json.dumps({"_robot": "derive_journey_map", "counts": counts, "total": total,
                                "drift": drift, "unmapped": unmapped, "stages": stages}, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"derive_journey_map: {total} stages ({counts['done']} done / {counts['partial']} partial / {counts['gap']} gap / {counts['deferred']} deferred), {len(drift)} drift, {len(unmapped)} unmapped")


if __name__ == "__main__":
    main()
