#!/usr/bin/env python3
"""
================================================================================
ROBOT —  gen_fixtures   (test data, derived — NOT hardcoded)   (v2 pipeline)
================================================================================
WHAT IT DOES: Generates VALID sample records for every entity FROM THE CANONICAL,
so proofs/seeds never hand-hardcode field values. A schema change (e.g. adding
schools.pincode) auto-flows into the samples — zero proof edits, zero copied literals.

RULE (no-hardcoding): tests call sample("schools", { ...overrides }); the field values
come from the schema, not pasted literals. Required fields are filled with type/rule-valid
values (enum -> first value; "N-digit" -> N-digit number; email/mobile by name; etc.).
FK fields are NOT filled (the caller supplies real ids); status is left to the caller.

INPUT:  spec/derived/canonical.json
OUTPUT: spec/derived/fixtures.ts  (export function sample(entity, overrides))
RUN:    python versa-oms/generators/robots/gen_fixtures.py
================================================================================
"""
import json
from pathlib import Path

CANON = Path("versa-oms/spec/derived/canonical.json")
OUT = Path("versa-oms/spec/derived/fixtures.ts")
SKIP = {"id", "created_at", "updated_at", "status"}


def value_for(entity, f):
    name, typ, rule = f["name"], (f.get("type") or "string").lower(), (f.get("rule") or "").lower()
    if f.get("enum_values"):
        return f["enum_values"][0]
    import re
    md = re.search(r"(\d+)-digit", rule)
    if md:
        n = int(md.group(1))
        return "1" + "0" * (n - 1)            # a valid N-digit number (e.g. pincode -> 100000)
    if "email" in name:
        return f"{entity}.{name}@example.test"
    if "mobile" in name or "phone" in name or "contact" in name:
        return "9000000000"
    if typ in ("date",) or name.endswith("_date") or name.endswith("_at"):
        return "2026-01-01"
    if typ in ("timestamp",):
        return "2026-01-01T00:00:00Z"
    if typ in ("integer", "int", "number", "decimal"):
        return "100"
    if typ in ("boolean", "bool"):
        return True
    if "time" in name:
        return "10:00"
    return f"{entity}-{name}"


def main():
    entities = json.loads(CANON.read_text(encoding="utf-8"))["entities"]
    supp = json.loads(Path("versa-oms/source-of-truth/v2_supplement/data_model_supplement.json").read_text(encoding="utf-8"))
    auto = supp.get("generated_rules", {}).get("auto_identifier", {})  # e.g. {"students": "candidate_id"} — auto-generated, never seeded
    samples = {}
    for name, e in sorted(entities.items()):
        rec = {}
        for f in e["fields"]:
            if f["name"] in SKIP or f.get("references") or f["name"] == auto.get(name):  # skip system, status, FKs, auto-ids
                continue
            rec[f["name"]] = value_for(name, f)
        samples[name] = rec
    body = json.dumps(samples, indent=2)
    ts = ("// GENERATED by gen_fixtures from canonical.json — DO NOT EDIT. Valid sample records, no hardcoded literals.\n"
          "// Usage: sample(\"schools\", { status: \"lead\" })  — fills schema fields; you pass FKs/status/specific overrides.\n"
          f"const SAMPLES: Record<string, Record<string, unknown>> = {body};\n\n"
          "export function sample(entity: string, overrides: Record<string, unknown> = {}): Record<string, unknown> {\n"
          "  return { ...(SAMPLES[entity] || {}), ...overrides };\n}\n")
    OUT.write_text(ts, encoding="utf-8")
    print(f"gen_fixtures: sample() for {len(samples)} entities -> {OUT}")


if __name__ == "__main__":
    main()
