#!/usr/bin/env python3
"""
================================================================================
ROBOT 4 of 8  —  gen_db                                (v2 vibe-coding pipeline)
================================================================================
WHAT IT DOES (one line):
    Turns the build-ready canonical into real SQL: one CREATE TABLE per entity,
    with primary keys, typed columns, NOT NULL / enum CHECK constraints, and
    FOREIGN KEY constraints — emitted in dependency build-order so every FK
    target table exists first.

WHY IT MATTERS:
    The FK + CHECK constraints push the data model INTO the database itself. After
    this, the database PHYSICALLY CANNOT store a fake foreign key or a disconnected
    row — v1's invented `candidate_results` island would be rejected by Postgres,
    not just by a gate. Integrity stops being a promise and becomes a constraint.

WHERE IT SITS:
    canonical.json --> [gen_db] --> spec/derived/migrations/0001_schema.sql --> (applied to Postgres)
    First of the GEN robots (blueprint -> code).

INPUT:   versa-oms/spec/derived/canonical.json   (entities, fields, FKs, build_order)
OUTPUT:  versa-oms/spec/derived/migrations/0001_schema.sql

INTEGRITY — INVARIANTS:
    I1. DERIVED-ONLY. Every table/column/FK comes from canonical. No invented schema.
    I2. REFERENTIAL. Each FK field -> FOREIGN KEY REFERENCES <target>(id). The DB enforces it.
    I3. BUILD-ORDER. Tables emitted in canonical.build_order (referenced tables first) so the
        migration applies cleanly without forward references.
    I4. COLUMN RULES. "required"/primary_key -> NOT NULL; "unique" -> UNIQUE; enum + enum_values -> CHECK IN.
    I5. IDEMPOTENT. Same canonical -> byte-identical SQL.

AUTH-LAST NOTE:
    Row-Level Security (school_id scoping) is gen_db's responsibility too, but it depends on the auth
    context (current user's school), which is built LAST. So RLS is emitted in the AUTH phase as
    0002_rls.sql — NOT here. This file is the open, browsable schema (no RLS) so the portal can be
    checked freely during the build.

VERIFIED BY: check_generated (SQL matches canonical) + applying it to Postgres (it must apply cleanly;
    a forward-reference or bad FK would fail — proving I2/I3).
HOW TO RUN:  python versa-oms/generators/robots/gen_db.py
DO NOT: hand-edit the .sql; edit the source (BRD/supplement) -> re-run Robots 1,2,4.
STATUS: Robot 4/8. Emits the schema (tables + FKs + checks). RLS deferred to the auth phase (auth-last).
================================================================================
"""
import json
from pathlib import Path

CANON = Path("versa-oms/spec/derived/canonical.json")
OUT = Path("versa-oms/spec/derived/migrations/0001_schema.sql")

TYPE = {"uuid": "uuid", "text": "text", "string": "text", "enum": "text", "timestamp": "timestamptz",
        "datetime": "timestamptz", "date": "date", "integer": "integer", "int": "integer",
        "number": "numeric", "decimal": "numeric", "boolean": "boolean", "bool": "boolean",
        "json": "jsonb", "jsonb": "jsonb"}


def sqltype(t):
    return TYPE.get((t or "text").strip().lower().split()[0] if t else "text", "text")


def main():
    canon = json.loads(CANON.read_text(encoding="utf-8"))
    entities, order = canon["entities"], canon["build_order"]
    cat_path = Path("versa-oms/spec/derived/rule_catalog.json")
    catalog = json.loads(cat_path.read_text(encoding="utf-8")) if cat_path.exists() else {"workflows": {}}
    ent_states = {}  # entity -> its workflow states (handoff states are valid in the status CHECK too)
    for _wf, _w in catalog.get("workflows", {}).items():
        if _w.get("entity") and _w.get("states"):
            ent_states.setdefault(_w["entity"], set()).update(_w["states"])
    out = ["-- GENERATED by gen_db (Robot 4) from canonical.json — DO NOT EDIT. Edit the source + re-run.",
           "-- Tables in dependency build-order: every FK target exists before the table that references it.",
           "-- RLS (school scoping) is emitted later in the AUTH phase (0002_rls.sql), not here.", ""]
    fk_total = 0
    for name in order:
        e = entities[name]
        cols, fks = [], []
        for f in e["fields"]:
            # a FK column must match its target's key TYPE (all PKs are uuid 'id'); the BRD types FK fields
            # as "many-to-one X" which is a relationship, not a column type -> force uuid so the FK applies.
            col_type = "uuid" if f.get("references") else sqltype(f["type"])
            parts = [f'  "{f["name"]}" {col_type}']
            rule = (f.get("rule") or "").lower()
            if f.get("primary_key") or "required" in rule:
                parts.append("NOT NULL")
            if "unique" in rule:
                parts.append("UNIQUE")
            if f["type"] == "enum" and f.get("enum_values"):
                vals = sorted(set(f["enum_values"]) | ent_states.get(name, set())) if f["name"] == "status" else f["enum_values"]
                parts.append('CHECK ("%s" IN (%s))' % (f["name"], ", ".join("'%s'" % v for v in vals)))
            cols.append(" ".join(parts))
            if f.get("references"):
                fks.append(f'  FOREIGN KEY ("{f["name"]}") REFERENCES "{f["references"]}" ("id")')
                fk_total += 1
        body = cols + [f'  PRIMARY KEY ("{e["primary_key"]}")'] + fks
        out.append(f'CREATE TABLE "{name}" (')
        out.append(",\n".join(body))
        out.append(");\n")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(out), encoding="utf-8")
    print(f"gen_db: {len(order)} tables (build-order) · {fk_total} FOREIGN KEY constraints -> {OUT}")


if __name__ == "__main__":
    main()
