#!/usr/bin/env python3
"""
================================================================================
ROBOT 5 of 8  —  gen_services                          (v2 vibe-coding pipeline)
================================================================================
WHAT IT DOES (one line):
    Generates one TypeScript service per entity: typed CRUD + the lifecycle
    state-machine (allowed transitions from the rule catalog), so the table gets
    BEHAVIOUR that mechanically refuses illegal state changes.

WHERE IT SITS:
    canonical + rule_catalog --> [gen_services] --> spec/derived/services/<entity>.service.ts
                                                    --> gen_routes (Robot 6) wraps these as APIs
WHY IT MATTERS:
    A raw table lets any status be written to any value. A SERVICE enforces the
    workflow: `transition(id, action)` only succeeds if `current_status -> action`
    is a transition the BRD declared. Illegal jumps (e.g. lead -> students_open,
    skipping approval) are impossible — the state machine is generated, not trusted.

INPUT:
    versa-oms/spec/derived/canonical.json       (entities + fields)
    versa-oms/spec/derived/rule_catalog.json    (lifecycle transitions + validation rules)
OUTPUT:
    versa-oms/spec/derived/services/<entity>.service.ts   (one per entity)

INTEGRITY — INVARIANTS:
    I1. DERIVED-ONLY. CRUD fields come from canonical; transitions come from the catalog. No invention.
    I2. LIFECYCLE-ENFORCED. transition() rejects any action whose `from` != the row's current status
        (except the `any` wildcard). The allowed set is exactly the catalog's transitions for that entity.
    I3. VALIDATION-DELEGATED. create/update call validate<Entity>() — provided by gen_rules (Robot 7) —
        rather than re-typing validation here (one source for rules).
    I4. IDEMPOTENT. Same canonical+catalog -> byte-identical services.
    I5. THIN. The service is wiring over a frozen `db` kernel; no business judgment lives in hand code.

VERIFIED BY: check_module (each module's service is complete + its lifecycle matches the catalog) + tsc.
HOW TO RUN:  python versa-oms/generators/robots/gen_services.py
DO NOT: hand-edit the .ts; edit the BRD/catalog -> re-run Robots 1,2,3,5.
STATUS: Robot 5/8. CRUD + lifecycle. (Effect chains — what happens AFTER a transition — layer in once
    derive_catalog extracts the `effect` rule type; tracked in ROBOTS.md.)
================================================================================
"""
import json
import re
from pathlib import Path

CANON = Path("versa-oms/spec/derived/canonical.json")
CATALOG = Path("versa-oms/spec/derived/rule_catalog.json")
OUTDIR = Path("versa-oms/spec/derived/services")

TS = {"uuid": "string", "text": "string", "string": "string", "enum": "string", "timestamp": "string",
      "date": "string", "integer": "number", "int": "number", "number": "number", "decimal": "number",
      "boolean": "boolean", "json": "Record<string, unknown>", "jsonb": "Record<string, unknown>"}


def tstype(t):
    return TS.get((t or "text").strip().lower().split()[0] if t else "text", "string")


def pascal(s):
    return "".join(p.capitalize() for p in s.split("_"))


def entity_for_workflow(wf, entities):
    wfl = wf.lower()
    for e in sorted(entities, key=len, reverse=True):  # prefer the most specific name match
        if e.rstrip("s") in wfl:
            return e
    return None


def main():
    entities = json.loads(CANON.read_text(encoding="utf-8"))["entities"]
    catalog = json.loads(CATALOG.read_text(encoding="utf-8"))
    # map each entity -> its lifecycle transitions (via workflow name match)
    ent_trans = {n: [] for n in entities}
    for t in catalog["rules"]["lifecycle"]:
        e = entity_for_workflow(t["workflow"], entities)
        if e:
            ent_trans[e].append(t)

    OUTDIR.mkdir(parents=True, exist_ok=True)
    for name in sorted(entities):
        e = entities[name]
        P = pascal(name)
        # input type = the non-system, non-FK-only writable fields
        writable = [f for f in e["fields"] if f["name"] not in ("id", "created_at", "updated_at")]
        fieldlines = []
        for f in writable:
            opt = "" if ("required" in (f.get("rule") or "").lower() or f.get("primary_key")) else "?"
            fieldlines.append(f'  {f["name"]}{opt}: {tstype(f["type"])};')
        trans = ent_trans[name]
        tmap = ", ".join(f'{t["action"]}: {{ from: "{t["from"]}", to: "{t["to"]}" }}' for t in trans)

        ts = [f'// GENERATED by gen_services (Robot 5) from canonical + rule_catalog — DO NOT EDIT.',
              f'import {{ db }} from "../runtime/db";              // frozen data kernel',
              f'import {{ validate{P} }} from "../rules/{name}.rules"; // from gen_rules (Robot 7)', '',
              f'export type {P}Input = {{', *fieldlines, '};', '',
              f'export async function create{P}(input: {P}Input) {{',
              f'  const errors = validate{P}(input);',
              f'  if (errors.length) return {{ ok: false as const, errors }};',
              f'  return {{ ok: true as const, data: await db.insert("{name}", input) }};',
              f'}}', '',
              f'export async function get{P}(id: string) {{ return db.get("{name}", id); }}',
              f'export async function list{P}() {{ return db.list("{name}"); }}',
              f'export async function update{P}(id: string, patch: Partial<{P}Input>) {{ return db.update("{name}", id, patch); }}', '']
        if trans:
            ts += [f'// lifecycle state machine — only these transitions exist (from the BRD via the catalog)',
                   f'const TRANSITIONS = {{ {tmap} }} as const;',
                   f'export async function transition{P}(id: string, action: keyof typeof TRANSITIONS) {{',
                   f'  const row = await db.get("{name}", id) as {{ status?: string }};',
                   f'  const t = TRANSITIONS[action];',
                   f'  if (!t) throw new Error(`unknown action ${{action}} on {name}`);',
                   f'  if (t.from !== "any" && row.status !== t.from)',
                   f'    throw new Error(`illegal transition ${{action}}: {name} is "${{row.status}}", needs "${{t.from}}"`);',
                   f'  return db.update("{name}", id, {{ status: t.to }});',
                   f'}}', '']
        (OUTDIR / f"{name}.service.ts").write_text("\n".join(ts), encoding="utf-8")

    n_life = sum(1 for n in entities if ent_trans[n])
    print(f"gen_services: {len(entities)} services · {n_life} with an enforced lifecycle state-machine -> {OUTDIR}/")


if __name__ == "__main__":
    main()
