#!/usr/bin/env python3
"""
================================================================================
ROBOT 6 of 8  —  gen_routes                            (v2 vibe-coding pipeline)
================================================================================
WHAT IT DOES (one line):
    Wraps each entity's service (Robot 5) as real HTTP API routes — list/create,
    get/update, and lifecycle transition — every response in ONE standard
    envelope with the correct status code.

WHERE IT SITS:
    services (Robot 5) --> [gen_routes] --> spec/derived/routes/api/<entity>/...route.ts
                                            --> gen_screens (Robot 8) calls these from the UI
INPUT:   versa-oms/spec/derived/canonical.json   (entities + which have a lifecycle/status)
OUTPUT:  versa-oms/spec/derived/routes/api/<entity>/route.ts            (GET list, POST create)
         versa-oms/spec/derived/routes/api/<entity>/[id]/route.ts       (GET one, PATCH update)
         versa-oms/spec/derived/routes/api/<entity>/[id]/[action]/route.ts  (POST transition; lifecycle only)

INTEGRITY — INVARIANTS:
    I1. DERIVED-ONLY. One route per service operation; routes call the service, never the db. No logic here.
    I2. ONE ENVELOPE. Every response goes through ok()/err() — { ok, data } or { ok:false, code, errors }.
    I3. CORRECT STATUS. create=201, validation=422, not-found=404, illegal transition=409, else 200.
    I4. IDEMPOTENT. Same canonical -> byte-identical routes.
    I5. THIN. The route parses the request, calls the service, envelopes the result. Nothing else.

VERIFIED BY: check_generated (routes match services) + tsc + check_journey (the J1 HTTP path works end-to-end).
HOW TO RUN:  python versa-oms/generators/robots/gen_routes.py
DO NOT: put validation/lifecycle logic in a route — that lives in the service/rules. Edit source -> re-run.
STATUS: Robot 6/8. CRUD + transition routes. (Auth guards wrap these in the AUTH phase, last — auth-last.)
================================================================================
"""
import json
from pathlib import Path

CANON = Path("versa-oms/spec/derived/canonical.json")
OUTDIR = Path("versa-oms/spec/derived/routes/api")


def pascal(s):
    return "".join(p.capitalize() for p in s.split("_"))


def main():
    entities = json.loads(CANON.read_text(encoding="utf-8"))["entities"]
    n_routes = 0
    for name in sorted(entities):
        e = entities[name]
        P = pascal(name)
        has_status = any(f["name"] == "status" for f in e["fields"])
        svc = f'@/services/{name}.service'
        base = OUTDIR / name

        # collection: GET list, POST create
        (base).mkdir(parents=True, exist_ok=True)
        (base / "route.ts").write_text("\n".join([
            f'// GENERATED by gen_routes (Robot 6) — DO NOT EDIT.',
            f'import {{ list{P}, create{P} }} from "{svc}";',
            f'import {{ ok, err }} from "@/runtime/envelope";', '',
            f'export async function GET() {{ return ok(await list{P}()); }}', '',
            f'export async function POST(req: Request) {{',
            f'  const input = await req.json();',
            f'  const r = await create{P}(input);',
            f'  return r.ok ? ok(r.data, 201) : err("VALIDATION_FAILED", 422, r.errors);',
            f'}}', '']), encoding="utf-8")
        n_routes += 2

        # item: GET one, PATCH update
        (base / "[id]").mkdir(parents=True, exist_ok=True)
        (base / "[id]" / "route.ts").write_text("\n".join([
            f'// GENERATED by gen_routes (Robot 6) — DO NOT EDIT.',
            f'import {{ get{P}, update{P}, delete{P} }} from "{svc}";',
            f'import {{ ok, err }} from "@/runtime/envelope";', '',
            f'export async function GET(_req: Request, {{ params }}: {{ params: {{ id: string }} }}) {{',
            f'  const row = await get{P}(params.id);',
            f'  return row ? ok(row) : err("NOT_FOUND", 404, "{name} not found");',
            f'}}', '',
            f'export async function PATCH(req: Request, {{ params }}: {{ params: {{ id: string }} }}) {{',
            f'  return ok(await update{P}(params.id, await req.json()));',
            f'}}', '',
            f'export async function DELETE(_req: Request, {{ params }}: {{ params: {{ id: string }} }}) {{',
            f'  return ok(await delete{P}(params.id));',
            f'}}', '']), encoding="utf-8")
        n_routes += 2

        # transition route (lifecycle entities only)
        if has_status:
            (base / "[id]" / "[action]").mkdir(parents=True, exist_ok=True)
            (base / "[id]" / "[action]" / "route.ts").write_text("\n".join([
                f'// GENERATED by gen_routes (Robot 6) — DO NOT EDIT.',
                f'import {{ transition{P} }} from "{svc}";',
                f'import {{ ok, err }} from "@/runtime/envelope";', '',
                f'export async function POST(_req: Request, {{ params }}: {{ params: {{ id: string; action: string }} }}) {{',
                f'  try {{ return ok(await transition{P}(params.id, params.action as never)); }}',
                f'  catch (e) {{ return err("ILLEGAL_TRANSITION", 409, String((e as Error).message)); }}',
                f'}}', '']), encoding="utf-8")
            n_routes += 1

    print(f"gen_routes: {len(entities)} entities · {n_routes} route handlers -> {OUTDIR}/")


if __name__ == "__main__":
    main()
