// GENERATED by gen_pages.py from spec/pages/school_answer_sheets.json — DO NOT EDIT. Edit the spec/component + regenerate.
import { SchoolAnswerSheetsView } from "@/components/SchoolAnswerSheetsView";

export default function Page() {
  return <SchoolAnswerSheetsView />;
}
