// GENERATED by gen_routes (Robot 6) — DO NOT EDIT.
import { getStudents, updateStudents, deleteStudents } from "@/services/students.service";
import { ok, err } from "@/runtime/envelope";

export async function GET(_req: Request, { params }: { params: { id: string } }) {
  const row = await getStudents(params.id);
  return row ? ok(row) : err("NOT_FOUND", 404, "students not found");
}

export async function PATCH(req: Request, { params }: { params: { id: string } }) {
  return ok(await updateStudents(params.id, await req.json()));
}

export async function DELETE(_req: Request, { params }: { params: { id: string } }) {
  return ok(await deleteStudents(params.id));
}
