// GENERATED by gen_routes (Robot 6) — DO NOT EDIT.
import { getParticipations, updateParticipations } from "@/services/participations.service";
import { ok, err } from "@/runtime/envelope";

export async function GET(_req: Request, { params }: { params: { id: string } }) {
  const row = await getParticipations(params.id);
  return row ? ok(row) : err("NOT_FOUND", 404, "participations not found");
}

export async function PATCH(req: Request, { params }: { params: { id: string } }) {
  return ok(await updateParticipations(params.id, await req.json()));
}
