// GENERATED by gen_pages.py from spec/pages/staff_materials_upload.json — DO NOT EDIT. Edit the spec/component + regenerate.
import { MaterialsUploadView } from "@/components/MaterialsUploadView";

export default function Page() {
  return <MaterialsUploadView />;
}
