// GENERATED by gen_rules.py from the rule catalog — DO NOT EDIT. Edit canonical/judgment/eligibility + regenerate.
export type EligibilityResult = { eligible: boolean; reason?: string };

export function isEligiblePaymentLink_create(row: Record<string, unknown>): EligibilityResult {  // payment_link.create.eligible
  if (!(Number(row["student_count"] ?? 0) >= 1 && Number(row["unit_price"] ?? 0) > 0)) return { eligible: false, reason: "A payment link needs at least 1 student and a positive unit price." };
  return { eligible: true };
}
