// GENERATED by gen_rules.py from the rule catalog — DO NOT EDIT. Edit canonical/judgment/eligibility + regenerate.
export type FieldError = { field: string; message: string };

export function validateSupportTickets_create(body: Record<string, unknown>): FieldError[] {
  const errors: FieldError[] = [];
  if (!String(body["subject"] ?? "").trim()) errors.push({ field: "subject", message: "A subject is required." }); // support_tickets.create.subject_required
  if (!String(body["description"] ?? "").trim()) errors.push({ field: "description", message: "A description is required." }); // support_tickets.create.description_required
  return errors;
}
