// GENERATED by gen_rules.py from spec/rules/support_tickets.rules.json — DO NOT EDIT. Edit the rules + regenerate.
// Compiled validation rules (spec/rules/RULE_TAXONOMY.md). Each validate* returns the field errors,
// in declaration order; the calling route wraps them in a VALIDATION_FAILED envelope.
export type FieldError = { field: string; message: string };

export function validateSupportTickets_create(body: Record<string, unknown>): FieldError[] {
  const errors: FieldError[] = [];
  if (!String(body["subject"] ?? "").trim()) errors.push({ field: "subject", message: "A subject is required." }); // support_tickets.create.subject_required
  if (!String(body["description"] ?? "").trim()) errors.push({ field: "description", message: "A description is required." }); // support_tickets.create.description_required
  return errors;
}
