// GENERATED by gen_rules.py — DO NOT EDIT. Compiled from reports/rule_catalog.derived.json
// (derived from canonical) MINUS server_set in spec/rules/judgment/support_tickets.judgment.json. Edit canonical/judgment + regenerate.
export type FieldError = { field: string; message: string };

export function validateSupportTickets_create(body: Record<string, unknown>): FieldError[] {
  const errors: FieldError[] = [];
  if (!String(body["subject"] ?? "").trim()) errors.push({ field: "subject", message: "A subject is required." }); // support_tickets.create.subject_required
  if (!String(body["description"] ?? "").trim()) errors.push({ field: "description", message: "A description is required." }); // support_tickets.create.description_required
  return errors;
}
