// GENERATED by gen_routes (Robot 6) — DO NOT EDIT.
import { listStudyResources, createStudyResources } from "@/services/study_resources.service";
import { ok, err } from "@/runtime/envelope";

export async function GET() { return ok(await listStudyResources()); }

export async function POST(req: Request) {
  const input = await req.json();
  const r = await createStudyResources(input);
  return r.ok ? ok(r.data, 201) : err("VALIDATION_FAILED", 422, r.errors);
}
