// GENERATED by gen_endpoints.py from spec/endpoints/staff_crm_item.json — DO NOT EDIT. Edit the spec + regenerate.
import { makeStaffItemHandlers } from "@/server/lib/routeHandlers";
import * as service from "@/server/modules/school_crm/service";

export const { GET, PATCH } = makeStaffItemHandlers("school_crm", service);
