// GENERATED by _validation/gen_modules.py — DO NOT EDIT.
import { NextRequest, NextResponse } from "next/server";
import { requireStaffScope } from "@/server/guards/requireStaffScope";
import { ok, err, meta } from "@/server/http/envelope";
import { ValidationError } from "@/server/lib/defineModule";
import { listChildRecords } from "@/server/lib/listChild";
import { addChildRecord } from "@/server/lib/childWrite";

export async function GET(request: NextRequest, ctx: { params: Promise<{ id: string }> }) {
  const guard = await requireStaffScope(request, "school_onboarding_ops", "read");
  if (!guard.ok) return NextResponse.json(guard.body, { status: guard.status });
  const { id } = await ctx.params;
  return NextResponse.json(ok(await listChildRecords("school_onboarding_documents", "onboarding_case_id", id, guard.actor), meta(guard.requestId, "school_onboarding_ops")));
}

export async function POST(request: NextRequest, ctx: { params: Promise<{ id: string }> }) {
  const guard = await requireStaffScope(request, "school_onboarding_ops", "write");
  if (!guard.ok) return NextResponse.json(guard.body, { status: guard.status });
  const { id } = await ctx.params;
  let body: Record<string, unknown> = {};
  try { body = (await request.json()) as Record<string, unknown>; } catch { body = {}; }
  try {
    return NextResponse.json(ok(await addChildRecord("school_onboarding_documents", "onboarding_case_id", id, body, guard.actor, {"required": ["document_type"], "allowed": ["document_type", "review_note"], "actorColumn": "uploaded_by", "defaults": {"review_status": "uploaded"}, "module": "school_onboarding_ops"}), meta(guard.requestId, "school_onboarding_ops")), { status: 201 });
  } catch (e) {
    if (e instanceof ValidationError) return NextResponse.json(err("VALIDATION_FAILED", "Validation failed.", meta(guard.requestId, "school_onboarding_ops"), { field_errors: e.fieldErrors }), { status: 422 });
    return NextResponse.json(err("INTERNAL", "Unexpected error.", meta(guard.requestId, "school_onboarding_ops")), { status: 500 });
  }
}
