// GENERATED by gen_routes (Robot 6) — DO NOT EDIT.
import { listSchoolUsers, createSchoolUsers } from "@/services/school_users.service";
import { ok, err } from "@/runtime/envelope";

export async function GET() { return ok(await listSchoolUsers()); }

export async function POST(req: Request) {
  const input = await req.json();
  const r = await createSchoolUsers(input);
  return r.ok ? ok(r.data, 201) : err("VALIDATION_FAILED", 422, r.errors);
}
