// GENERATED by gen_fixtures from canonical.json — DO NOT EDIT. Valid sample records, no hardcoded literals.
// Usage: sample("schools", { status: "lead" })  — fills schema fields; you pass FKs/status/specific overrides.
const SAMPLES: Record<string, Record<string, unknown>> = {
  "audit_events": {
    "trace_id": "audit_events-trace_id",
    "actor_role": "audit_events-actor_role",
    "action": "audit_events-action",
    "entity_name": "audit_events-entity_name",
    "entity_id": "audit_events-entity_id",
    "previous_status": "audit_events-previous_status",
    "new_status": "audit_events-new_status",
    "ip_address": "audit_events-ip_address",
    "external_reference": "audit_events-external_reference",
    "reason": "audit_events-reason"
  },
  "certificates": {
    "certificate_number": "certificates-certificate_number",
    "verification_code": "certificates-verification_code",
    "certificate_type": "certificates-certificate_type",
    "pdf_file": "certificates-pdf_file",
    "issued_at": "2026-01-01",
    "revoked_at": "2026-01-01",
    "revocation_reason": "certificates-revocation_reason"
  },
  "courier_batches": {
    "batch_code": "courier_batches-batch_code",
    "courier_company": "courier_batches-courier_company",
    "awb_number": "courier_batches-awb_number",
    "dispatch_date": "2026-01-01",
    "package_count": "100",
    "sheets_expected": "100",
    "sheets_dispatched": "100",
    "sheets_received": "100",
    "receipt_file": "courier_batches-receipt_file",
    "seal_condition": "courier_batches-seal_condition"
  },
  "email_campaigns": {
    "name": "email_campaigns-name",
    "subject": "email_campaigns-subject",
    "html_content": "email_campaigns-html_content",
    "attachments": "email_campaigns-attachments",
    "channel": "outreach",
    "provider": "email_campaigns-provider",
    "segment": "email_campaigns-segment",
    "scheduled_at": "2026-01-01T00:00:00Z",
    "sent_count": "100",
    "delivered_count": "100",
    "opened_count": "100",
    "bounced_count": "100",
    "target_ids": "email_campaigns-target_ids",
    "provider_campaign_id": "email_campaigns-provider_campaign_id",
    "provider_url": "email_campaigns-provider_url",
    "recipient_emails": ""
  },
  "email_sends": {
    "send_ref": "email_sends-send_ref",
    "email": "email_sends.email@example.test",
    "provider_message_id": "email_sends-provider_message_id",
    "sent_at": "2026-01-01T00:00:00Z",
    "delivered_at": "2026-01-01T00:00:00Z",
    "opened_at": "2026-01-01T00:00:00Z"
  },
  "exam_materials": {
    "material_code": "exam_materials-material_code",
    "material_type": "exam_materials-material_type",
    "file": "exam_materials-file",
    "release_at": "2026-01-01",
    "expires_at": "2026-01-01",
    "download_count": "100"
  },
  "exam_slots": {
    "slot_code": "exam_slots-slot_code",
    "exam_date": "2026-01-01",
    "start_time": "10:00",
    "end_time": "10:00",
    "timezone": "10:00",
    "mode": "exam_slots-mode",
    "capacity_schools": "100",
    "capacity_students": "100",
    "booked_schools": "100",
    "booked_students": "100",
    "eligible_grades": "exam_slots-eligible_grades"
  },
  "olympiads": {
    "name": "olympiads-name",
    "academic_year": "olympiads-academic_year",
    "subject": "olympiads-subject",
    "eligible_grades": "olympiads-eligible_grades",
    "registration_open_at": "2026-01-01",
    "registration_close_at": "2026-01-01",
    "exam_window_start": "olympiads-exam_window_start",
    "exam_window_end": "olympiads-exam_window_end",
    "fee_per_student": "100",
    "school_commission_per_student": "100",
    "max_marks": "100"
  },
  "omr_imports": {
    "import_code": "omr_imports-import_code",
    "uploaded_file": "omr_imports-uploaded_file",
    "row_count": "100",
    "valid_count": "100",
    "error_count": "100",
    "review_status": "omr_imports-review_status"
  },
  "participations": {
    "participation_code": "participations-participation_code",
    "estimated_student_count": "100",
    "confirmed_student_count": "100",
    "gross_amount": "100",
    "commission_amount": "100",
    "net_amount_payable": "100",
    "payment_status": "participations-payment_status",
    "consent_declaration_status": "participations-consent_declaration_status",
    "locked_at": "2026-01-01"
  },
  "payments": {
    "payment_code": "payments-payment_code",
    "expected_amount": "100",
    "received_amount": "100",
    "provider": "payments-provider",
    "provider_link_id": "payments-provider_link_id",
    "provider_payment_id": "payments-provider_payment_id",
    "payment_reference": "payments-payment_reference",
    "manual_evidence_file": "payments-manual_evidence_file",
    "reversal_reason": "payments-reversal_reason",
    "reconciled_at": "2026-01-01"
  },
  "results": {
    "result_code": "results-result_code",
    "raw_score": "100",
    "max_marks": "100",
    "percentage": "100",
    "school_rank": "100",
    "city_rank": "100",
    "state_rank": "100",
    "national_rank": "100",
    "award_category": "results-award_category"
  },
  "school_imports": {
    "import_code": "school_imports-import_code",
    "source": "school_imports-source",
    "file": "school_imports-file",
    "total_rows": "100",
    "imported_count": "100",
    "failed_count": "100",
    "error_summary": "school_imports-error_summary",
    "mapping": "school_imports-mapping"
  },
  "school_users": {
    "role_label": "school_users-role_label",
    "is_primary": true
  },
  "schools": {
    "name": "schools-name",
    "board": "schools-board",
    "city": "schools-city",
    "state": "schools-state",
    "country": "schools-country",
    "address_line1": "schools-address_line1",
    "address_line2": "schools-address_line2",
    "locality": "schools-locality",
    "pincode": "100000",
    "principal_name": "schools-principal_name",
    "coordinator_name": "schools-coordinator_name",
    "coordinator_email": "schools.coordinator_email@example.test",
    "coordinator_mobile": "9000000000",
    "website": "schools-website",
    "source": "import",
    "unsubscribed": true,
    "last_contacted_at": "2026-01-01T00:00:00Z",
    "referral": "schools-referral"
  },
  "students": {
    "student_name": "students-student_name",
    "grade": "students-grade",
    "section": "students-section",
    "school_roll_number": "students-school_roll_number",
    "parent_guardian_name": "students-parent_guardian_name",
    "parent_contact": "9000000000",
    "consent_obtained": true,
    "consent_date": "2026-01-01",
    "validation_errors": "students-validation_errors"
  },
  "users": {
    "email": "users.email@example.test",
    "full_name": "users-full_name",
    "role": "super_admin",
    "user_status": "invited"
  }
};

export function sample(entity: string, overrides: Record<string, unknown> = {}): Record<string, unknown> {
  return { ...(SAMPLES[entity] || {}), ...overrides };
}
