// GENERATED by gen_routes (Robot 6) — DO NOT EDIT.
import { listReEvaluations, createReEvaluations } from "@/services/re_evaluations.service";
import { ok, err } from "@/runtime/envelope";

export async function GET() { return ok(await listReEvaluations()); }

export async function POST(req: Request) {
  const input = await req.json();
  const r = await createReEvaluations(input);
  return r.ok ? ok(r.data, 201) : err("VALIDATION_FAILED", 422, r.errors);
}
