// GENERATED by gen_routes (Robot 6) — DO NOT EDIT.
import { listAuditEvents, createAuditEvents } from "@/services/audit_events.service";
import { ok, err } from "@/runtime/envelope";

export async function GET() { return ok(await listAuditEvents()); }

export async function POST(req: Request) {
  const input = await req.json();
  const r = await createAuditEvents(input);
  return r.ok ? ok(r.data, 201) : err("VALIDATION_FAILED", 422, r.errors);
}
