// GENERATED by gen_routes (Robot 6) — DO NOT EDIT.
import { getExamSlots, updateExamSlots } from "@/services/exam_slots.service";
import { ok, err } from "@/runtime/envelope";

export async function GET(_req: Request, { params }: { params: { id: string } }) {
  const row = await getExamSlots(params.id);
  return row ? ok(row) : err("NOT_FOUND", 404, "exam_slots not found");
}

export async function PATCH(req: Request, { params }: { params: { id: string } }) {
  return ok(await updateExamSlots(params.id, await req.json()));
}
