// GENERATED by gen_routes (Robot 6) — DO NOT EDIT.
import { listSchools, createSchools } from "@/services/schools.service";
import { ok, err } from "@/runtime/envelope";

export async function GET() { return ok(await listSchools()); }

export async function POST(req: Request) {
  const input = await req.json();
  const r = await createSchools(input);
  return r.ok ? ok(r.data, 201) : err("VALIDATION_FAILED", 422, r.errors);
}
