-- GENERATED by gen_db (Robot 4) from canonical.json — DO NOT EDIT. Edit the source + re-run.
-- Tables in dependency build-order: every FK target exists before the table that references it.
-- RLS (school scoping) is emitted later in the AUTH phase (0002_rls.sql), not here.

CREATE TABLE "email_campaigns" (
  "id" uuid NOT NULL,
  "campaign_code" text,
  "name" text NOT NULL,
  "subject" text NOT NULL,
  "html_content" text NOT NULL,
  "attachments" text,
  "channel" text NOT NULL CHECK ("channel" IN ('outreach', 'transactional')),
  "provider" text,
  "segment" text,
  "status" text CHECK ("status" IN ('cancelled', 'draft', 'in_brevo', 'paused', 'scheduled', 'sending', 'sent')),
  "scheduled_at" timestamptz,
  "sent_count" integer,
  "delivered_count" integer,
  "opened_count" integer,
  "bounced_count" integer,
  "target_ids" text,
  "provider_campaign_id" text,
  "provider_url" text,
  "recipient_emails" text,
  "created_at" timestamptz,
  "updated_at" timestamptz,
  PRIMARY KEY ("id")
);

CREATE TABLE "exam_slots" (
  "id" uuid NOT NULL,
  "slot_code" text NOT NULL,
  "exam_date" date NOT NULL,
  "start_time" text NOT NULL,
  "end_time" text NOT NULL,
  "timezone" text,
  "mode" text,
  "capacity_schools" integer NOT NULL,
  "capacity_students" integer NOT NULL,
  "booked_schools" integer,
  "booked_students" integer,
  "eligible_grades" jsonb,
  "status" text CHECK ("status" IN ('cancelled', 'changed', 'closed', 'draft', 'full', 'open', 'selected', 'slot_confirmed')),
  PRIMARY KEY ("id")
);

CREATE TABLE "olympiads" (
  "id" uuid NOT NULL,
  "olympiad_code" text,
  "name" text NOT NULL,
  "academic_year" text NOT NULL,
  "subject" text NOT NULL,
  "eligible_grades" jsonb NOT NULL,
  "registration_open_at" timestamptz NOT NULL,
  "registration_close_at" timestamptz NOT NULL,
  "exam_window_start" timestamptz NOT NULL,
  "exam_window_end" timestamptz NOT NULL,
  "fee_per_student" numeric NOT NULL,
  "school_commission_per_student" numeric NOT NULL,
  "max_marks" integer NOT NULL,
  "status" text CHECK ("status" IN ('archived', 'closed', 'draft', 'open')),
  "exam_duration_minutes" integer,
  "negative_marking_enabled" boolean,
  "negative_marks" numeric,
  "re_eval_window_days" integer,
  "re_eval_fee" numeric,
  "merit_top_percent" integer,
  PRIMARY KEY ("id")
);

CREATE TABLE "school_imports" (
  "id" uuid NOT NULL,
  "import_code" text NOT NULL UNIQUE,
  "source" text NOT NULL,
  "file" text NOT NULL,
  "total_rows" integer,
  "imported_count" integer,
  "failed_count" integer,
  "status" text CHECK ("status" IN ('failed', 'imported', 'uploaded', 'validating')),
  "error_summary" text,
  "mapping" text,
  "created_at" timestamptz,
  "updated_at" timestamptz,
  PRIMARY KEY ("id")
);

CREATE TABLE "users" (
  "id" uuid NOT NULL,
  "email" text NOT NULL UNIQUE,
  "full_name" text NOT NULL,
  "role" text NOT NULL CHECK ("role" IN ('super_admin', 'company_admin', 'operations_head', 'operations_executive', 'sales_executive', 'school_onboarding_executive', 'finance_admin', 'finance_executive', 'exam_operations_manager', 'content_manager', 'material_release_manager', 'courier_manager', 'evaluation_manager', 'omr_import_operator', 'results_approver', 'certificate_manager', 'notifications_manager', 'support_executive', 'security_reviewer', 'auditor', 'school_coordinator', 'school_principal')),
  "user_status" text NOT NULL CHECK ("user_status" IN ('invited', 'active', 'suspended', 'disabled')),
  "created_at" timestamptz,
  "updated_at" timestamptz,
  PRIMARY KEY ("id")
);

CREATE TABLE "answer_keys" (
  "id" uuid NOT NULL,
  "answer_key_code" text,
  "olympiad_id" uuid NOT NULL,
  "grade" text NOT NULL,
  "total_questions" integer NOT NULL,
  "key" jsonb NOT NULL,
  "status" text CHECK ("status" IN ('archived', 'draft', 'published')),
  "created_at" timestamptz,
  "updated_at" timestamptz,
  PRIMARY KEY ("id"),
  FOREIGN KEY ("olympiad_id") REFERENCES "olympiads" ("id")
);

CREATE TABLE "audit_events" (
  "id" uuid NOT NULL,
  "trace_id" text NOT NULL,
  "actor_user_id" uuid,
  "actor_role" text NOT NULL,
  "action" text NOT NULL,
  "entity_name" text NOT NULL,
  "entity_id" text NOT NULL,
  "previous_status" text,
  "new_status" text,
  "ip_address" text,
  "external_reference" text,
  "reason" text,
  "created_at" timestamptz,
  PRIMARY KEY ("id"),
  FOREIGN KEY ("actor_user_id") REFERENCES "users" ("id")
);

CREATE TABLE "schools" (
  "id" uuid NOT NULL,
  "school_code" text,
  "name" text NOT NULL,
  "board" text,
  "city" text NOT NULL,
  "state" text NOT NULL,
  "country" text,
  "address_line1" text,
  "address_line2" text,
  "locality" text,
  "pincode" text,
  "principal_name" text,
  "coordinator_name" text NOT NULL,
  "coordinator_email" text NOT NULL UNIQUE,
  "coordinator_mobile" text,
  "status" text CHECK ("status" IN ('approved', 'blocked', 'inactive', 'lead', 'prospect', 'registered', 'rejected')),
  "created_at" timestamptz,
  "updated_at" timestamptz,
  "website" text,
  "source" text NOT NULL CHECK ("source" IN ('import', 'manual', 'self')),
  "unsubscribed" boolean,
  "last_contacted_at" timestamptz,
  "import_id" uuid,
  "olympiad_interest_id" uuid,
  "referral" text,
  PRIMARY KEY ("id"),
  FOREIGN KEY ("import_id") REFERENCES "school_imports" ("id"),
  FOREIGN KEY ("olympiad_interest_id") REFERENCES "olympiads" ("id")
);

CREATE TABLE "study_resources" (
  "id" uuid NOT NULL,
  "resource_code" text,
  "olympiad_id" uuid NOT NULL,
  "grade" text,
  "kind" text CHECK ("kind" IN ('syllabus', 'sample_paper', 'guide')),
  "title" text NOT NULL,
  "url" text NOT NULL,
  "status" text CHECK ("status" IN ('archived', 'draft', 'published')),
  "created_at" timestamptz,
  "updated_at" timestamptz,
  PRIMARY KEY ("id"),
  FOREIGN KEY ("olympiad_id") REFERENCES "olympiads" ("id")
);

CREATE TABLE "email_sends" (
  "id" uuid NOT NULL,
  "send_ref" text NOT NULL UNIQUE,
  "campaign_id" uuid NOT NULL,
  "school_id" uuid NOT NULL,
  "email" text NOT NULL,
  "status" text CHECK ("status" IN ('bounced', 'clicked', 'delivered', 'failed', 'opened', 'queued', 'sent', 'unsubscribed')),
  "provider_message_id" text,
  "sent_at" timestamptz,
  "delivered_at" timestamptz,
  "opened_at" timestamptz,
  "created_at" timestamptz,
  "updated_at" timestamptz,
  PRIMARY KEY ("id"),
  FOREIGN KEY ("campaign_id") REFERENCES "email_campaigns" ("id"),
  FOREIGN KEY ("school_id") REFERENCES "schools" ("id")
);

CREATE TABLE "participations" (
  "id" uuid NOT NULL,
  "participation_code" text,
  "school_id" uuid NOT NULL,
  "olympiad_id" uuid NOT NULL,
  "estimated_student_count" integer,
  "confirmed_student_count" integer,
  "gross_amount" numeric,
  "commission_amount" numeric,
  "net_amount_payable" numeric,
  "payment_status" text,
  "exam_slot_id" uuid,
  "consent_declaration_status" text,
  "status" text CHECK ("status" IN ('approved', 'cancelled', 'certificates_released', 'count_finalised', 'draft', 'exam_completed', 'locked', 'materials_released', 'paid', 'payment_pending', 'renewed', 'results_published', 'slot_confirmed', 'students_open', 'submitted', 'upload_received', 'validation_failed', 'validation_passed')),
  "locked_at" timestamptz,
  PRIMARY KEY ("id"),
  FOREIGN KEY ("school_id") REFERENCES "schools" ("id"),
  FOREIGN KEY ("olympiad_id") REFERENCES "olympiads" ("id"),
  FOREIGN KEY ("exam_slot_id") REFERENCES "exam_slots" ("id")
);

CREATE TABLE "school_settings" (
  "id" uuid NOT NULL,
  "settings_code" text,
  "school_id" uuid NOT NULL,
  "display_name" text,
  "emblem_url" text,
  "emblem_on_certificate" text CHECK ("emblem_on_certificate" IN ('no', 'yes')),
  "contact_email" text,
  "created_at" timestamptz,
  "updated_at" timestamptz,
  PRIMARY KEY ("id"),
  FOREIGN KEY ("school_id") REFERENCES "schools" ("id")
);

CREATE TABLE "school_users" (
  "id" uuid NOT NULL,
  "directus_user_id" uuid NOT NULL,
  "school_id" uuid NOT NULL,
  "role_label" text,
  "is_primary" boolean,
  "status" text,
  PRIMARY KEY ("id"),
  FOREIGN KEY ("directus_user_id") REFERENCES "users" ("id"),
  FOREIGN KEY ("school_id") REFERENCES "schools" ("id")
);

CREATE TABLE "courier_batches" (
  "id" uuid NOT NULL,
  "batch_code" text NOT NULL,
  "school_id" uuid NOT NULL,
  "participation_id" uuid NOT NULL,
  "courier_company" text NOT NULL,
  "awb_number" text NOT NULL,
  "dispatch_date" date NOT NULL,
  "package_count" integer NOT NULL,
  "sheets_expected" integer NOT NULL,
  "sheets_dispatched" integer NOT NULL,
  "sheets_received" integer,
  "receipt_file" text,
  "seal_condition" text,
  "status" text CHECK ("status" IN ('closed', 'dispatched', 'exception', 'pending', 'received')),
  PRIMARY KEY ("id"),
  FOREIGN KEY ("school_id") REFERENCES "schools" ("id"),
  FOREIGN KEY ("participation_id") REFERENCES "participations" ("id")
);

CREATE TABLE "exam_materials" (
  "id" uuid NOT NULL,
  "material_code" text NOT NULL,
  "participation_id" uuid,
  "olympiad_id" uuid NOT NULL,
  "exam_slot_id" uuid,
  "material_type" text,
  "file" text NOT NULL,
  "release_at" timestamptz NOT NULL,
  "expires_at" timestamptz,
  "download_count" integer,
  "status" text CHECK ("status" IN ('approved', 'draft', 'expired', 'release_scheduled', 'released', 'revoked')),
  PRIMARY KEY ("id"),
  FOREIGN KEY ("participation_id") REFERENCES "participations" ("id"),
  FOREIGN KEY ("olympiad_id") REFERENCES "olympiads" ("id"),
  FOREIGN KEY ("exam_slot_id") REFERENCES "exam_slots" ("id")
);

CREATE TABLE "payments" (
  "id" uuid NOT NULL,
  "payment_code" text NOT NULL,
  "participation_id" uuid NOT NULL,
  "school_id" uuid NOT NULL,
  "expected_amount" numeric NOT NULL,
  "received_amount" numeric,
  "provider" text,
  "provider_link_id" text,
  "provider_payment_id" text,
  "payment_reference" text,
  "status" text CHECK ("status" IN ('draft', 'expired', 'failed', 'link_created', 'manually_confirmed', 'paid', 'pending', 'reconciled', 'reversed')),
  "manual_evidence_file" text NOT NULL,
  "reversal_reason" text NOT NULL,
  "reconciled_at" timestamptz,
  PRIMARY KEY ("id"),
  FOREIGN KEY ("participation_id") REFERENCES "participations" ("id"),
  FOREIGN KEY ("school_id") REFERENCES "schools" ("id")
);

CREATE TABLE "students" (
  "id" uuid NOT NULL,
  "candidate_id" text,
  "school_id" uuid NOT NULL,
  "participation_id" uuid NOT NULL,
  "student_name" text NOT NULL,
  "grade" text NOT NULL,
  "section" text,
  "school_roll_number" text UNIQUE,
  "parent_guardian_name" text,
  "parent_contact" text,
  "consent_obtained" boolean NOT NULL,
  "consent_date" date,
  "status" text,
  "validation_errors" jsonb,
  "exam_attendance" text CHECK ("exam_attendance" IN ('not_marked', 'present', 'absent')),
  PRIMARY KEY ("id"),
  FOREIGN KEY ("school_id") REFERENCES "schools" ("id"),
  FOREIGN KEY ("participation_id") REFERENCES "participations" ("id")
);

CREATE TABLE "admit_cards" (
  "id" uuid NOT NULL,
  "admit_card_code" text,
  "student_id" uuid NOT NULL,
  "participation_id" uuid NOT NULL,
  "school_id" uuid NOT NULL,
  "exam_slot_id" uuid,
  "candidate_id" text,
  "venue" text,
  "status" text CHECK ("status" IN ('generated', 'issued')),
  "created_at" timestamptz,
  "updated_at" timestamptz,
  PRIMARY KEY ("id"),
  FOREIGN KEY ("student_id") REFERENCES "students" ("id"),
  FOREIGN KEY ("participation_id") REFERENCES "participations" ("id"),
  FOREIGN KEY ("school_id") REFERENCES "schools" ("id"),
  FOREIGN KEY ("exam_slot_id") REFERENCES "exam_slots" ("id")
);

CREATE TABLE "omr_imports" (
  "id" uuid NOT NULL,
  "import_code" text NOT NULL,
  "participation_id" uuid NOT NULL,
  "courier_batch_id" uuid NOT NULL,
  "uploaded_file" text NOT NULL,
  "row_count" integer,
  "valid_count" integer,
  "error_count" integer,
  "review_status" text,
  "uploaded_by" uuid NOT NULL,
  "approved_by" uuid,
  "status" text CHECK ("status" IN ('approved', 'awaiting_import', 'exceptions_found', 'imported', 'rejected', 'reviewed')),
  PRIMARY KEY ("id"),
  FOREIGN KEY ("participation_id") REFERENCES "participations" ("id"),
  FOREIGN KEY ("courier_batch_id") REFERENCES "courier_batches" ("id"),
  FOREIGN KEY ("uploaded_by") REFERENCES "users" ("id"),
  FOREIGN KEY ("approved_by") REFERENCES "users" ("id")
);

CREATE TABLE "results" (
  "id" uuid NOT NULL,
  "result_code" text,
  "student_id" uuid NOT NULL,
  "participation_id" uuid NOT NULL,
  "school_id" uuid NOT NULL,
  "raw_score" numeric NOT NULL,
  "max_marks" numeric NOT NULL,
  "percentage" numeric,
  "school_rank" integer,
  "city_rank" integer,
  "state_rank" integer,
  "national_rank" integer,
  "award_category" text,
  "status" text CHECK ("status" IN ('approved', 'corrected', 'draft', 'imported', 'published', 'under_review', 'withheld')),
  "responses" jsonb,
  PRIMARY KEY ("id"),
  FOREIGN KEY ("student_id") REFERENCES "students" ("id"),
  FOREIGN KEY ("participation_id") REFERENCES "participations" ("id"),
  FOREIGN KEY ("school_id") REFERENCES "schools" ("id")
);

CREATE TABLE "awards" (
  "id" uuid NOT NULL,
  "award_code" text,
  "result_id" uuid NOT NULL,
  "student_id" uuid NOT NULL,
  "school_id" uuid NOT NULL,
  "award_type" text CHECK ("award_type" IN ('gold', 'silver', 'bronze', 'merit')),
  "tracking_ref" text,
  "status" text CHECK ("status" IN ('delivered', 'dispatched', 'pending')),
  "created_at" timestamptz,
  "updated_at" timestamptz,
  PRIMARY KEY ("id"),
  FOREIGN KEY ("result_id") REFERENCES "results" ("id"),
  FOREIGN KEY ("student_id") REFERENCES "students" ("id"),
  FOREIGN KEY ("school_id") REFERENCES "schools" ("id")
);

CREATE TABLE "certificates" (
  "id" uuid NOT NULL,
  "certificate_number" text NOT NULL,
  "verification_code" text NOT NULL,
  "student_id" uuid NOT NULL,
  "result_id" uuid NOT NULL,
  "school_id" uuid NOT NULL,
  "certificate_type" text,
  "pdf_file" text,
  "issued_at" timestamptz,
  "revoked_at" timestamptz,
  "revocation_reason" text NOT NULL,
  "status" text CHECK ("status" IN ('draft', 'generated', 'invalid', 'issued', 'rate_limited', 'revoked', 'valid')),
  PRIMARY KEY ("id"),
  FOREIGN KEY ("student_id") REFERENCES "students" ("id"),
  FOREIGN KEY ("result_id") REFERENCES "results" ("id"),
  FOREIGN KEY ("school_id") REFERENCES "schools" ("id")
);

CREATE TABLE "re_evaluations" (
  "id" uuid NOT NULL,
  "re_eval_code" text,
  "result_id" uuid NOT NULL,
  "student_id" uuid NOT NULL,
  "school_id" uuid NOT NULL,
  "reason" text NOT NULL,
  "fee" numeric,
  "revised_score" numeric,
  "resolution_note" text,
  "status" text CHECK ("status" IN ('rejected', 'requested', 'resolved', 'under_review')),
  "created_at" timestamptz,
  "updated_at" timestamptz,
  PRIMARY KEY ("id"),
  FOREIGN KEY ("result_id") REFERENCES "results" ("id"),
  FOREIGN KEY ("student_id") REFERENCES "students" ("id"),
  FOREIGN KEY ("school_id") REFERENCES "schools" ("id")
);
