// GENERATED by _validation/gen_modules.py — DO NOT EDIT.
import { NextRequest, NextResponse } from "next/server";
import { requireStaffScope } from "@/server/guards/requireStaffScope";
import { ok, err, meta } from "@/server/http/envelope";
import { ValidationError } from "@/server/lib/defineModule";
import { reviewChildRecord } from "@/server/lib/childWrite";

export async function PATCH(request: NextRequest, ctx: { params: Promise<{ id: string; cid: string }> }) {
  const guard = await requireStaffScope(request, "school_onboarding_ops", "write");
  if (!guard.ok) return NextResponse.json(guard.body, { status: guard.status });
  const { id, cid } = await ctx.params;
  let body: Record<string, unknown> = {};
  try { body = (await request.json()) as Record<string, unknown>; } catch { body = {}; }
  try {
    return NextResponse.json(ok(await reviewChildRecord("school_onboarding_documents", cid, "onboarding_case_id", id, body, guard.actor, {"editable": ["review_status", "review_note"], "reviewerColumn": "reviewed_by", "reviewedAtColumn": "reviewed_at", "module": "school_onboarding_ops"}), meta(guard.requestId, "school_onboarding_ops")));
  } catch (e) {
    if (e instanceof ValidationError) return NextResponse.json(err("VALIDATION_FAILED", "Validation failed.", meta(guard.requestId, "school_onboarding_ops"), { field_errors: e.fieldErrors }), { status: 422 });
    return NextResponse.json(err("INTERNAL", "Unexpected error.", meta(guard.requestId, "school_onboarding_ops")), { status: 500 });
  }
}
