// GENERATED by gen_routes (Robot 6) — DO NOT EDIT.
import { listCourierBatches, createCourierBatches } from "@/services/courier_batches.service";
import { ok, err } from "@/runtime/envelope";

export async function GET() { return ok(await listCourierBatches()); }

export async function POST(req: Request) {
  const input = await req.json();
  const r = await createCourierBatches(input);
  return r.ok ? ok(r.data, 201) : err("VALIDATION_FAILED", 422, r.errors);
}
