// GENERATED by gen_pages.py from spec/pages/staff_security_integrity.json — DO NOT EDIT. Edit the spec/component + regenerate.
import { IntegrityView } from "@/components/IntegrityView";

export default function Page() {
  return <IntegrityView />;
}
