// GENERATED by gen_routes (Robot 6) — DO NOT EDIT.
import { getSchoolImports, updateSchoolImports, deleteSchoolImports } from "@/services/school_imports.service";
import { ok, err } from "@/runtime/envelope";

export async function GET(_req: Request, { params }: { params: { id: string } }) {
  const row = await getSchoolImports(params.id);
  return row ? ok(row) : err("NOT_FOUND", 404, "school_imports not found");
}

export async function PATCH(req: Request, { params }: { params: { id: string } }) {
  return ok(await updateSchoolImports(params.id, await req.json()));
}

export async function DELETE(_req: Request, { params }: { params: { id: string } }) {
  return ok(await deleteSchoolImports(params.id));
}
