// GENERATED by gen_routes (Robot 6) — DO NOT EDIT.
import { listEmailSends, createEmailSends } from "@/services/email_sends.service";
import { ok, err } from "@/runtime/envelope";

export async function GET() { return ok(await listEmailSends()); }

export async function POST(req: Request) {
  const input = await req.json();
  const r = await createEmailSends(input);
  return r.ok ? ok(r.data, 201) : err("VALIDATION_FAILED", 422, r.errors);
}
