// GENERATED by gen_routes (Robot 6) — DO NOT EDIT.
import { getStudyResources, updateStudyResources, deleteStudyResources } from "@/services/study_resources.service";
import { ok, err } from "@/runtime/envelope";

export async function GET(_req: Request, { params }: { params: { id: string } }) {
  const row = await getStudyResources(params.id);
  return row ? ok(row) : err("NOT_FOUND", 404, "study_resources not found");
}

export async function PATCH(req: Request, { params }: { params: { id: string } }) {
  return ok(await updateStudyResources(params.id, await req.json()));
}

export async function DELETE(_req: Request, { params }: { params: { id: string } }) {
  return ok(await deleteStudyResources(params.id));
}
