// GENERATED by gen_routes (Robot 6) — DO NOT EDIT.
import { listCertificates, createCertificates } from "@/services/certificates.service";
import { ok, err } from "@/runtime/envelope";

export async function GET() { return ok(await listCertificates()); }

export async function POST(req: Request) {
  const input = await req.json();
  const r = await createCertificates(input);
  return r.ok ? ok(r.data, 201) : err("VALIDATION_FAILED", 422, r.errors);
}
