// GENERATED by gen_routes (Robot 6) — DO NOT EDIT.
import { getCourierBatches, updateCourierBatches } from "@/services/courier_batches.service";
import { ok, err } from "@/runtime/envelope";

export async function GET(_req: Request, { params }: { params: { id: string } }) {
  const row = await getCourierBatches(params.id);
  return row ? ok(row) : err("NOT_FOUND", 404, "courier_batches not found");
}

export async function PATCH(req: Request, { params }: { params: { id: string } }) {
  return ok(await updateCourierBatches(params.id, await req.json()));
}
