// GENERATED by gen_routes (Robot 6) — DO NOT EDIT.
import { getAdmitCards, updateAdmitCards, deleteAdmitCards } from "@/services/admit_cards.service";
import { ok, err } from "@/runtime/envelope";

export async function GET(_req: Request, { params }: { params: { id: string } }) {
  const row = await getAdmitCards(params.id);
  return row ? ok(row) : err("NOT_FOUND", 404, "admit_cards not found");
}

export async function PATCH(req: Request, { params }: { params: { id: string } }) {
  return ok(await updateAdmitCards(params.id, await req.json()));
}

export async function DELETE(_req: Request, { params }: { params: { id: string } }) {
  return ok(await deleteAdmitCards(params.id));
}
