from __future__ import annotations

import argparse
from pathlib import Path
from common import ROOT, read_csv, write_csv, load_state, snake_case

DEFAULT_MODULES = [
    ("company_dashboard", "Company Dashboard", "operations"),
    ("staff_users", "Staff Users", "admin"),
    ("roles_permissions", "Roles & Permissions", "security_operations"),
    ("school_crm", "School CRM", "sales_operations"),
    ("school_onboarding_ops", "School Onboarding Ops", "operations"),
    ("student_roster_ops", "Student Roster Ops", "operations"),
    ("finance_ops", "Finance Ops", "finance"),
    ("exam_slot_ops", "Exam Slot Ops", "exam_operations"),
    ("exam_material_ops", "Exam Material Ops", "exam_operations"),
    ("courier_ops", "Courier Ops", "logistics"),
    ("evaluation_ops", "Evaluation Ops", "evaluation"),
    ("results_ops", "Results Ops", "results"),
    ("certificate_ops", "Certificate Ops", "certificates"),
    ("notification_ops", "Notification Ops", "communications"),
    ("support_tickets", "Support Tickets", "support"),
    ("task_work_queue", "Task Work Queue", "operations"),
    ("reports_exports", "Reports & Exports", "analytics"),
    ("admin_settings", "Admin Settings", "admin"),
    ("security_audit_console", "Security & Audit Console", "security_operations")
]

def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", default=str(ROOT / "outputs" / "source_of_truth" / "answered_source_of_truth.csv"))
    parser.add_argument("--out", default=str(ROOT / "outputs" / "source_of_truth" / "module_registry.csv"))
    args = parser.parse_args()

    state = load_state()
    completed = set(state.get("completed_modules", []))

    rows = []
    for i, (mid, name, owner) in enumerate(DEFAULT_MODULES, 1):
        rows.append({
            "priority_order": str(i),
            "module_id": mid,
            "module_name": name,
            "module_type": "company_portal_module",
            "owner": owner,
            "purpose": f"{name} module generated by Versa Spec Playbook.",
            "depends_on": "",
            "provides": "",
            "consumed_by": "",
            "status": "COMPLETED_FOR_REVIEW" if mid in completed else "PENDING",
            "recommended_generation_order": str(i)
        })

    headers = ["priority_order","module_id","module_name","module_type","owner","purpose","depends_on","provides","consumed_by","status","recommended_generation_order"]
    write_csv(Path(args.out), rows, headers)
    print(f"Wrote module registry: {args.out}")

if __name__ == "__main__":
    main()
