// GENERATED by gen_routes (Robot 6) — DO NOT EDIT.
import { getPayments, updatePayments, deletePayments } from "@/services/payments.service";
import { ok, err } from "@/runtime/envelope";

export async function GET(_req: Request, { params }: { params: { id: string } }) {
  const row = await getPayments(params.id);
  return row ? ok(row) : err("NOT_FOUND", 404, "payments not found");
}

export async function PATCH(req: Request, { params }: { params: { id: string } }) {
  return ok(await updatePayments(params.id, await req.json()));
}

export async function DELETE(_req: Request, { params }: { params: { id: string } }) {
  return ok(await deletePayments(params.id));
}
