// GENERATED by gen_routes (Robot 6) — DO NOT EDIT.
import { transitionCertificates } from "@/services/certificates.service";
import { ok, err } from "@/runtime/envelope";

export async function POST(_req: Request, { params }: { params: { id: string; action: string } }) {
  try { return ok(await transitionCertificates(params.id, params.action as never)); }
  catch (e) { return err("ILLEGAL_TRANSITION", 409, String((e as Error).message)); }
}
