// GENERATED by gen_pages.py from spec/pages/staff_reports_exports.json — DO NOT EDIT. Edit the spec/component + regenerate.
import { ReportExportsView } from "@/components/ReportExportsView";

export default function Page() {
  return <ReportExportsView />;
}
