// GENERATED by gen_routes (Robot 6) — DO NOT EDIT.
import { getEmailSends, updateEmailSends, deleteEmailSends } from "@/services/email_sends.service";
import { ok, err } from "@/runtime/envelope";

export async function GET(_req: Request, { params }: { params: { id: string } }) {
  const row = await getEmailSends(params.id);
  return row ? ok(row) : err("NOT_FOUND", 404, "email_sends not found");
}

export async function PATCH(req: Request, { params }: { params: { id: string } }) {
  return ok(await updateEmailSends(params.id, await req.json()));
}

export async function DELETE(_req: Request, { params }: { params: { id: string } }) {
  return ok(await deleteEmailSends(params.id));
}
