// GENERATED by gen_endpoints.py from spec/endpoints/staff_lookup.json — DO NOT EDIT. Edit the spec + regenerate.
import { NextRequest, NextResponse } from "next/server";
import { requireStaffScope } from "@/server/guards/requireStaffScope";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";
import { LOOKUP_LABELS } from "@/server/lookups/labelColumns.generated";
import { ok, err, meta } from "@/server/http/envelope";
import { lookupQuery, lookupResult, escapeLike } from "@/server/lookups/query";

const MOD = "company_dashboard"; // any authenticated staff may read reference data

export async function GET(request: NextRequest, ctx: { params: Promise<{ table: string }> }) {
  const { table } = await ctx.params;
  const guard = await requireStaffScope(request, MOD, "read");
  if (!guard.ok) return NextResponse.json(guard.body, { status: guard.status });

  const labelCol = LOOKUP_LABELS[table];
  if (!labelCol) return NextResponse.json(err("NOT_FOUND", "Not a reference table.", meta(guard.requestId, MOD)), { status: 404 });

  const { q, limit } = lookupQuery(request);
  const supabase = createSupabaseAdminClient();
  let query = supabase.from(table).select(`id, ${labelCol}`);
  if (q && labelCol !== "id") query = query.ilike(labelCol, `%${escapeLike(q)}%`);
  const { data, error } = await query.order(labelCol === "id" ? "id" : labelCol, { ascending: true }).limit(limit + 1);
  if (error) return NextResponse.json(ok({ items: [], hasMore: false }, meta(guard.requestId, MOD)));
  return NextResponse.json(ok(lookupResult(data, labelCol, limit), meta(guard.requestId, MOD)));
}
